### ISSUE TITLE
Blockchain trust management

### ISSUE THREAD

**Issue by mappum** [cosmos/voyager#100]
Since we are using light-clients, we will need to expose a little bit of blockchain trust management to users.

When we init the light-client for the first time, it gives us a block hash to accept or reject, and all the chain verification after that point connects back to that initial block hash (so if it's on a fork, your client will be stuck on that fork). Currently, we always accept that hash (we were previously assuming it came from a trusted full node), but we need a smarter strategy about choosing whether or not the hash is valid.

This trust management will also have to happen if the user has not started up the wallet in longer than 1 month (the unbonding period).

We can do this a few different ways through the UI:
1. When initializing, prompt the user to accept or reject the hash. This is easy, but terrible UX because most people won't care/understand, and will probably just click "accept" instead of verifying the hash is valid.
2. Preconfigure the production builds to ship with a known recent block hash. This has good UX since the user doesn't have to think about it, but we will have to fall back to #1 if the block hash is more than 1 month old.
3. Have semi-trusted third parties (community members, companies, etc.) who sign block hashes, and let users configure which ones they want to trust (kind of like CAs). If any of them are on a fork, the user can be warned that a fork happened, and we can either pick one for them or let them choose. This is the best IMO, but is definitely most complex so this is a longer-term goal.

**Comment by faboweb** [comment]
I would go with 1) for now. I think 2) could confuse the user in the fallback case. I vote to aim for 3) in the long run. We should have a list of semi-trusted nodes (or validators?), ping all of them and take the hash with the super majority.

**Comment by faboweb** [comment]
As discussed with @mappum we will go with 2) which gives us the best UX while shipping builds fast (faster then once a month).
