### ISSUE TITLE
add loading graphic to initial "pinging node" modal

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1006]
<img width="631" alt="screen shot 2018-07-23 at 11 30 40 am" src="https://user-images.githubusercontent.com/6021933/43086648-ddd2dc34-8e6b-11e8-90d2-153ccf8791ec.png">

**Comment by jolesbi** [comment]
i'd also like to propose adding this somewhere on the session screen as to not interrupt the user flow. we can be "connecting" while still letting the user proceed (up until a certain point).

**Comment by faboweb** [comment]
Sadly its not that simple. Currently the key management is bundled with the LCD that needs to be restarted everytime we connect to a new node.
If the user is sining in while the LCD is down, he gets an error.
We can probably work around this somehow. I like your proposal @jolesbi

**Comment by jolesbi** [comment]
makes sense - let's discuss!

also, i noticed a potential bug. when running voyager locally, if you sign out, sometimes the node pinging will be happening in the background (visible in the console) but the modal is not displayed. I end up on the auth screen with network errors until voyager finds a node.

**Comment by jbibla** [comment]
- show session screen initially with persistent connected bar (design required)
- for sign up - disable submit button
- for sign in - show loading graphic for accounts
- for sign in with seed - show loading graphic
- for hardware - show loading graphic
