### ISSUE TITLE
Improve staking E2E tests by adding a second validator

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1019]
UI Version: 0.8.2

Description:

Currently the test only has one validator which wouldn't show problems that have to do with more then one validator being present.

**Comment by faboweb** [comment]
Plan:
- Start a 2nd node
- Declare it to be a validator
- Stake to 2nd node

**Comment by fedekunze** [comment]
how hard is to add a third one ? @faboweb

**Comment by faboweb** [comment]
If we have the 2nd one setup, I think it is easy.

**Comment by fedekunze** [comment]
I'd go for 3 then if it's just a copy/paste

**Comment by faboweb** [comment]
why? ^^

**Comment by faboweb** [comment]
Not as straight forward as I though:
- The 2nd validator needs to use different ports
- We need to add the 2nd validator pubkey to the genesis
- We need to declare our 1st node as a persistent_peer in the config.toml (unclear what ID is right now)
