### ISSUE TITLE
Voyager crashes on start

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1023]
UI Version: 0.8.2

Description:

Voyager crashes on start (`Voyager has encountered a critical error that blocks the app from running. Please create an issue and include a copy of the app logs.`).

This is in the Electron console:

```JavaScript
core.get-iterator.js?83c5:5

Uncaught (in promise) TypeError: null is not iterable!
    at module.exports.__webpack_require__.getIterator (webpack-internal:///1138:5:42)
    at Store._callee5$ (webpack-internal:///1175:402:61)
    at tryCatch (webpack-internal:///845:62:40)
    at Generator.invoke [as _invoke] (webpack-internal:///845:296:22)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///845:114:21)
    at step (webpack-internal:///14:17:30)
    at eval (webpack-internal:///14:28:13)
    at <anonymous>
```

also:

```
blockchain.js?027c:153

Tryed to subscribe to an already subscribed rpc event
```
| * | * | * | * |
| -- | -- | -- | -- |
  | error | @ | blockchain.js?027c:179
  | (anonymous) | @ | blockchain.js?027c:179
  | (anonymous) | @ | client.js?7aab:103
  | onceWrapper | @ | events.js:317
  | emitTwo | @ | events.js:126
  | emit | @ | events.js:214
  | (anonymous) | @ | client.js?7aab:75
  | emitOne | @ | events.js:116
  | emit | @ | events.js:211
  | addChunk | @ | _stream_readable.js?46dd:291
  | readableAddChunk | @ | _stream_readable.js?46dd:278
  | Readable.push | @ | _stream_readable.js?46dd:245
  | Duplexify._forward | @ | index.js?3e6e:170
  | onreadable | @ | index.js?3e6e:134
  | emitNone | @ | events.js:106
  | emit | @ | events.js:208
  | emitReadable_ | @ | _stream_readable.js?46dd:504
  | emitReadable | @ | _stream_readable.js?46dd:498
  | addChunk | @ | _stream_readable.js?46dd:298
  | readableAddChunk | @ | _stream_readable.js?46dd:278
  | Readable.push | @ | _stream_readable.js?46dd:245
  | Duplexify._forward | @ | index.js?3e6e:170
  | onreadable | @ | index.js?3e6e:134
  | emitNone | @ | events.js:106
  | emit | @ | events.js:208
  | emitReadable_ | @ | _stream_readable.js?46dd:504
  | emitReadable | @ | _stream_readable.js?46dd:498
  | addChunk | @ | _stream_readable.js?46dd:298
  | readableAddChunk | @ | _stream_readable.js?46dd:278
  | Readable.push | @ | _stream_readable.js?46dd:245
  | Transform.push | @ | _stream_transform.js?0f55:148
  | onmessage | @ | stream.js?b72e:119
  | onMessage | @ | WebSocket.js?3b39:442
  | emitTwo | @ | events.js:126
  | emit | @ | events.js:214
  | ontext | @ | WebSocket.js?3b39:841
  | (anonymous) | @ | Receiver.js?32a8:536
  | Receiver.applyExtensions | @ | Receiver.js?32a8:371
  | (anonymous) | @ | Receiver.js?32a8:508
  | Receiver.flush | @ | Receiver.js?32a8:347
  | finish | @ | Receiver.js?32a8:541
  | (anonymous) | @ | Receiver.js?32a8:499
  | Receiver.add | @ | Receiver.js?32a8:103
  | realHandler | @ | WebSocket.js?3b39:825
  | emitOne | @ | events.js:116
  | emit | @ | events.js:211
  | addChunk | @ | _stream_readable.js:263
  | readableAddChunk | @ | _stream_readable.js:250
  | Readable.push | @ | _stream_readable.js:208
  | onread | @ | net.js:594

This is in the terminal:

```shell
electron  spawning /Users/david/Documents/AllInBits/voyager/builds/gaia/darwin_amd64/gaiacli with args ""advanced" "rest-server" "--laddr" "tcp://localhost:9070" "--home" "/Users/david/.cosmos-voyager-dev/gaia-7002/lcd" "--node" "172.104.136.83:26657" "--chain-id" "gaia-7002""

electron  gaiacli: I[07-26|19:24:56.941] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:64406

electron  gaia rest server ready

electron  Signaling connected node

electron  gaiacli: I[07-26|19:24:56.947] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:64373

electron  gaiacli: panic: resource temporarily unavailable
          
          goroutine 1 [running]:
          github.com/cosmos/cosmos-sdk/client/lcd.createHandler(0xc4208e2380, 0x5, 0x7ffeefbfdc97)
          	/go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:78 +0x612
          github.com/cosmos/cosmos-sdk/client/lcd.ServeCommand.func1(0xc4208fab40, 0xc420493000, 0x0, 0x8, 0x0, 0x0)

electron  gaiacli: 	/go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:40 +0x8e
          github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc4208fab40, 0xc420492f00, 0x8, 0x8, 0xc4208fab40, 0xc420492f00)
          	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:698 +0x46d
          github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x209a520, 0x19ec3fa, 0x24, 0xc4208f0778)
          	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
          github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0x209a520, 0xc42090e100, 0x209a600)
          	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:736 +0x2b
          github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x209a520, 0x1b35b00, 0x2, 0xc4208dc8a0)
          	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
          main.main()
          	/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/cmd/gaiacli/main.go:146 +0xb88

electron  gaiacli exited with code 2

electron  The gaiacli rest-server (LCD) exited unplanned
```

**Comment by NodeGuy** [comment]
Ah, I see this is initiated by polling code:

```JavaScript
    // poll until LCD is started
    let client = new LcdClient(`http://localhost:${LCD_PORT}`)
    while (true) {
      try {
        await client.listKeys()
        break // request succeeded
      } catch (err) {
        await sleep(1000)
      }
    }
```

Probably that's not what's causing the crash then.

**Comment by faboweb** [comment]
Two different errors.
First one: The genesis accounts can have `coins: null` which is not iterable... I will create PR in a sec
2nd one: Apparently the gaiacli doesn't shut down properly sometimes making Voyager break on reconnection.

**Comment by jbibla** [comment]
referenced in #1040 — didn't happen on start — but seems to be a duplicate.
