### ISSUE TITLE
What should we track?

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1032]
UI Version: 0.8.2

Description:

What events should we track in google analytics?

Remove opt-in in favor of opt-out.

**Comment by faboweb** [comment]
We could track all the actions:
- login
- logout
- send coins
- stake/unbond/redelegate
- search?

**Comment by faboweb** [comment]
Prime use case: delegating

**Comment by nylira** [comment]
Let's also track receiving coins. Without steak the user can't do anything on the testnet. Let's see what percentage of users manage to get coins from the faucet.

**Comment by jbibla** [comment]
to clarify, we want to add google analytics events for key actions (listed above) and also switch the default to "being tracked" with an option to opt-out for users that are signed in.

@faboweb

**Comment by faboweb** [comment]
In theory just finalize the list of actions (without implementing them).
Implementing them could be another issue.
Removing the opt-out could also be a another issue.

**Comment by jbibla** [comment]
ok!

general app events:
- all session events (sign in, sign out, sign up)
- action modal opens (for each modal)
- use of help icon in toolbar

primary actions:
- sends
- delegations
- undelegations
- redelegations
- proposal creations
- deposits
- votes

the following tickets should be done to complete this epic:
- tag voyager tx's #1630
- switch from opt-in to opt-out https://github.com/cosmos/voyager/issues/1887
- google events https://github.com/cosmos/voyager/issues/1888 
- ensure sentry works on the web https://github.com/cosmos/voyager/issues/1625
