### ISSUE TITLE
Node approval process design

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1036]
if a user doesn't open voyager for more than 3 weeks voyager will not be able to safely determine what the validator set is - and therefore will not be able to trust any data.

so we'll need to track time for our users - so we can notify them when it has been 3 weeks and we'll need to provide a mechanism for verifying the real validator set (maybe by verifying a hash of the current set).

this is an interesting and unique design / technical problem.

maybe @mappum has some insights here.

**Comment by faboweb** [comment]
We actually have a modal to approve a validator hash implemented.

Is it really 3 weeks? This sounds strange in a blockchain context. Maybe block height? Or just the diff of the validators is > 1/3?

**Comment by jbibla** [comment]
> We actually have a modal to approve a validator hash implemented.

😍 — i'd still like to discuss how we can help users get this hash.

> Is it really 3 weeks?

apparently, yes. i'm sure we can translate this to block height.

> the diff of the validators is > 1/3

this is also something to consider i think!

**Comment by jbibla** [comment]
as discussed in the ui / ux call

- the time period is however long the unbonding period is (30 days / 3 weeks)
- introduce "trust status" - LCD will check 100 nodes (every startup / every week) to see if more than 2/3 of full nodes agree on the validator set hash
- no need to notify with modal unless more than 1/3 disagree
- will help build trust with user and provide important assurances from a security perspective

- ui designs to come 🎨

**Comment by faboweb** [comment]
Link #55 #1222

**Comment by NodeGuy** [comment]
Can we close this now that we're always connecting to the same node?

**Comment by jbibla** [comment]
i think so

**Comment by faboweb** [comment]
ok, we can reopen the topic when we have more dynamic nodes.
