### ISSUE TITLE
Unexpected erorr messages: "Atoms must be between 0 and -1148250"

### ISSUE THREAD

**Issue by zmanian** [cosmos/voyager#1041]
This message makes no sense and I can't click submit
![screenshot from 2018-07-28 20-09-00](https://user-images.githubusercontent.com/93434/43362564-3ee6ffe8-92a2-11e8-87f4-6928eb2d5a32.png)

**Comment by zmanian** [comment]
The messages go away if I edit every field

**Comment by faboweb** [comment]
Thank you for the bug report.
This probably has to do with steak being fractions. We will quickly follow up.

**Comment by faboweb** [comment]
This should be resolved by #1048

**Comment by okwme** [comment]
closed due to resolution noted by @faboweb
