### ISSUE TITLE
Validators with non-whole fractions of steaks showing incorrectly in staking window

### ISSUE THREAD

**Issue by KamuelBob** [cosmos/voyager#1042]
UI Version: 0.9.1 Windows

Description:

Validators with non-whole fractions of steaks are showing the incorrect amount in the Staking window of Voyager.

![image](https://user-images.githubusercontent.com/38965739/43363825-aa113b86-9350-11e8-800f-540dd1d2690c.png)

Querying the above two validators in the Explorer shows that they should have 135.9 and 126.9 steaks respectively.

![image](https://user-images.githubusercontent.com/38965739/43363862-6f85fb04-9351-11e8-96d0-aaffd1dcfc2c.png)

![image](https://user-images.githubusercontent.com/38965739/43363868-91712892-9351-11e8-87a7-1ab01a4fd932.png)

While this looks like the decimal place is not being handled correctly, another validator (#kingnet.com) is showing as 432 steak when according to the Explorer they have 86.4 (out by factor of 5 instead of 10).

The percent of vote is being calculated off the incorrect Total Votes, so I'm guessing this will be resolved once the votes is fixed.

Feel free to open Voyager v0.9.1 Windows on live testnet (gaia-7003) to view the same results.

**Comment by KamuelBob** [comment]
Only had a quick chance to have a look, but appears to be the way it is expecting only integers somewhere here:
https://github.com/cosmos/voyager/blob/develop/app/src/renderer/components/staking/PageStaking.vue#L72

**Comment by faboweb** [comment]
Awesome bug report. We will follow up quickly.
