### ISSUE TITLE
Content not showing

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1043]
UI Version: 0.9.1

Description: 

1. wallet page disappears
2. block explorer won't display individual block pages
3. version numbers are not being displayed

<img width="1440" alt="screen shot 2018-07-29 at 8 15 46 am" src="https://user-images.githubusercontent.com/6021933/43366520-4435a5f6-930d-11e8-9a31-e0c7942c1c02.png">

<img width="1440" alt="screen shot 2018-07-29 at 8 15 57 am" src="https://user-images.githubusercontent.com/6021933/43366529-63f55d32-930d-11e8-9806-05edf8c67377.png">

<img width="1440" alt="screen shot 2018-07-29 at 8 18 07 am" src="https://user-images.githubusercontent.com/6021933/43366533-684fb1de-930d-11e8-8599-06918c405086.png">

**Comment by jbibla** [comment]
<img width="1440" alt="screen shot 2018-07-29 at 9 03 27 am" src="https://user-images.githubusercontent.com/6021933/43366606-ab53f232-930e-11e8-8007-e88c5d404bdc.png">

**Comment by nylira** [comment]
I cannot recreate the wallet page error on `gaia-7005` while synced to a live node. The other errors still exist though.

**Comment by jbibla** [comment]
- [ ] wallet page disappears (can't reproduce)
- [ ] block explorer won't display individual block pages (#1089)
- [ ] version numbers are not being displayed (#1043)

**Comment by fedekunze** [comment]
The Internal Error could be because of [cosmos-sdk/2007](https://github.com/cosmos/cosmos-sdk/issues/2007)
