### ISSUE TITLE
Wallet Staking - Slider UI Bug

### ISSUE THREAD

**Issue by steaksquad** [cosmos/voyager#1045]
UI Version: 0.9.1

Description: Slider interface bug

- In wallet, under Staking tab
- Select more than 1 validator 
- When trying to Bond 'Steak' after hitting next, there's a graphic slider bug when you slide any slider besides the first selected. 
- Not only Grayed out, but no change to input field

<img width="1008" alt="screen shot 2018-07-30 at 4 06 06 am" src="https://user-images.githubusercontent.com/41894036/43385934-1acddcda-93b0-11e8-8bc6-464730a8d25a.png">

I believe the problem is only the slider UI because making 'Steak' bond allocation through mouse clicks on the arrows to increase or decrease count OR simply input field seems to be perfectly fine. Problems start when trying to use the slider. 

<img width="1160" alt="screen shot 2018-07-30 at 4 18 39 am" src="https://user-images.githubusercontent.com/41894036/43385951-26493014-93b0-11e8-90d3-6d2938113d13.png">

**Comment by faboweb** [comment]
Thank you for the report. We will try to fix this quickly.
