### ISSUE TITLE
Use `gaiaversion.txt`

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1046]
UI Version: 0.9.1

Description:

Testnet configuration folders should now contain a `gaiaversion.txt` which holds the SDK version used for that network. This could be parsed to build Voyager for a certain network.

**Comment by NodeGuy** [comment]
Done in https://github.com/cosmos/voyager/pull/1060/commits/da118b6fe2d1d305ea0995136b577eb098f8caae.

**Comment by faboweb** [comment]
Can we also use the `gaiaversion.txt` to deprecate `COMMIT.sh`?

**Comment by NodeGuy** [comment]
Interesting idea.

If we don't use the hash then we have to trust GitHub.

Are you suggesting that the build process look at the network requested, see whether it has a version of Gaia built for it, and if it doesn't then delete the current version of Gaia and rebuild it?
