### ISSUE TITLE
implement "My Stake" page

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1054]
New design 

<img width="810" alt="screen shot 2018-09-03 at 4 07 44 pm" src="https://user-images.githubusercontent.com/31522760/44991169-92a2db80-af93-11e8-9730-0bbb22c1cf1c.png">

https://zpl.io/aBNdBxK

**Comment by okwme** [comment]
https://sketch.cloud/s/xKnxA/all/voyager-ui/

**Comment by okwme** [comment]
- [ ] make new component in `components/staking` to be shown within `PageStaking.vue`
- [ ] filter validators by those you are actively staked to, and those you are unbonding from
- [ ] make a component for Active Validators with bonded amount and rewards amount
- [ ] make a component for Unbonding Validators with unbonding amount and time left
- [ ] bonus: make tab filters
