### ISSUE TITLE
PageBlock not displaying / errors! errors!

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1057]
<img width="1043" alt="screen shot 2018-07-31 at 8 52 04 pm" src="https://user-images.githubusercontent.com/6021933/43494998-9ea5c7a8-9503-11e8-9b28-2d7c7a27d745.png">

**Comment by nylira** [comment]
I cannot recreate this on `gaia-7005`. 0.9.3 works with this

**Comment by jbibla** [comment]
i am on 0.9.3 on gaia-7005 - this is still an issue for me.

**Comment by faboweb** [comment]
We removed the block explorer for now.
