### ISSUE TITLE
User Report: Bugs and Feature Requests

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/voyager#1061]
UI Version: 0.8.2 for Local Testnode and Demo Network. 0.9.2 for Public Testnet

**General Usability**:

Upon startup, background was dark blue with small black text which made it very hard to read. Starting theme was blank in Settings, had to switch to dark/light theme to get readability.

Switching from demo network to local testnode caused some of the validators in demo network to show up in staking for local testnode. Should be clearer isolation between networks

After creating an account and signing out, Voyager only gave me option to sign into that one account. Should be easy to create and manage multiple accounts from single Voyager application.

**Transactions**

1. Transactions don’t show up in tx history in Local Testnode or on Public Testnet.
2. On demo network it shows up, however when I click on transaction I want to see more details about it. E.g. which block and index was it committed in, how much fees were paid, etc.

**Blocks**

1. Can't query blocks on Local Testnode or Public Testnet.
2. Clicking on a block caused “Internal Error”. The transaction count seems to increment correctly, but I can't click on block to see more details
    - Feature Request: Clicking on block shows number of transactions, proposer, number of precommits, any validator changes.

**Staking**

1. Worked well on Public Testnet. However, could completely break on demo network. Changing more than one validator at a time caused unexpected errors. Percents of stake became NaN%. "Atoms must be between 0 and -984".
2. Staking sliders should be more smooth, generally found it much easier to input numbers directly rather than drag slider.
3. Staking success messages could be more useful. Rather than "bonding/unbonding successful". Would be cool to see "Bonding N steak to Validator X was successful" as example of more specific message.
4. Feature Request: Don't know if this already exists, but would like to get notification if one of the validators i delegate to gets slashed so that I can unbond rest of my steak.

**Voting**
- Vote doesn’t get committed as a transaction in blockchain when running Local testnode, not sure if this same happened with Public testnet.
- Hard to know what the colors in pie graph mean. Legend or color map would be useful
- Voyager doesn’t save what your current vote is (or fact that you voted at all)
   - If I click Yes on Vote for a proposal, I should navigate out and navigate back and still see that I voted Yes. Instead it shows Abstain as default choice when I come back to vote even after I voted
- There is no easy way for Voyager to display current vote tally correctly, so I suggest not displaying any results at all until after a proposal has completed voting period.
- Would like to have page to see results of completed votes that I participated in, didn't test whether this feature existed but it would be nice to have if it isn't already there.

**Comment by faboweb** [comment]
Hey @AdityaSripal,
How have you imagined receiving the notification for
> would like to get notification if one of the validators i delegate to gets slashed

**Comment by jbibla** [comment]
figment sends an email which is pretty nice. i get a daily update from them about my validator 🥇 

but, we have discussed a notifications page in the past for events like this. not sure if it's possible without a centralized database.

**Comment by faboweb** [comment]
I put "Voyager centralized server" as a milestone to discuss for the next meeting.

**Comment by AdityaSripal** [comment]
Yea, emails or texts would be great. I think if we could do that then most Voyager delegators will never worry about getting slashed for liveness. 

If my validator is getting close to being slashed, then I get notified on my phone (email or text), get on Voyager and redelegate to someone else.

If this requires a centralized server I think that's fine so long as users can opt in to having any interaction with this centralized server
