### ISSUE TITLE
Staked balance doesn't update after staking

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1065]
UI Version: 0.9.3

Description:

Staked balance on the PageWallet doesn't update after staking

**Comment by NodeGuy** [comment]
When I tried staking I noticed the the "Staked Balances" did update but the "Available Balances" did not.  Is this what you're experiencing?

**Comment by faboweb** [comment]
I can't test this on develop right now because of being unable to stake at all :/

**Comment by faboweb** [comment]
Available balance doesn't update automatically
Staked balance doesn't update at all (after pressing refresh)
Tested on local node.
