### ISSUE TITLE
Version information not showing

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1069]
UI Version: 0.9.3

Description:

SDK and Voyager version are not shown in modal.

<img width="324" alt="screen shot 2018-08-02 at 1 30 28 pm" src="https://user-images.githubusercontent.com/31522760/43585670-fb7a19f8-9665-11e8-8ce9-1d17b720a84c.png">

**Comment by nylira** [comment]
Mentioned by #1044

**Comment by faboweb** [comment]
@nylira I just want to be safe, but I don't see a mention of it in #1044

**Comment by jbibla** [comment]
i think he meant https://github.com/cosmos/voyager/issues/1043
