### ISSUE TITLE
Prevent sending to own address

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1070]
UI Version: 0.9.3

Description:

Voyager allows you to transfer to your own account (successfully). Balance stays the same which is good, but we should check if the address of the destination is the same as the sender in the UI.

<img width="1471" alt="screen shot 2018-08-02 at 1 32 36 pm" src="https://user-images.githubusercontent.com/31522760/43585850-6585264e-9666-11e8-8374-a30da5eb0fdb.png">

**Comment by faboweb** [comment]
This is not a bug, it is a feature and very good for testing tx history ;D
