### ISSUE TITLE
Add min and max values to input number

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1072]
UI Version: 0.9.3

Description:

Input type number should have:
min: 0 
max: User balance

I'd keep the error message just in case.

<img width="1466" alt="screen shot 2018-08-02 at 1 31 49 pm" src="https://user-images.githubusercontent.com/31522760/43586195-4357704e-9667-11e8-839f-2304e77020a3.png">

**Comment by faboweb** [comment]
👍

**Comment by okwme** [comment]
blocked by https://github.com/tendermint/ui/issues/44
