### ISSUE TITLE
Bond Bar out of margin

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1073]
UI Version: 0.9.3

Description:

Disable or hide bond bar if the user is revoked.
See picture below.

<img width="1474" alt="screen shot 2018-08-02 at 1 26 22 pm" src="https://user-images.githubusercontent.com/31522760/43586292-87d70f90-9667-11e8-87f2-78514c6a2961.png">

**Comment by faboweb** [comment]
Damn, still a bug with the stupid bar! 😆

**Comment by nylira** [comment]
Solution: disable bond bar manipulation. Remove the scrubber disk. Solves a whole class of bugs.
