### ISSUE TITLE
link to the testnet faucet on wallet page

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#1079]
UI Version: 0.9.3

Description: When I download Voyager 0.9.3 and create an account, it's unclear what the next step is. There's no link to the steak faucet. I have a feeling that if I'm running into this problem, most users have the same issue.

Proposal: If users do not have steak in their faucet, link to the testnet faucet on the Wallet page.

**Comment by faboweb** [comment]
This is already the case:
![image](https://user-images.githubusercontent.com/5869273/43724013-57a52c6e-9999-11e8-869b-268ae6ed992b.png)
