### ISSUE TITLE
Error fetching validator set

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1080]
UI Version: 0.9.3

Description:

Before I sign in, the error message "Error fetching validator set: Internal error" is displayed.

<img width="899" alt="screen shot 2018-08-06 at 12 14 06 pm" src="https://user-images.githubusercontent.com/2148537/43728237-6feaa1f4-9972-11e8-8923-2b7a05b61758.png">

I don't see anything significant in either console.

**Comment by jbibla** [comment]
it's odd that we are making requests before the user is signed in

**Comment by nylira** [comment]
Can we turn session modals into pages in `vue-router` instead of a z-index overlay on top of the wallet?

**Comment by faboweb** [comment]
@nylira can you create an issue recommending this change?

**Comment by faboweb** [comment]
I think this is a strange typo issue `/stake/validators/` vs `/stake/validators` and I experienced it as well in #1068 . It will hopefully be resolved after this is merged.

**Comment by faboweb** [comment]
Assumed fixed

**Comment by faboweb** [comment]
Still an issue

**Comment by NodeGuy** [comment]
What's blocking it?

**Comment by faboweb** [comment]
the blocking label was still on there

**Comment by NodeGuy** [comment]
I can't reproduce it.  @faboweb are you able to reproduce it consistently?

**Comment by NodeGuy** [comment]
So what's the desired behavior?  Should `getValidators` be called only when connected to a node or should we suppress the error message?

**Comment by faboweb** [comment]
Both seem to be valid options. Maybe we need to defer REST calls a little bit, so we are sure the connected node is working and we wont reconnect. This would solve the root cause.

**Comment by faboweb** [comment]
I handle the case "skipping it" in #1216

**Comment by fedekunze** [comment]
Created #1313 to turn the session modals to pages

**Comment by faboweb** [comment]
The rpc subscription starts before the REST client is up. The headers come in and trigger a load of the validators before the the REST server is up. This creates this issue.

Current patch: Do not load data before the user is not signed in (which should be after the REST server is up).
