### ISSUE TITLE
Update Jest

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1084]
UI Version: 0.9.3

Description:

Updated my dependencies on `package.json` and by upgrading `jest` from `21.2.1` to `23.4.2` all my test broke and threw the same error: 

```
  ● Test suite failed to run

    TypeError: jest.genMockFunction is not a function

       7 | global._Date = Date
       8 | global.Date = jest.fn(() => new global._Date(DATE_TO_USE.toISOString()))
    >  9 | Date.now = jest.genMockFunction().mockReturnValue(DATE_TO_USE.getTime())
```

Had to downgrade to de prev version to solve the issue, but in the long run we might have to change how we mock dates using `jest`.

See the following issue:

- https://github.com/facebook/jest/pull/6173

**Comment by NodeGuy** [comment]
A better choice is to stop using mocks in accordance with my talk.

**Comment by faboweb** [comment]
Spiked this:
- not straight forward
- will need some investigation to solve strange bugs

Don't underestimate this.
