### ISSUE TITLE
remove Axios & xmlhttprequest libraries

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1086]
Let's remove the `axios` and `xmlhttprequest` libraries.

* Node's [http.request](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_http_request_options_callback) works just as well and doesn't require a separate library.
* `xmlhttprequest` is buggy.
* `xmlhttprequest` is unmaintained.
* Extra libraries increase our attack surface.

**Comment by faboweb** [comment]
axios has the benefit of working in the browser and node. and it has 46k stars on GitHub, almost as many as node itself. I would guess it is well maintained. But let's discuss this with the team.

`xmlhttprequest` is actually not needed anymore in the tests. nice find. Removing it here: https://github.com/cosmos/voyager/pull/1098
