### ISSUE TITLE
MVP feature cut: remove the block explorer

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#1090]
UI Version: 0.9.3

Description: As discussed in #ui-team, let's remove the block explorer and link to users to https://explorecosmos.network instead. This reduces the scope of Voyager, which is a boon for development. **As a bonus, we can close a bunch of issues!**

- [x] remove block explorer
- [ ] remove block explorer npm dependencies
- [x] block details should link to Cosmos Explorer
- [ ] transaction details should link to Cosmos Explorer

Closes #1089 
Closes #945 
Closes #381

**Comment by jbibla** [comment]
> remove block explorer npm dependencies

didn't see any

> transaction details should link to Cosmos Explorer

this should be covered in tendermint/ui i think
