### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by beichenh** [cosmos/voyager#1095]
This is a feature request instead of bug report. 

Currently Cosmos UI Voyager supports cross-platform desktops. However, a lot of users are using mobile devices to manage their wallets and perform transactions. Is there a plan to develop a mobile version e.g. using Ionic or Reactive Native in the near future? The current Electron framework doesn't seem to be extensible for mobile support.

Please consider.

**Comment by faboweb** [comment]
We are not aiming for mobile support in the near future. There are plans to do so post-launch. Stay tuned. :)
