### ISSUE TITLE
Your Votes not sorting

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#1096]
UI Version: 0.9.3
Description: on staking page your votes doesn't sort

**Comment by nylira** [comment]
I encountered this error.

<img width="1023" alt="screen shot 2018-08-09 at 12 13 53 pm" src="https://user-images.githubusercontent.com/172531/43877680-d77bc5fc-9bcd-11e8-9508-4352b6b11eb6.png">
<img width="1023" alt="screen shot 2018-08-09 at 12 14 00 pm" src="https://user-images.githubusercontent.com/172531/43877682-da5da416-9bcd-11e8-8122-7390b5e146ea.png">

**Comment by okwme** [comment]
sorry for merging this already i didn't see your comment @nylira 
I'm unable to reproduce the bug though, I see you've got 40 staked to Nylira Validator
That's where mine is staked too, do you have multiple stakes?
can you still reproduce the error? if so could you tell me more info that would help in reproducing or debugging in general? maybe we can open a new issue if so?
