### ISSUE TITLE
super laggy / unresponsive

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#1102]
UI Version: 0.9.3
Description: maybe it's my old computer on these hot days but i'm getting very poor performance from voyager. Pages freeze all the time, clickable things never turn to the click cursor and the click itself hangs for ages before anything occurs

**Comment by jbibla** [comment]
i noticed this yesterday as well on my new macbook pro in a highly air conditioned room.

**Comment by faboweb** [comment]
maybe has to do with caching, which also encrypts the value, on every store update

**Comment by fedekunze** [comment]
Closed by #1121
