### ISSUE TITLE
Make staking terminology consistent.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1104]
UI Version: 0.9.3

Description:

We use both "staking" and "delegation" to refer to the same thing.  It's a new concept to most people so it would be better if we introduce only a single new term for it instead of two.

**Comment by jbibla** [comment]
absolutely agree. we should go with staking because of its natural association with proof of stake.

**Comment by faboweb** [comment]
Investigate with the SDK team

**Comment by NodeGuy** [comment]
Let's do this in Staking 2.0.

**Comment by faboweb** [comment]
May be low amount of work with high value (expected 1h meeting with a decision, 1h implementation). But I don't feel strongly about this.

**Comment by jbibla** [comment]
apparently we are "Bonding POS" now... we can't move forward with this until we are certain.

**Comment by NodeGuy** [comment]
Duplicate of #1283.
