### ISSUE TITLE
"You do not have any ATOMs to delegate." confusing while using STEAK

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1105]
UI Version: 0.9.3

Description:

I've been staking with STEAK but just got the error message, "You do not have any ATOMs to delegate."  The terminology is confusing.

**Comment by jbibla** [comment]
yes, we should use a config variable for the native currency so it will be ...

1. less confusing for testnet users
2. easy to update for mainnet
3. FuN 🎉

**Comment by faboweb** [comment]
Use config staking denom
