### ISSUE TITLE
available balance shows in small font for a few seconds

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1108]
UI Version: 0.9.3

Description:

<img width="806" alt="screen shot 2018-08-08 at 1 42 28 pm" src="https://user-images.githubusercontent.com/2148537/43854488-023c0f58-9b11-11e8-9f1f-3d92b98dfac7.png">

To reproduce this I log out and I log in again.  The font is small for a few seconds and then fixes itself.

**Comment by jbibla** [comment]
i don't know if it is required to discuss this

**Comment by NodeGuy** [comment]
We're currently using the `discuss` label to assign issues.  Maybe we should discuss that.

**Comment by jbibla** [comment]
ah. we don't need to use a label to assign issues.

> Maybe we should discuss that.

oh god.
![giphy](https://user-images.githubusercontent.com/6021933/43926807-63b705d8-9bf9-11e8-8fea-2d5ed8334225.gif)

**Comment by okwme** [comment]
waiting for confirmation from @NodeGuy this error still occurs

**Comment by jbibla** [comment]
i think we should remove the animations. this is not even the right animation if it did work reliably.

**Comment by NodeGuy** [comment]
It's now so fast that I don't notice it unless I look very carefully, in which case it looks like buggy jank.  Let's remove the animation.

![aug-16-2018 17-14-42](https://user-images.githubusercontent.com/2148537/44235603-1a0ce400-a178-11e8-8397-955fc7e6a3d0.gif)

**Comment by faboweb** [comment]
Summing up: The agreement is to remove the animation.
