### ISSUE TITLE
Signing out should take me to the "Sign in to Cosmos Voyager" page.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1109]
UI Version: 0.9.3

Description:

I signed out to create a new account but was taken to the "Sign In" page which doesn't give me that option.  I would expect instead to be taken to the "Sign in to Cosmos Voyager" page which gives me the option to create a new account as well.

**Comment by jbibla** [comment]
do you mean that signing out should take you back to the original session modal instead of the sign in modal?

**Comment by faboweb** [comment]
I support David there

**Comment by NodeGuy** [comment]
> do you mean that signing out should take you back to the original session modal instead of the sign in modal?

Yes.

**Comment by faboweb** [comment]
This is now the case. #1137 resets the value if signed out.
