### ISSUE TITLE
Brand-new account shows staked balance.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1110]
UI Version: 0.9.3

Description:

<img width="809" alt="screen shot 2018-08-08 at 1 46 46 pm" src="https://user-images.githubusercontent.com/2148537/43854640-84a9e640-9b11-11e8-961b-7738500c5618.png">

I created a brand-new account and the wallet is showing that it already has 130 STEAK staked.

**Comment by jbibla** [comment]
what do you mean by "brand-new"?

**Comment by faboweb** [comment]
probabaly has to do with #1112
