### ISSUE TITLE
Don't run tests when pushing to release

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1114]
UI Version: 0.9.3

Description:

Pushing to `release` runs a job on CircleCI that creates a pull request release candidate.  The tests are run twice (once on `release` and a second time on the pull request).  Let's skip the tests on `release`.

**Comment by jbibla** [comment]
i think we're abusing the discuss label - which in my mind is a label for things we are going to discuss in our zoom calls.
