### ISSUE TITLE
Progress buttons

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1118]
UI Version: 0.9.4

Description:

We could show a progress bar on the submit button, based on an estimated block time (last blocks).

Example:
![image](https://user-images.githubusercontent.com/5869273/43948512-4b3ac7be-9c8b-11e8-9582-4353c13a1787.png)

**Comment by faboweb** [comment]
Pulling in @nylira

**Comment by nylira** [comment]
Like I mentioned on #1092, I would support having a async loading bar for sending, staking, and voting transactions. It would be nice if the user can still use the app while the block is being finalized.

A progress bar on the submission button still makes the user wait to see if the tx made it through. I think they'd be worried that they can't leave the page before the progress bar completes.

**Comment by faboweb** [comment]
wait for decisions on #1092

**Comment by jbibla** [comment]
instead of blocking the user from proceeding with more submissions / transactions ...

1. show successful submission
2. clear for new tx's
3. show loading icon in sidebar next to transactions link
4. include the pending / loading tx in tx history

**Comment by faboweb** [comment]
so this is more the optimistic UI approach. I trust u on that. closing this issue.
