### ISSUE TITLE
my delegations not showing up

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#1123]
UI Version: 0.X.X

Description: don't see my delegations to Nylira anymore

**Comment by okwme** [comment]
ok it does show up after the call to: `/stake/delegators/cosmosaccaddr18tkxwzhyn4a5ss63vttwpespvm7kxm895m9ppf` but takes 44.85 seconds ⏳

**Comment by fedekunze** [comment]
what about `/stake/delegators/cosmosaccaddr18tkxwzhyn4a5ss63vttwpespvm7kxm895m9ppf/delegations/<NyliraAddr>` ?

**Comment by okwme** [comment]
moved to #1133
