### ISSUE TITLE
finish staking UI

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1132]
- [x] my stake - https://zpl.io/aBNdBxK
- [x] validators index - https://zpl.io/VQEdB6k
- [ ] ~validator profile~ https://github.com/cosmos/voyager/issues/1171
- [x] delegation form - https://zpl.io/aBNp8nA
- [x] redelegation form - https://zpl.io/VxlvdWk

**Comment by fedekunze** [comment]
@nylira @jbibla I now you have showed them already, but can you post the links to the design files here as well ? Thanks !

**Comment by NodeGuy** [comment]
@jbibla Fede requested the design files 11 days ago.  Would you please post them here?

**Comment by jbibla** [comment]
@NodeGuy the link was provided 10 days ago.

<img width="789" alt="screen shot 2018-08-31 at 7 34 05 am" src="https://user-images.githubusercontent.com/6021933/44910208-53a12b80-acf0-11e8-95f4-31eb5516b7a5.png">

**Comment by NodeGuy** [comment]
I see a link to "my stake".  What about "validators index", "delegation form", and "redelegation form"?

**Comment by faboweb** [comment]
validator index: https://sketch.cloud/s/xKnxA/all/voyager-ui/staking-validators-ui
delegation form: https://sketch.cloud/s/xKnxA/all/voyager-ui/staking-delegation
redelegation form: https://sketch.cloud/s/xKnxA/all/voyager-ui/staking-redelegation
