### ISSUE TITLE
Improve performance of /stake/delegators/{delegatorAddr}

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1133]
UI Version: 0.9.4

Description:

This request takes 45s!

**Comment by NodeGuy** [comment]
I presume you mean `/stake/delegators/{delegatorAddr}`?

**Comment by faboweb** [comment]
Yes :)

**Comment by NodeGuy** [comment]
Blocked by https://github.com/cosmos/voyager/issues/1141.

**Comment by faboweb** [comment]
Why was this removed from the sprint without clarification?

**Comment by fedekunze** [comment]
@faboweb I'm still working on that. @NodeGuy is blocked on the Pact tests only. Will finish this before the end of the sprint

**Comment by NodeGuy** [comment]
I thought that's what you said you wanted during our call last week—I split the issue into a smaller scope and threw the remainder back into the backlog.

**Comment by fedekunze** [comment]
Heads up, I'm implementing Sunny's `Queriers` for this cosmos/cosmos-sdk#1918

**Comment by NodeGuy** [comment]
See https://github.com/cosmos/voyager/issues/1193 about creating a test for this endpoint.

**Comment by faboweb** [comment]
Blocked by a decision of the SDK team on how to handle this.

**Comment by fedekunze** [comment]
Closed by cosmos/cosmos-sdk#2249
