### ISSUE TITLE
Make sure all data is cleared on switching networks

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1135]
UI Version: 0.9.4

Description:

All data like candidates or balances or txs or anything should be reverted to the empty state on switching a network.

Could be done on signing out.

**Comment by jbibla** [comment]
> Could be done on signing out.

doesn't this defeat the purpose of caching in the first place?

@fedekunze @faboweb

**Comment by faboweb** [comment]
This clears the data of one user when he signs out, so that the data is not visible to another user logging in.
