### ISSUE TITLE
"about" menu doesn't display unless logged in

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1138]
i think we should use the native electron menu.

https://electronjs.org/docs/api/menu

**Comment by faboweb** [comment]
This didn't worked properly on Windows/Linux. Maybe this was a bug and we can test this again.

**Comment by jbibla** [comment]
i thought i remembered something about this. i would be surprised if electron hadn't solved this.

**Comment by faboweb** [comment]
easy fix might be to set z-index on the menu higher then the session menu

**Comment by jbibla** [comment]
yeah, but i think ideally it would be done the electron native way

**Comment by faboweb** [comment]
Plan:
Easy fix: Increase the z-index of the about menu to show even when the sign in overlay is showing.
Sophisticated fix: Use the electron native menu for this (https://github.com/cosmos/voyager/issues/1201)

**Comment by faboweb** [comment]
Update:
While the login screen is displaying, no other component is rendered. So the about menu is not rendered as well. So I think we need to do #1201

**Comment by faboweb** [comment]
Closed in favor of #1201
