### ISSUE TITLE
Create Pact test for /stake/delegators/{delegatorAddr}.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1141]
Create a test for the endpoint /stake/delegators/{delegatorAddr} on both the Voyager and SDK sides.  Test for both undelegations and redelegations.

This work supports https://github.com/cosmos/voyager/issues/1133.

**Comment by NodeGuy** [comment]
I'm giving up trying to do this myself—writing good tests in the SDK is too painful.  I've added this to the agenda to discuss options.

**Comment by faboweb** [comment]
On what is this blocked? If this is blocked, let's skip the pact tests and use the existing test structure for #1133

**Comment by NodeGuy** [comment]
I can't write a good test without the help of the SDK team.  It has nothing to do with Pact.  I'm pair programming with Alessio to get help tomorrow.

**Comment by NodeGuy** [comment]
Closing in favor of https://github.com/cosmos/voyager/issues/1193 and https://github.com/cosmos/voyager/issues/1194.
