### ISSUE TITLE
Voyager showing incorrect stake balances

### ISSUE THREAD

**Issue by kjaiswal** [cosmos/voyager#1153]
UI Version: 0.9.4

Description:

Steps to reproduce - 

1. Downloaded new version Voyager and received 20 STEAK at cosmosaccaddr1990ceh7wh50j2z6wq08ekzez7yr6hpwtpap9ku

2. First issue, I see "Connecting to network..." intermittently. After delegating 18 STEAK, I see abnormally high number of my delgated STEAK number in "Staking" tab (see screenshot attached)

3. Couldn't query block error also seen.

Recommendations - 

1. In menu item "About Cosmos Voyager", please show version numbers for wallet and SDK, these are missing right now.

2. I remember, a fix was made to not produce blocks with empty transactions, but I still see these being produced in Voyager.

3. 
![cosmos_voyager_bug_1](https://user-images.githubusercontent.com/2622360/44310552-39308f00-a38d-11e8-8053-0a9665995dcd.png)

**Comment by kjaiswal** [comment]
The balance made its way to network, see network explorer screenshot.
![cosmos_voyager_bug_2](https://user-images.githubusercontent.com/2622360/44310594-fd49f980-a38d-11e8-9d0e-2b46dbb76c84.png)

**Comment by faboweb** [comment]
should be fixed with #1148 @fedekunze could you clarify?

**Comment by fedekunze** [comment]
@faboweb @kjaiswal solved in #1148
