### ISSUE TITLE
new UI For validator profile

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1171]
- [x] Design
- [ ] Implementation

https://zpl.io/VQEQ6zn - Validator Profile

**Comment by NodeGuy** [comment]
Please remove issues from the backlog when moving them into Scrumptious.

**Comment by okwme** [comment]
- [ ] add new header to validator page
- [ ] create profile box with image and same info from LiDelegate.vue component
  - reuse that component?
- [ ] table with metadata (needs to be mostly stubbed as lots of the info isn't available)

**Comment by siman** [comment]
> https://zpl.io/VQEQ6zn - Validator Profile
no access :(
