### ISSUE TITLE
staking Params and Pool

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1172]
Description:

Implement design to implement the view for querying `Params` and `Pool`
See PR: cosmos/cosmos-sdk#2099

- [x] Endpoints
- [x] [Design](https://app.zeplin.io/project/59e66beff6721ea8bf562e5b/screen/5bb26dc2cc296e3ffefa3046): Tab
- [ ] Implementation

**Comment by jbibla** [comment]
hey @fedekunze can you help explain what is required here? what is the feature? how should it work?

**Comment by fedekunze** [comment]
@jb There are 2 new staking endpoints to query info about global parameters and the staking pool. You can see the list of attributes returned [here](https://github.com/cosmos/cosmos-sdk/blob/develop/docs/sdk/clients.md#query-parameters). 

The new staking endpoints are `GET stake/pool` and `GET stake/parameters`.

In short, this would require a modal or new tab in staking that shows this information.

**Comment by NodeGuy** [comment]
Is this on the [roadmap](https://docs.google.com/document/d/1UMlt44hyO8igXlYY3AnIFPit-HGpeSBoL0oel0A-GZk/edit#heading=h.vbhggi2rgbo3)?

I'm concerned about feature creep.  Let's consider this for Staking 2.0.

**Comment by jbibla** [comment]
@fedekunze i am not convinced we need to show this data in voyager. do you think we should? can you make a case for it?

**Comment by faboweb** [comment]
I think parameters for a network would be nice to show, right?

**Comment by jbibla** [comment]
maybe - but i don't think this is a `staking` issue.

**Comment by fedekunze** [comment]
imo it's defenitely `staking`. The inflation, unbonding period, max number of validators on the Hub, etc are things that are very important for delegators to be aware of

**Comment by faboweb** [comment]
Fede argues it is low work high value: we could have a simple modal showing with a button on the staking page showing this.

**Comment by faboweb** [comment]
> nothing is simple 😜

hahahah soooooo true

**Comment by faboweb** [comment]
@jbibla do you have designs for this on your todo list?

**Comment by jbibla** [comment]
very simple design: https://zpl.io/bo9WBnZ

**Comment by NodeGuy** [comment]
Why is this blocked?

**Comment by jbibla** [comment]
was blocked by an absence of designs.

**Comment by fedekunze** [comment]
@jbibla should I proceed with the comments I added to the Params Tab ?

**Comment by jbibla** [comment]
yes! they are all great points / suggestions.
