### ISSUE TITLE
Cosmos address component

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1173]
the UI can abbreviate addresses and pubkeys for a friendlier and less cluttered UI. 

though, bech32 prefixes have made our address _a bit_ more readable - they are still for computers (let's be honest).

i'd like to propose that we abbreviate addresses and pubkeys - the tooltip could display the full address. see below.

this will result in a more readable, less overwhelming, cleaner UI. 🥇 
```
cosmosvalpub12ztjt9nfj20cxw4w4fdg5g0lak83mc23csqzgx
cosmosvalpub...qzgx

cosmosaccaddr1qk2q3l28t6qhzyc7psdffsdf832ep8uwdaer
cosmosaccaddr...daer
```

**Comment by faboweb** [comment]
I vote yes. We probably need to show some letters in the beginning and some in the end.

**Comment by jbibla** [comment]
are you proposing the following? not sure if i agree. would like others to weigh in. we have these nifty bech32 prefixes which might be "enough".
```
cosmosvalpub12zt...qzgx
cosmosaccaddr1qk2...daer
```

**Comment by faboweb** [comment]
Yes this is what I mean. Just for a sense of security.

**Comment by NodeGuy** [comment]
Do you mean "elide" instead of "concatenate"?

**Comment by jbibla** [comment]
update from SDK (can't find the issue):

```
cosmosval12zt...qzgx
cosmos1qk2...daer
```
or
```
cosmosval...qzgx
cosmos...daer
```

> Do you mean "elide" instead of "concatenate"?

hard to say.

**Comment by faboweb** [comment]
Hö? They renamed `cosmosaccaddr` to `cosmos`?

**Comment by jbibla** [comment]
i believe so - @jackzampolin can you link the ticket? i'm sorry, i can't find it 😞

**Comment by NodeGuy** [comment]
Do you mean this PR?  https://github.com/cosmos/cosmos-sdk/pull/2103

**Comment by NodeGuy** [comment]
This proposal is about abbreviating addresses.  Concatenate means [to link together in a series or chain](https://www.merriam-webster.com/dictionary/concatenate).

**Comment by NodeGuy** [comment]
Sounds good to me.

**Comment by jackzampolin** [comment]
@jbibla https://github.com/cosmos/cosmos-sdk/pull/2103 🙇

**Comment by faboweb** [comment]
add copying #1174

**Comment by fedekunze** [comment]
I'm not fully understanding what are we suppose to implement here and what are the functionalities of this component. Does it just need a tooltip ?
