### ISSUE TITLE
improve copy to clipboard ux

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1174]
1. low opacity until hover
2. hover turns to link color
3. copy _does not_ confirm with notify but rather a small checkmark and the word "copied"

![screen shot 2018-08-21 at 3 04 46 pm](https://user-images.githubusercontent.com/6021933/44423243-a2fa9580-a553-11e8-9cfb-16cde328a490.png)
![screen shot 2018-08-21 at 3 04 56 pm](https://user-images.githubusercontent.com/6021933/44423244-a2fa9580-a553-11e8-8f0c-0bd6102b18e9.png)

also including idea from #1173 for fun

![screen shot 2018-08-21 at 3 08 37 pm](https://user-images.githubusercontent.com/6021933/44423444-1f8d7400-a554-11e8-8347-c0049ecfb6a0.png)
![screen shot 2018-08-21 at 3 08 42 pm](https://user-images.githubusercontent.com/6021933/44423443-1f8d7400-a554-11e8-8731-5d61c24926ae.png)

**Comment by faboweb** [comment]
Just concerned about the initial low opacity. This has a bad contrast and might be overlooked.
