### ISSUE TITLE
Do not run publish step every time

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1177]
Description:

CI runs publish step everytime and it fails everytime.

**Comment by NodeGuy** [comment]
What do you mean by "everytime"?  Do you mean on every push?  I'm not seeing it on [the latest push](https://circleci.com/workflow-run/e5d052fe-95c3-401d-841d-c6ef089063bf).

**Comment by faboweb** [comment]
On every push to develop: https://circleci.com/workflow-run/c01fa5c9-8b35-495f-a049-36a053396188

**Comment by faboweb** [comment]
Still doing it: https://circleci.com/gh/cosmos/voyager/6844
