### ISSUE TITLE
No transactions when sending tokens to a friendly bot in a demo mode

### ISSUE THREAD

**Issue by siman** [cosmos/voyager#1181]
UI Version: 0.9.4

Description: No transactions when sending tokens to a friendly bot in a demo mode

1. Start Voyager
2. Click "Try Demo"
3. Sign in, Next
4. In Wallet, click "Send" button on any token from your balance
5. Specify the number of tokens and an address of a friendly bot (from the tip at the bottom of the form) as `cosmosaccaddr1p6zajjw6xged056andyhn62lm7axwzyspkzjq0`
6. Click "Send Tokens" button
7. Confirm a transaction, see a green successful message

**Exptected**: See new transactions on Transactions page
**Actual**: Transactions page is empty

![image](https://user-images.githubusercontent.com/153928/44658446-89e95d00-aa09-11e8-9e68-828c04332cdf.png)

**Comment by faboweb** [comment]
This is fixed in the next release. Stay tuned.

**Comment by NodeGuy** [comment]
Fixed in https://github.com/cosmos/voyager/releases/tag/v0.10.1.
