### ISSUE TITLE
test if errors work in voyager

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1192]
As of https://github.com/cosmos/cosmos-sdk/pull/2119 errors returned by the LCD are not longer plain text (with a lot of additional noise) but a JSON object. This should deprecate the need to parse out the error message from this plain text error.
The question is, is there an additional need to adjust Voyagers error parsing (to show the correct error to the user) or do we still need to parse the error from the JSON object.

**Comment by NodeGuy** [comment]
What does this mean?

**Comment by faboweb** [comment]
Updated the description.

**Comment by NodeGuy** [comment]
So is this a spike proposal?

**Comment by NodeGuy** [comment]
How did it end up in Scrumptious with no one assigned?

**Comment by faboweb** [comment]
This was a follow up for @fedekunze ticket on the SDK. I forgot the assign someone as it wasn't created in process. I will get to it if I find time.

**Comment by faboweb** [comment]
Plan:
- produce an error in the LCD (like not enough atoms to stake)
- check if Voyager displays the error user friendly
