### ISSUE TITLE
SDK: Create simple test for /stake/delegators/{delegatorAddr}

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1193]
We're working on improving the performance of /stake/delegators/{delegatorAddr} in https://github.com/cosmos/voyager/issues/1133.

To support this work we need a simple unit test.  Currently there is a test called [TestBonding](https://github.com/cosmos/cosmos-sdk/blob/fb5fe9914d2489f15450a0b9ccde9b5c06a26e16/client/lcd/lcd_test.go#L427-L510) which is 84 lines of code and very complex.  We need a test that:

* is simple
* creates its own node and Gaia Lite server
* creates a state of one account delegating to another, nothing else
* creates the state using the Go API, not REST calls
* creates a deterministic state that's the same in every test, including the keys/addresses of both accounts
* located in `x/stake/client/rest` (e.g., `rest_test.go`, near the code it's testing)

**Comment by faboweb** [comment]
I would advice defering any tests like this, until the SDK team has delivered a framework for testing the enables us to easyly do all those things. We can get on their nerves about this, but I don't think we should be developing this.

**Comment by faboweb** [comment]
Very nicely written issue btw. :) 👍

**Comment by NodeGuy** [comment]
Moved to https://github.com/cosmos/cosmos-sdk/issues/2307.
