### ISSUE TITLE
Start writing contract tests.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1194]
We depend on the Gaia Lite REST API in the SDK.  Sometimes it changes, which breaks our code.

Both the SDK and Voyager have tests for the behavior of the API.  We can unify some of the two separate tests suites into contract tests, making sure the tests are the same on both sides, therefore ensuring agreement about what the behavior should be.  The contract will be written by Voyager so that it's a [consumer-driven contract](https://martinfowler.com/articles/consumerDrivenContracts.html).  This means that the contract cannot be changed without communicating with the Voyager team.

This will have the following benefits:

* We'll be reusing test code in both the SDK and Voyager, reducing complexity.
* Because the tests will be the same in both projects, divergent expectations about behavior will be prevented.
* The contract will be a natural forcing function to trigger communication about breaking changes between the two teams.
* We can use the contract tests in favor of some of our end-to-end tests (see [7 Reasons to Choose Consumer-Driven Contract Tests Over End-to-End Tests](https://reflectoring.io/7-reasons-for-consumer-driven-contracts/)), reducing the problems we've been having with the E2E tests (slowness, non-deterministic, difficulty in diagnosing failures).

We can start by creating a single, simple test and then adding more over time.  [Pact](https://docs.pact.io/readme) is the de facto standard tool for creating contract tests.  It has libraries for [JavaScript](https://github.com/pact-foundation/pact-js) and [Go](https://github.com/pact-foundation/pact-go/).

**Comment by NodeGuy** [comment]
I'm changing this to `high priority` because our development velocity is gated by the slowness of the E2E tests.  Having good contract test coverage will allow us to gut the E2E tests and to increase our velocity.

**Comment by faboweb** [comment]
Would something like https://github.com/mkoryak/swagger-mock-server together with https://github.com/Trax-air/swagger-tester on the SDK side work for you? We already have the swagger definition as a contract format.

**Comment by NodeGuy** [comment]
* [Swagger UI](https://cosmos-staging.interblock.io/rpc/)
* [Swagger.yaml](https://raw.githubusercontent.com/cosmos/cosmos-sdk/7c9048b591de2aba9bf4c04aa1517f5c81d1a692/client/lcd/swagger-ui/swagger.yaml)
