### ISSUE TITLE
Add E2E test for showing transaction history

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1198]
UI Version: 0.9.4

Description:

We do not test, if the SDK correctly serves the txs.

**Comment by NodeGuy** [comment]
E2E tests [are really expensive](https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html).

This can be tested with a less expensive test.

The ideal would be [a contract test](https://github.com/cosmos/voyager/issues/1194).

**Comment by fedekunze** [comment]
blocked by #1375

**Comment by jbibla** [comment]
why is that blocked?

**Comment by faboweb** [comment]
I don't think the e2e tests are blocked on changing the location of the `TmLiTransaction` component

**Comment by NodeGuy** [comment]
Blocked by https://github.com/cosmos/voyager/issues/1575.

**Comment by fedekunze** [comment]
Fixed, removing label
