### ISSUE TITLE
Jank while loading validator profiles

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1199]
UI Version: 0.9.4

Description:

When starting the applications the app freezes for some seconds. I assume this is while downloading the validator profiles.

Chrome performance profile:
[Profile-20180829T120817.json.zip](https://github.com/cosmos/voyager/files/2331719/Profile-20180829T120817.json.zip)

**Comment by faboweb** [comment]
The reason is that for every update state is persistet which is costly since we are encrypting it.

**Comment by faboweb** [comment]
Plan:
- improve caching behavior by only updating the cache on actual updates
- cache keybase requests

**Comment by jbibla** [comment]
also, let's not block anything in making the requests to keybase. we can show a loading graphic or the default validator icon while loading. 

also, we can lazy load the images - which should limit the requests significantly.
