### ISSUE TITLE
Use the electron native about menu for version

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1201]
UI Version: 0.9.4

Description:

We are currently using a custom Vue component to show about information. We decided that the native Electron about menu would be a better UX.

Plan:
- Remove the Vue component about menu
- Activate the native about menu in the main thread (`index.js`)
- Show all information from the Vue component in the native about menu

Split from #1138

**Comment by faboweb** [comment]
- [ ] show native dialog
- [ ] display voyager, sdk, electron version
- [ ] test on Mac
- [ ] test on Windows
- [ ] test on Linux

**Comment by faboweb** [comment]
It looks like this on Mac:
![image](https://user-images.githubusercontent.com/5869273/44840031-87247d00-ac40-11e8-83ee-e2a69dfac2c0.png)

**Comment by jbibla** [comment]
🎉 awesome @faboweb
