### ISSUE TITLE
Validator page is displaying stake incorrect

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1207]
UI Version: 0.10.1

Description:
![image](https://user-images.githubusercontent.com/5869273/44791082-22661580-aba1-11e8-9ef4-7b9d7338b78d.png)
![image](https://user-images.githubusercontent.com/5869273/44791068-1a0dda80-aba1-11e8-828b-f30e2bcedd7e.png)

**Comment by fedekunze** [comment]
ohh I thought this was already solved. Let's also compare the returned validator_power string value from the Explorer, maybe it's having the same issue we had with `sdk.Dec`.

**Comment by faboweb** [comment]
The explorer receives `tokens: "6521/2"` for this validator.

**Comment by faboweb** [comment]
We are still displaying tokens vs. displaying voting_power. Will push a fix.
