### ISSUE TITLE
Releases of Voyager should identify which testnet(s) they work on

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#1212]
UI Version: `develop`

Description: I think that version 0.9.x of Voyager functioning with `gaia-8000` doesn't make much sense. Wouldn't it be better if we just publicly labeled this release as Voyager 8000?

**Comment by NodeGuy** [comment]
Yes, strong agreement.

**Comment by faboweb** [comment]
Does this have any implications for releases on GitHub or naming or the about section?

**Comment by NodeGuy** [comment]
SemVer is more important for libraries than applications.

**Comment by jbibla** [comment]
how will we increment version numbers after mainnet launch?

**Comment by NodeGuy** [comment]
Hmm, putting a non-semver version (`gaia-8001.1`) in package.json breaks Husky's pre-commit script.

**Comment by faboweb** [comment]
It says version is optional if you don't publish the package. Does something complain when we do not use semver?

**Comment by NodeGuy** [comment]
Running a script with npm fails.  I was unable even to commit the change because Husky failed to run the precommit script.

**Comment by NodeGuy** [comment]
How about we keep our current version scheme but also display the `default_network` value from `config.toml` in the About box and in the release binaries file names?

E.g.,

```
Cosmos_Voyager-v0.10.6-gaia-8001-macOS.zip
```

**Comment by faboweb** [comment]
Sounds reasonable. Just brainstorming: Can we use funky semver by putting the network number in there? Like 0.8001.1. After 1.x we could change that again.

**Comment by NodeGuy** [comment]
It would need to go in the major version to comply with SemVer (`8001.10.6`) because our testnets are not backwards compatible and we couldn't lower the version number to 1.x.x later because it's strictly increasing.

**Comment by faboweb** [comment]
It maybe doesn't comply with semver, but it also wouldn't crash any scripts I guess.

**Comment by faboweb** [comment]
A decision was made to do it, there is no technical problem doing so as 0.x.y is compatible to a semver version schema. After 1.x we implement true semver. So let's do it.

**Comment by jbibla** [comment]
i would propose we stick with semver for testnets and after mainnet launch. let's just change the title of the release for the testnet releases...

```
Cosmos Voyager Alpha v0.10.6 (UNSAFE)
Cosmos Voyager Alpha v.11.0 (Gaia-9000)(UNSAFE)
```

**Comment by faboweb** [comment]
👍 Bowing to the majority on this one then.

**Comment by NodeGuy** [comment]
Don't bow yet!  I forgot that we don't need to comply with the normal SemVer rules before 1.0.0.  We agreed in the meeting to go with Fabo's proposal.
