### ISSUE TITLE
Voyager ran into issue directly after starting

### ISSUE THREAD

**Issue by pypypy777** [cosmos/voyager#1213]
Version: v2.0.8

Description:
Got this Error after starting the App:

_"Voyager ran into an error
Voyager has encountered a critical error that blocks the app from running. Please create an issue and include a copy of the app logs."_

When siging up there was a bad connection window popping up on the top right so I restarted Voyager and after that siging up worked for me.
I am on a a Ubuntu 16.04.5 Machine

Log:
Wed Aug 29 2018 22:31:05 GMT+0200 (CEST) Running Cosmos-UI
main-process: initializing data directory (/home/markus/.cosmos-voyager/gaia-8001)
main-process: spawning /home/markus/Downloads/cosmos/resources/app/bin/gaiacli with args ""version""
main-process: gaiacli: 0.24.2-1c38c704

main-process: gaiacli version: "0.24.2", expected: "0.24.1"
main-process: pinging node: http://gaia-seed2.interblock.io:26657
main-process: gaiacli exited with code 0
main-process: Node gaia-seed2.interblock.io is alive
main-process: Picked node: gaia-seed2.interblock.io
main-process: starting gaia rest server with nodeIP gaia-seed2.interblock.io:26657
main-process: startLCD /home/markus/.cosmos-voyager/gaia-8001/lcd
main-process: spawning /home/markus/Downloads/cosmos/resources/app/bin/gaiacli with args ""advanced" "rest-server" "--laddr" "tcp://localhost:9071" "--home" "/home/markus/.cosmos-voyager/gaia-8001/lcd" "--node" "gaia-seed2.interblock.io:26657" "--chain-id" "gaia-8001""
main-process: View has booted
main-process: gaiacli: I[08-29|20:31:06.540] Starting RPC HTTP server on tcp://localhost:9071 module=rest-server 

main-process: gaiacli: I[08-29|20:31:06.540] REST server started                          module=rest-server 

Wed Aug 29 2018 22:31:07 GMT+0200 (CEST) Running Cosmos-UI
main-process: root exists (/home/markus/.cosmos-voyager/gaia-8001)
main-process: configs are compatible with current app version
main-process: spawning /home/markus/Downloads/cosmos/resources/app/bin/gaiacli with args ""version""
main-process: gaiacli: 0.24.2-1c38c704

main-process: gaiacli version: "0.24.2", expected: "0.24.1"
main-process: pinging node: http://gaia-seed1.interblock.io:26657
main-process: gaiacli exited with code 0
main-process: gaiacli: I[08-29|20:31:07.514] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:58172

main-process: gaia rest server ready
main-process: Signaling connected node
main-process: gaiacli: I[08-29|20:31:07.619] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:58184
I[08-29|20:31:07.619] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:58180

main-process: Node gaia-seed1.interblock.io is alive
main-process: Picked node: gaia-seed1.interblock.io
main-process: starting gaia rest server with nodeIP gaia-seed1.interblock.io:26657
main-process: startLCD /home/markus/.cosmos-voyager/gaia-8001/lcd
main-process: spawning /home/markus/Downloads/cosmos/resources/app/bin/gaiacli with args ""advanced" "rest-server" "--laddr" "tcp://localhost:9071" "--home" "/home/markus/.cosmos-voyager/gaia-8001/lcd" "--node" "gaia-seed1.interblock.io:26657" "--chain-id" "gaia-8001""
main-process: gaia rest server ready
main-process: gaiacli: I[08-29|20:31:09.577] Served RPC HTTP response                     module=rest-server method=GET url=/node_version status=200 duration=2060 remoteAddr=127.0.0.1:58174
I[08-29|20:31:09.590] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:58190

main-process: gaiacli: panic: resource temporarily unavailable

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/client/lcd.createHandler(0xc420836c40, 0x5, 0x7ffcf06b1521)
	/go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:78 +0x634
github.com/cosmos/cosmos-sdk/client/lcd.ServeCommand.func1(0xc420b54900, 0xc42082ef80, 0x0, 0x8, 0x0, 0x0)
	/go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:40 +0x8e
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc420b54900, 0xc42082ee80, 0x8, 0x8, 0xc420b54900, 0xc42082ee80)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:698 +0x46d
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1697d20, 0xe13aa0, 0x24, 0xc420af9e08)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0x1697d20, 0xc42014f760, 0x1697e00)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x1697d20, 0xf5d980, 0x2, 0xc420b403c0)
	/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/go/src/github.com/cosmos/cosmos-sdk/cmd/gaia/cmd/gaiacli/main.go:151 +0xcce

main-process: gaiacli exited with code 2
main-process: gaiacli: I[08-29|20:31:09.736] Served RPC HTTP response                     module=rest-server method=GET url=/node_version status=200 duration=117 remoteAddr=127.0.0.1:58194

main-process: gaiacli: I[08-29|20:31:10.165] Served RPC HTTP response                     module=rest-server method=GET url=/validatorsets/latest status=200 duration=444 remoteAddr=127.0.0.1:58184

main-process: View has booted
main-process: Signaling connected node
main-process: The gaiacli rest-server (LCD) exited unplanned
main-process: gaiacli: I[08-29|20:31:12.147] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:58200

main-process: gaiacli: I[08-29|20:31:12.148] Served RPC HTTP response                     module=rest-server method=GET url=/keys status=200 duration=0 remoteAddr=127.0.0.1:58200

main-process: gaiacli: I[08-29|20:31:12.202] Served RPC HTTP response                     module=rest-server method=GET url=/validatorsets/latest status=200 duration=616 remoteAddr=127.0.0.1:58184

main-process: gaiacli: I[08-29|20:31:14.308] Served RPC HTTP response                     module=rest-server method=GET url=/validatorsets/latest status=200 duration=527 remoteAddr=127.0.0.1:58200

main-process: gaiacli: I[08-29|20:31:20.747] Served RPC HTTP response                     module=rest-server method=GET url=/validatorsets/latest status=200 duration=523 remoteAddr=127.0.0.1:58200

**Comment by faboweb** [comment]
@pypypy777 did you have another instance of the cli/SDK open that used `/home/markus/.cosmos-voyager/gaia-8001/lcd` as a config dir? This error could appear when the keystore database is locked by another process.

**Comment by pypypy777** [comment]
Thanks for the response guys
@faboweb   
I restarted my machine and the same error still occurs however I can still use the Voyager app and send transactions and everything.

However, when I run a full node I cannot connect to any peers currently (already tryed different ones) may this be related to this issue?

**Comment by faboweb** [comment]
Which error still occurs? `"Voyager ran into an error
Voyager has encountered a critical error that blocks the app from running. Please create an issue and include a copy of the app logs."` should prevent you from using Voyager.

Which network are you trying to connect to with your full node?

**Comment by pypypy777** [comment]
This time I had to restart Cosmos Voyager until it worked and I could login. Before I was getting this error [log:](https://pastebin.com/jV2J08q8)
The app is successfully getting the lattest blocks. I connected to gaia-8001 with the cosmos voyager client. 

The full node I tryed on gaia-6002 as described in the documentation. I also tryed different seeds and peers as described in this [tutorial](https://medium.com/forbole/a-step-by-step-guide-to-join-cosmos-hub-testnet-e591a3d2cb41) but it didnt work

**Comment by pypypy777** [comment]
Update: I ran Voyager from the shell and it worked fine but gave me these errors:

(nautilus:1345): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:1345): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:1345): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(nautilus:1345): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(nautilus:1345): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

**Comment by pypypy777** [comment]
Ah thanks for the notice I guess this [part](https://cosmos.network/docs/getting-started/full-node.html#genesis-seeds) of the the docs should be changed then

**Comment by jbibla** [comment]
looks like a version error - as @fedekunze mentioned. also, doesn't seem to be related to 6002.

from the log:

```
main-process: gaiacli version: "0.24.2", expected: "0.24.1"
...
main-process: spawning /home/markus/Downloads/cosmos/resources/app/bin/gaiacli with args ""advanced" "rest-server" "--laddr" "tcp://localhost:9071" "--home" "/home/markus/.cosmos-voyager/gaia-8001/lcd" "--node" "gaia-seed1.interblock.io:26657" "--chain-id" "gaia-8001""
```

**Comment by faboweb** [comment]
`gaiacli version: "0.24.2", expected: "0.24.1"` this is a patch version and shouldn't be a problem
