### ISSUE TITLE
Complete unbonding transaction

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1220]
- [x] Design
- [ ] Implementation

Unbonding stake is split into 3 phases:
- first the user needs to send an unbonding tx, this triggers the unbonding intent
- the user now needs to wait for a certain amount of time (30days or something) set for the network
- after 30 days the user needs to end the unbonding by sending another "end unbonding" transaction to receive his stake back liquid in his account

Note: the user will not get slashed after the unbonding period as far as I know

In the designs, Jordan calls the termination of the tx "Claim".

**Comment by NodeGuy** [comment]
@jbibla Please link your design here.

**Comment by jbibla** [comment]
not sure which you meant, so here are two designs.

https://zpl.io/bWL0krn - Unstaking
https://zpl.io/bWLnE7e - Claim

**Comment by NodeGuy** [comment]
Uh oh, if you don't know what the design is then we can't call the design "done" and I can't implement it.

I created this issue from the "End unbonding" section of the roadmap.

We need a written spec for what this means.  @faboweb?

**Comment by faboweb** [comment]
I updated the description

**Comment by jbibla** [comment]
yes, this is a new concept for me. please use the same interaction model and design we have for "claim".

**Comment by jbibla** [comment]
i'm saying the design for "claim" can be used for "complete unbonding" which can be found here https://zpl.io/bWLnE7e

**Comment by faboweb** [comment]
Scope:
- add action button to the TmLiTransaction template in tendermint/ui
- change TmLiStakeTransaction for the unbonding transaction to
  - show the time until the unbonding period is over (where to get the unbonding period?)
  - show the call to action (disabling it until period is over)
- create action to send end unbonding transaction
- link end unbonding action to call to action on tx

**Comment by NodeGuy** [comment]
> i'm saying the design for "claim" can be used for "complete unbonding" which can be found here https://zpl.io/bWLnE7e

Oh, I get it.  Man, we're really good at generating lingo and synonyms!  :-)
