### ISSUE TITLE
Bonding Page Bugs

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#1263]
This looks like the same decimal problems we were having before...
![screenshot 2018-09-03 14 24 30](https://user-images.githubusercontent.com/964052/44986793-3933b000-af85-11e8-9a81-ab32aaf73359.png)

(the one below is an easy fix and already taken care of)
![screenshot 2018-09-03 13 58 25](https://user-images.githubusercontent.com/964052/44986767-2a4cfd80-af85-11e8-8c05-2d2bf1b2e496.png)

**Comment by NodeGuy** [comment]
Please remove issues from the backlog when moving them into Scrumptious.

**Comment by NodeGuy** [comment]
What are the steps to recreate this bug?

**Comment by faboweb** [comment]
@NodeGuy stake to a validator, wait until you get rewards/slashed, check the bonding page

**Comment by NodeGuy** [comment]
Forgive me for missing the obvious, but how long do I have to wait to get rewards/slashed?  I've been waiting a long time.

**Comment by faboweb** [comment]
If you stake to one of the top validators it should be less then 100 blocks I guess. But I am not sure.

**Comment by NodeGuy** [comment]
I've watched at least 10,000 blocks go by with no rewards.  @okwme Would you please walk me through how to recreate this bug?
