### ISSUE TITLE
Show loading indicator in staking overview

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1270]
UI Version: 0.10.2

Description:

Loading staking info (staked atoms) takes a long time (45s). We cache the results to improve UX. Still we need to show an indicator, that Voyager is still loading the data from chain.

**Comment by jbibla** [comment]
i actually think for loading the staking overview (at 45s) we need to have an obtrusive loader. 🐌

**Comment by faboweb** [comment]
while loading the first time. after that, it could be done unobtrusive don't you think?

**Comment by fedekunze** [comment]
waiting for cosmos/cosmos-sdk#2249 to be merged so that we won't require the loader
