### ISSUE TITLE
Unobtrusive loading indicator 

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1271]
UI Version: 0.10.2

Description:

Our loading indicator is pretty big and bold. While we are moving towards an optimistic UI, I think we should go for a more decent loading indicator. The loading indicator shouldn't block the user from interacting.

Example:
![image](https://user-images.githubusercontent.com/5869273/45021891-0c3dd680-b033-11e8-9179-1f3fa8946c5a.png)

**Comment by jbibla** [comment]
which loader are you saying is obtrusive?

**Comment by faboweb** [comment]
`tm-data-loading`

**Comment by faboweb** [comment]
@jbibla what is your take on prio on this?
