### ISSUE TITLE
Create My Stake tab.

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#1278]
Originally part of https://github.com/cosmos/voyager/issues/1054 this was blocked because it was non-trivial to acquire a list of all validators to which the current user is currently unbonding from. Once that data is available it is possible to use the tab "My Stake" as a trigger for filtering the validators into sections of bonding and unbonding.

Scope:

- [x] create my stake page
- [x] link my stake page from the tabs menu
- [x] create list of validators you have bond with (based on `committedDelegations`)
- [x] create list of validators you are unbonding from (based on `unbondingDelegations`)
- [x] add link to all validators

**Comment by faboweb** [comment]
This should be possible right now. We are already querying this data. The data lives in `delegations.js -> state.unbondingDelegations`.

**Comment by jbibla** [comment]
`unbondingDelegations` is not the same as "bonded delegators" by which i think @okwme means "currently bonded validators".

**Comment by faboweb** [comment]
> all validators to which the current user is currently unbonding from

sounds like `unbondingDelegations`. maybe the title is wrong, maybe I am wrong. 🤷‍♂️

**Comment by faboweb** [comment]
accessing the current state of the my stake page:
the distinction in bonded / unbonding validators is missing.

**Comment by siman** [comment]
Is it possible to see your designs before implementing them or maybe even take some part in discussions?

**Comment by jbibla** [comment]
that sounds like a great idea.

[here is a link](https://scene.zeplin.io/project/59e66beff6721ea8bf562e5b) to some designs we're working on.

**Comment by faboweb** [comment]
Scope:
- [ ] create my stake page
- [ ] link my stake page from the tabs menu
- [ ] create list of validators you have bond with (based on `committedDelegations`)
- [ ] create list of validators you are unbonding from (based on `unbondingDelegations`)
- [ ] add link to all validators

**Comment by NodeGuy** [comment]
Your scope expands the issue beyond bonded delegators.  I've copied your scope additions to the main body and changed the title.

**Comment by NodeGuy** [comment]
I see now there was already an issue for [implement "My Stake" page](https://github.com/cosmos/voyager/issues/1054) which was closed even though it wasn't done.  Man, this is confusing.

**Comment by NodeGuy** [comment]
I split out the completion of LiDelegate to #1319.
