### ISSUE TITLE
combine bonding page w validator profile

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#1280]
Necessary to complete this issue https://github.com/cosmos/voyager/issues/1054 as once the checkboxes are removed there is no way to get to the bonding page. If the bonding actions were included on the validator page as the [new designs](https://zpl.io/aBNdBxK) detail, the checkboxes could be removed.

**Comment by NodeGuy** [comment]
Covered by https://github.com/cosmos/voyager/issues/1219, https://github.com/cosmos/voyager/issues/1293, and https://github.com/cosmos/voyager/issues/1294.
