### ISSUE TITLE
prioritize connecting to full nodes that are already "caught up"

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1282]
sometimes, voyager will connect to a full node that isn't caught up yet which is a drag for the user and can can possibly prohibit transactions from taking place. instead, before connecting to a full node, let's check to see if they are caught up or not. this will provide a superior UX for our users.

**Comment by fedekunze** [comment]
It's posible to get the node status with this [endpoint](https://tendermint.github.io/slate/?shell#status) and later get the `result.sync_info` from it. In this case you're suggesting to connect with the nodes that have `result. sync_info. syncing = false` value only ?

**Comment by NodeGuy** [comment]
Please add the label `discuss` to all new issues.

**Comment by jbibla** [comment]
if `result. sync_info.syncing = true` when a node is syncing / catching up - then yes.

do you think that's a good idea?

**Comment by fedekunze** [comment]
Closing this as we are connecting to a trusted full node already
