### ISSUE TITLE
Read SDK distribution spec and extract commission earned formula.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1285]
Read the [distribution specification](https://github.com/cosmos/cosmos-sdk/tree/develop/docs/spec/distribution) and extract the formulas necessary to implement:

- [ ] a user should be able to see how many fee shares they have been issued from each validator they have delegated to.
- [ ] we should display the approximate value of these fee shares

Supports #135

**Comment by rigelrozanski** [comment]
Not to throw a wrench in the UI - but you should know that the only "static and increasing" thing which a delegation will be gaining to represent their rewards is something called "accumulation". The current mechanism works in such a way that the actual rewarded tokens which are distributed when withdrawing "accumulation" can actually fluctuate based on change in incoming fees and other delegators of the same validator withdrawing their accumulation. - So on a really bad day, as a delegator, if you are not withdrawing accumulation, you may end up having less rewards available to you at the end of the day even though you have gained accumulation.

**Comment by rigelrozanski** [comment]
think of accumulation as a "share in available rewards to withdraw from a validator" Because incoming rewards fluctuate, the expected worth of these "accumulation-shares" also fluctuate. 

You can ALWAYS withdraw all your accumulation. The value of your accumulated shares may decrease based on the dynamics of this system however

**Comment by jbibla** [comment]
ah! interesting!

> The value of your accumulated shares may decrease 

in what situation would this occur? in the event of slashing perhaps?

**Comment by rigelrozanski** [comment]
Rephrased from the spec:

>If you happen to know that incoming rewards are about significantly move up,
you are incentivized to not withdraw until after this event, increasing the
worth of your existing _accum_.

The same is true of the fees suddenly dropping - if everyone else but you knew this was going to happen and they withdrew their fees, but you didn't, and then the fees dropppppped, then the relative worth of each of your accum with be reduced as new fees/accum were added

**Comment by faboweb** [comment]
More from a technical standpoint:
- can I query for accum shares already?
- on which events do the accum shares change their value? (so we can requery the shares) as from what I got, when the reward pool size changes, am I correct?

**Comment by rigelrozanski** [comment]
I'm implementing this mechanism right now - but I think it makes sense to be able to query for the accum yes, also we could implement a query for current worth of the accum as well (although it may be a tiny bit expensive so validator nodes probably should respond to this query)

**Comment by faboweb** [comment]
> although it may be a tiny bit expensive so validator nodes probably should respond to this query

You mean `shouldn't`? validator nodes should probably anyway not respond to queries I thought?!

> Every block when rewards are added the worth of accum shares changes value.

thx. here are multiple events described: https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/distribution/state.md . are these irrelevant?

**Comment by rigelrozanski** [comment]
the big one is here: https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/distribution/end_block.md 
where we describe what happens when the rewards are added to the distribution

**Comment by faboweb** [comment]
Let me sum up how I understand this:
You want applications to recalculate the reward pool for each validator client side after each block? Isn't that impractical? How about we trigger an event "PoolChanged" so we don't need to replicate the logic client side?

**Comment by rigelrozanski** [comment]
Just to be clear, the SDK doesn't calculate the PoolWorth until a withdraw transaction is submitted, which means, the worth of each accum for each delegation is actually unknown by the hub until the specific delegator submits a transaction. 

The only thing I can see that would work was is the applications only provide an estimated worth of a delegators accum which can be calculated on the application side either on demand by the user or some rough interval such as per once per 10 minutes or hour etc. probably want to also provide the worth in the form "estimated worth of unwithdrawn rewards is [value] at [datetime]"

**Comment by faboweb** [comment]
Getting everything now from stargate
