### ISSUE TITLE
We are displaying shares

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1289]
UI Version: 0.10.3

Description:

We are currently displaying shares received from `/stake/delegators/...`. Those are not atoms. Shares need to be multiplied with a token count of the validator.
We can either choose to show shares or calculate atoms.

**Comment by jbibla** [comment]
i would propose calculating atoms

**Comment by faboweb** [comment]
same here. I would propose calculating atoms even already on the lcd side. does a client need to care about shares?

**Comment by jbibla** [comment]
does a client need to care about shares? 

i can imagine a client caring about shares - but voyager doesn't have to IMO
