### ISSUE TITLE
Implement redelegation

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1293]
Description:

Designs:
- [Modal](https://zpl.io/VxlvdWk)
- [Tx History](https://app.zeplin.io/project/59e66beff6721ea8bf562e5b/screen/5b8d49746fb4e0204a7beca7)

Scope:
- [x] Implement redelegation tx design in tendermint/ui
- [x] Add redelegation tx to tx history
- [x] Implement redelegation in the new delegation popup
- [x] Implement sending the redelegation transaction

**Comment by fedekunze** [comment]
Closed by #1310
