### ISSUE TITLE
Refactor app/src/renderer/vuex/modules/delegation.js/submitDelegation

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1300]
It currently assumes knowledge of existing delegations.  With the new UX this is unnecessary and adds complexity.

**Comment by faboweb** [comment]
Could you elaborate a little more on what you mean with `It currently assumes knowledge of existing delegations` and why `With the new UX this is unnecessary and adds complexity.`?

**Comment by okwme** [comment]
Also curious what you mean exactly @NodeGuy 
But would like to add that I also noticed this function needs some refactoring. Especially with regard to correctly calculated optimistic updates on atom/share amounts and querying the new delegates to confirm the optimistic updates only after a new block header has been received. Maybe this issue should be split up into David's specific task as well as these:

- [ ] Update shares/atoms as optimistic updates
- [ ] Query actual delegate shares/atoms only after new block header

**Comment by NodeGuy** [comment]
> Could you elaborate a little more on what you mean with It currently assumes knowledge of existing delegations and why With the new UX this is unnecessary and adds complexity.?

My understanding is that the old design would display the current state of delegation and allow the user to modify it.  

For example:

currently delegated: 5 atoms
additional amount to delegate: 2 atoms

`submitDelegation` takes as input 7 atoms, reflecting both the state of the current delegation and the new.

The new design doesn't make any reference to the previous delegation:

additional amount to delegate: 2 atoms

This means that `submitDelegation` can take as input 2 atoms, not having to deal with the complexity of computing the previous delegation amount.

Is my understanding correct?

**Comment by faboweb** [comment]
I get it:
In the new design delegating and undelegating are 2 separate interactions and they both get as an input the diff. So we don't need to calculate the diff in `submitDelegation`.
Sounds good.
