### ISSUE TITLE
Cannot read full address

### ISSUE THREAD

**Issue by haasted** [cosmos/voyager#1304]
UI Version: v0.10.2-macOS

While inspecting validators to find a suitable staking destination, I noticed that the Pub Key field of one of them was truncated by the UI:
![screen shot 2018-09-11 at 12 05 31](https://user-images.githubusercontent.com/1016810/45353563-6dc5ee00-b5bb-11e8-8ba1-1675573fe2cb.png)

There appears to be no way to expand the line and access the entire address.

**Comment by faboweb** [comment]
We are redesigning the validator page right now. We will pay attention to put your feedback in effect there.
Until then: can you double click the pubkey and copy the whole key this way?

**Comment by haasted** [comment]
@faboweb : Yes, double-clicking and copying will include the entire string. 

Manually selecting the entire, visible string will only copy the visible parts.

**Comment by jbibla** [comment]
thank you @haasted - is this on the explorer at cosmosexplorer.com?
