### ISSUE TITLE
Claim staking rewards

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1306]
I as a user
Want to be able to claim rewards I have with validators
So that I can receive my earnings from the system

AC:
- [ ] button on delegations tab (following JBs designs)
- [ ] claim should open an action modal to sign the claim transaction

Old:
There is a tx for withdrawing all rewards TxWithdrawDelegationRewardsAll
It is also possible to withdraw just from one validator which we can implement as a 2nd step.

We probably need to create an endpoint to query for rewards, as there is none right now or calculate it clientside. For calculating it clientside we still need additional information like ValidatorDistInfo and DelegatorDistInfo as seen in the wihdraw calculation done here. I suppose just querying the calculated data is better as it leaves the logic on the SDK side.

As for updating the rewards, they are triggered on following events (taken from https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/distribution/state.md):

delegation amount to a validator is updated,
a validator successfully proposes a block and receives a reward,
any delegator withdraws from a validator, or
the validator withdraws it's commission.

**Comment by faboweb** [comment]
Follow up of #520

**Comment by fedekunze** [comment]
see design comments on #2010
