### ISSUE TITLE
Staking without staking

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1308]
Commit 47cd3936ed250223e0a354727c77a65571e6a372

Go to PageBond
Don't change a thing
Confirm
Delegate

This will create a delegation request.

**Comment by NodeGuy** [comment]
PageBond will be replaced soon by https://github.com/cosmos/voyager/issues/1219.

**Comment by faboweb** [comment]
It is/was a problem with the comparison of old atoms vs new atoms. If it will not be a problem with the new implementation, we can close this.

**Comment by NodeGuy** [comment]
I suspect it won't be a problem.  Let's close it for now and re-open if necessary.
