### ISSUE TITLE
add e2e tests for unbonding flow

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1311]
Description:

The test should test the flow:
- [ ] stake to a validator
- [ ] unbond from a validator

**Comment by NodeGuy** [comment]
Do I remember correctly that "claim tokens from unbonding" is now automatic?

**Comment by faboweb** [comment]
> Do I remember correctly that "claim tokens from unbonding" is now automatic?

Good catch. I delete the point.

**Comment by faboweb** [comment]
Actually already implemented
