### ISSUE TITLE
Hide notification error if it's already shown

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1315]
**Description:**

<img width="984" alt="screen shot 2018-09-13 at 4 11 19 pm" src="https://user-images.githubusercontent.com/31522760/45493818-e9689c00-b76f-11e8-94c7-7dd4acac0666.png">

We should check if the error is the same as one of the others displayed before pushing the notification

**Comment by jbibla** [comment]
at least, position absolute or fixed instead of relative

**Comment by faboweb** [comment]
> position absolute

sounds like an easy solution

**Comment by fedekunze** [comment]
duplicate from #1468
