### ISSUE TITLE
Complete LiValidator.vue

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1319]
The following code is incomplete:

```JavaScript
    slashes() {
      return "n/a" //TODO: add slashes
    },
    commission() {
      return "n/a" //TODO: add commission
    },
    uptime() {
      return "n/a" //TODO: add real uptime
    },
    yourRewards() {
      return "n/a"
    },
```

**Comment by faboweb** [comment]
> Uptime can be calculated from the validator signing info endpoint:
Uptime (%) = signingInfo.signed_blocks_counter * 100/ (latest_block_height - signingInfo.start_height)

100 blocks is not much. Maybe go for 10000 blocks? Plus I feel a lot will have like 99.99% uptime which doesn't say much. How about displaying failed blocks?

> Uptime can be calculated from the validator signing info endpoint:
Uptime (%) = signingInfo.signed_blocks_counter * 100/ (latest_block_height - signingInfo.start_height)

How about adding this to the queriers?

**Comment by fedekunze** [comment]
@faboweb the `*100` is to calculate the % 😄

**Comment by fedekunze** [comment]
@faboweb I think adding a `slashing/jailed` counter on the sdk would make sense. cc: @cwgoes

**Comment by faboweb** [comment]
> @faboweb the *100 is to calculate the % 😄

ahhhh hahahahaah sorry nvm

**Comment by cwgoes** [comment]
> @faboweb I think adding a slashing/jailed counter on the sdk would make sense. cc: @cwgoes

Can you further explicate? To find the number of slashes or jail/unjails within a certain block range you can query the events by tag and sum up the length of the array.

I don't think we want to track unnecessary data in consensus state. In the future special indexing nodes could do such a thing, but that's probably out of scope prelaunch.

**Comment by faboweb** [comment]
Querying all slashing txs for a certain range and then mapping them to validators might be a good solution.

**Comment by NodeGuy** [comment]
Possibly related to https://github.com/cosmos/voyager/issues/1285.
