### ISSUE TITLE
Change PageValidator boxes background color

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1324]
Description:

As per our discussion in #1317.  The current validator information boxes (e.g: owner, commission, etc) are similar to our input form fields. Let's change the background color (e.g to gray) to make them more distinguishable. 

![image](https://user-images.githubusercontent.com/31522760/45759296-e534f680-bc27-11e8-9e03-aef330c777a5.png)

**Comment by jbibla** [comment]
@fedekunze can you share a screenshot - i think i know what you're talking about but i want to make sure.

**Comment by faboweb** [comment]
Note: The info boxes ("My Stake" et al) look a lot like input fields as well. So maybe we shouldn't make the background gray as is there.

**Comment by jbibla** [comment]
i'd like to propose that we change the title of this ticket to be "Improve disabled state for input fields" - but i agree - we should do this!

**Comment by faboweb** [comment]
I think we may need to have different elements for showing data and for inputs (even if they are disabled). Users will never be able to change the data on there.

**Comment by jbibla** [comment]
the reason i like inputs (disabled / readonly) is because it shows that the data is malleable. 

but i am open to other suggestions. what would you guys like to see?

**Comment by faboweb** [comment]
What do you mean with malleable?

**Comment by jbibla** [comment]
i think it's the wrong word... but the point is that the validator can change it / it's editable for certain people.

**Comment by faboweb** [comment]
Not for any user of our product. But I understand the point. I retract my concerns.

**Comment by faboweb** [comment]
Is this still a thing?

**Comment by jbibla** [comment]
yes.

**Comment by jbibla** [comment]
no. sorry. we can include some of these points in staking-2 if it comes up. i am working on improvements that make this less relevant.

- information shouldn't look like inputs
- our disabled / readonly inputs have been improved already
- it would be nice to include colours in the future but it will require more consideration (at a later date)
