### ISSUE TITLE
Add status dots on the validator Li component

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1325]
Description:

Without them it's hard to distinguish a validator that is revoked from one that is not (see https://github.com/cosmos/voyager/pull/1317#discussion_r218400727).

Original designs:

- [Validator Index](https://app.zeplin.io/project/59e66beff6721ea8bf562e5b/screen/5b86c70526b2ec29512fcf21)
- [Validator Index - Status](https://app.zeplin.io/project/59e66beff6721ea8bf562e5b/screen/5b8db0a505c1be1b71089641)

**Comment by jbibla** [comment]
yep!

**Comment by fedekunze** [comment]
I think this is being addressed on #1367 ? cc: @faboweb
