### ISSUE TITLE
Governance LCD improvements

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1332]
We need usable governance endpoints. Therefor we need to evaluate the endpoints and improve them if necessary.

Scope:
- Create list of requests / use cases for governance
- Check if LCD is good enough for those use cases
- Improve the LCD on the use cases that are not good enough

**Comment by NodeGuy** [comment]
Governance specification: https://github.com/cosmos/cosmos-sdk/tree/develop/docs/spec/governance

**Comment by fedekunze** [comment]
Imo the one that needs some improvement is `GET /gov/proposals`. It currently uses query parameters for `depositer` and `voter` that should be split into different endpoints.
