### ISSUE TITLE
Ledger support

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1338]
Support for ledger nano.

- [ ] Design user flow
- [x] Implement account creation
- [ ] Implement signing

**Comment by faboweb** [comment]
Needs to be implemented in #1339

**Comment by NodeGuy** [comment]
How about we close this because it's far off in the future?

**Comment by faboweb** [comment]
deal

**Comment by fedekunze** [comment]
Reopening as per discussion with @faboweb and @jleni and labeling `high priority`:

- [implementation](https://github.com/ZondaX/ledger-cosmos-js/blob/5f40c5568f244dd952dd27d4a8a391a59f64599d/src/ledger-app.js#L57) 
- [unit test integration](https://github.com/ZondaX/ledger-cosmos-js/blob/5f40c5568f244dd952dd27d4a8a391a59f64599d/tests/tests-node.js#L37)

To Do:

1) Copy the logic of unit test on voyager 
2) Add 2 cmds more [here](https://github.com/ZondaX/ledger-cosmos-js/blob/5f40c5568f244dd952dd27d4a8a391a59f64599d/src/ledger-app.js#L72)

**Comment by faboweb** [comment]
Let's spike first if this works.

**Comment by jleni** [comment]
You can use the provided library (ledger-cosmos-js) as a reference. That has unit tests to show how to get app version, etc. It should work both on backend/frontend.
