### ISSUE TITLE
Amino JS

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1340]
To be able to sign messages (and later use lite client proofs to verify data) from within the browser and not rely on the gaia binary we need an amino (serializer/deserializer based on protobuf) version in JS. There is already an implementation we can use:
https://github.com/irisnet/irisnet-crypto/blob/master/chains/iris/amino.js

Scope:
- [ ] serialize all messages with amino-js (in lcdClient.js)

**Comment by jbibla** [comment]
if we are going to depend on third party libraries - we need to make sure the standards are high enough for our product and that they intend to continue to maintain and develop this software. or we can fork it and take care of it ourselves.

**Comment by faboweb** [comment]
I vote for forking and merging back to them. I suppose our fork will have a higher standard anyway and they will use ours in the future. :)

**Comment by siman** [comment]
Hi guys, I am developing TM ABCI dapp in Node.js and also need this js-amino. What is the status of this lib? Is it good/ready to use?

**Comment by faboweb** [comment]
Current state of amino.js https://github.com/irisnet/irisnet-crypto/blob/master/chains/iris/amino.js

**Comment by NodeGuy** [comment]
We don't have experience with it yet.

**Comment by faboweb** [comment]
Won't do
