### ISSUE TITLE
console_error_throw.js obscures failing unit tests

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1344]
would be nice to remove this so you can debug broken tests more easily.

**Comment by faboweb** [comment]
You can comment the code out to get the errors. The file prevents tests from passing in several cases that the code fails but the error isn't caught by the tests.

**Comment by NodeGuy** [comment]
I find myself commenting the code out every time I work on a PR these days because they obscure the source of errors.  Can we fix something elsewhere so we don't need these anymore?

**Comment by faboweb** [comment]
Let's spike it.

**Comment by faboweb** [comment]
I assume the title is wrong. The file is only imported in unit tests. Therefor it should not influence e2e tests.

**Comment by jbibla** [comment]
> You can comment the code out to get the errors.

yeahhhh - but errors are exactly what you need when tests are failing.

**Comment by faboweb** [comment]
> The file prevents tests from passing in several cases that the code fails but the error isn't caught by the tests.

I am open to alternative solutions.

**Comment by jbibla** [comment]
that seems odd. do you have any examples?

**Comment by NodeGuy** [comment]
This might be a better approach to handling the problem: https://vuejs.org/v2/api/#errorHandler

**Comment by faboweb** [comment]
> @faboweb Is this the original motivation for the code? vuejs/vue-test-utils#704

As far as I remember that and issues where `commit`s and `dispatch`es to the store would have types that do not exist in the store. So "integration" errors.
Plus asynchronous errors not caught by our code.

> This might be a better approach to handling the problem: https://vuejs.org/v2/api/#errorHandler

Great idea, let's try this.
