### ISSUE TITLE
Migrate to HTTPS-enabled LCD

### ISSUE THREAD

**Issue by alessio** [cosmos/voyager#1346]
Since `gaiacli 0.24.2-424-ge2da4caa` the REST server now serves requests via HTTPS by default.
Please introduce HTTPS support.

**Comment by fedekunze** [comment]
Thanks @alessio !

**Comment by NodeGuy** [comment]
What's blocking this?  Please include an explanation whenever you add the `blocked` label.

**Comment by faboweb** [comment]
We probably blocked this together in our team meeting last week. Feel free to add notes. ;) I assume this is blocked because we currently can't easily migrate to the latest develop of the SDK as we would loose compatibility with the testnet.
We may unblock this if we start using a staging branch.

**Comment by NodeGuy** [comment]
OK, blocked because we're waiting for the new SDK release to incorporate this feature.

**Comment by faboweb** [comment]
Timeboxed 2 days

**Comment by faboweb** [comment]
Scope:
- [ ] get https certificate data from console output when starting the lcd
- [ ] pass https certificate data to view process
- [ ] enable secure connection between view process and lcd (in lcdClient)

**Comment by NodeGuy** [comment]
Blocked by https://github.com/cosmos/cosmos-sdk/issues/2664.

**Comment by faboweb** [comment]
@NodeGuy this apparently is fixed on latest.
You could use my branch for testing: #1515

**Comment by NodeGuy** [comment]
Blocked until your branch is merged.

**Comment by faboweb** [comment]
My branch is dependent on your tests. ;)

**Comment by NodeGuy** [comment]
We decided to merge our PRs so this is no longer blocked.

**Comment by faboweb** [comment]
Done
