### ISSUE TITLE
Show commission earned

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#135]
I as a user
Want to see the amount of commission I earned
So that I stay engaged in holding atoms.

AC:
- [ ] a user should be able to see how many rewards they have been issued from each validator they have delegated to
- [ ] a user should be able to see a sum of the total rewards he has in all validators
- [ ] rewards should update in the UI as they update

See following event for updates on rewards (taken from https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/distribution/state.md):

dependencies: #209

**Comment by jolesbi** [comment]
delegators don't earn commissions. technically, they are issued "fee shares" for staking their Atom's.

a user will want to see how many fee shares they have been issued and this will need to be calculated on the client and stored locally. the math can be found in the [gaia repo spec](https://github.com/cosmos/gaia/pull/33). 

it is possible to query for this data in the event that there is a bug or the data is erased or disappears for any reason but we should be storing it locally as well by default. 

yo @rigelrozanski how'd i do? ✌️

**Comment by rigelrozanski** [comment]
Yes - each delegator receives fees shares, and are encouraged to withdraw their fee reward with a reasonable frequency. When withdrawing fees all fee shares they have accumulated must be withdrawn at once (backend requirement). Note that this is totally different from withdrawing atom provisions which are by default bonded, meaning that to withdraw them they must be unbonded. @jolesbi you did well - next thing you need to do is dig up the math from the spec! hehe I can help with this if you get stuck, there is a lot in there.

**Comment by NodeGuy** [comment]
> next thing you need to do is dig up the math from the spec! hehe I can help with this if you get stuck, there is a lot in there.

Holy cow there's a lot in there, @rigelrozanski!  Thanks for your offer of help.  I see the `cosmos/gaia` repository is now deprecated in favor of `cosmos-sdk`.  Would you please point us to the relevant document within `cosmos-sdk` (I can't find it) and extract for us the formulas we need?

**Comment by rigelrozanski** [comment]
@NodeGuy - PR just being finalized now - you can look at everything in this dir. (https://github.com/cosmos/cosmos-sdk/tree/rigel/piggy-bank-fee-spec/docs/spec/distribution) 

*note don't bother looking in the WIP folder - that's a more complicated mechanism which will not be implemented for a while

**Comment by rigelrozanski** [comment]
@NodeGuy PR is now merged - https://github.com/cosmos/cosmos-sdk/tree/develop/docs/spec/distribution

**Comment by NodeGuy** [comment]
Thank you.  Blocked by #1285.

**Comment by fedekunze** [comment]
see comments on #2010
