### ISSUE TITLE
Remove coloring of validator properties

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1356]
Remove the color indicators i.e. on commission. This will be part of staking 2.

**Comment by fedekunze** [comment]
do you want to remove only commission or all of them ?

**Comment by faboweb** [comment]
All of them.

Federico Kunze <notifications@github.com> schrieb am Di., 25. Sep. 2018,
15:43:

**Comment by fedekunze** [comment]
Closed via #1327
