### ISSUE TITLE
Reimplement PageValidator as a nested route.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1358]
Clicking on a validator hides the `My Stakes` and `Validators` tabs.  Keep the tabs visible (as in [the design](https://app.zeplin.io/project/59e66beff6721ea8bf562e5b/screen/5b8556a1cc45e20883c50006)) by making PageValidator a nested route.

**Comment by jbibla** [comment]
relevant / maybe duplicated by #1382

**Comment by NodeGuy** [comment]
Blocked by #1382 according to conversation with @jbibla.

**Comment by jbibla** [comment]
upon further examination - i think this was implemented the best way possible already. 

I thought that aiming to use child routes without a redirect would be the more correct approach - and it might be - but this is better for our use case with tabs where we need to pass in the path name as a prop.
