### ISSUE TITLE
Create separate process to display/capture seed words.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1359]
The seed words are the highest-value asset in Voyager.  See the [threat model](https://docs.google.com/document/d/1WOzU-518hsnScDvgbH6h8y2mb09LrzexTvUn7wISDZE/edit#heading=h.bb3n3onqnrxt).

![voyager processes](https://user-images.githubusercontent.com/2148537/46052419-5f73e800-c10c-11e8-893f-d1c99d1b36a3.png)

Create a new temporary process separate from the Renderer for temporarily opening a window to display or capture the seed words and send them to Gaia-Lite:

![three processes](https://user-images.githubusercontent.com/2148537/46053041-34d75e80-c10f-11e8-842c-fab84aacb885.png)

The new process should:

* depend on no modules (including Vue, etc.)
* employ hand-written HTML, CSS, and JavaScript
* be small so that it can be audited easily

**Comment by faboweb** [comment]
Sounds like a good idea. :)

**Comment by jbibla** [comment]
to clarify: 
- we are going to display a new window to the user that will _only_ contain their seed words. can this window contain a logo / image too?
- we will need to alter the design of the sign up session modal 

questions: 
- will the user / process be able to access the clipboard?
- will the user be able to access this window again? or is this a one time thing?
- we will need to alter the design of the recover-with-seed modal?

**Comment by faboweb** [comment]
> we are going to display a new window to the user that will only contain their seed words. can this window contain a logo / image too?

should be OK. in doubt we can inline the images as base64

> we will need to alter the design of the sign up session modal

yes

> will the user / process be able to access the clipboard?

better not. this is just attack surface.

> will the user be able to access this window again? or is this a one time thing?

one time thing

> we will need to alter the design of the recover-with-seed modal?

I guess we will need to have the same process for seed recovery, yes.

**Comment by NodeGuy** [comment]
Let's spike this first.

**Comment by NodeGuy** [comment]
I'm going to use the existing CSS from Voyager because otherwise this would be too much work.

**Comment by jbibla** [comment]
we're not going to implement this in the browser for the foreseeable future. will close for now.
