### ISSUE TITLE
General Language Improvements

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1365]
The validators on the my stake page are not unstaked, they are currently unstaking.

![image](https://user-images.githubusercontent.com/5869273/46092551-64d93d00-c1b5-11e8-8323-ea73b0505ba5.png)

**Comment by jbibla** [comment]
i think we're going with `unbonded` @fedekunze @rigelrozanski is that correct?

so maybe a good title would be `Currently Undbonding` - these should likely also show the dates 📅

**Comment by rigelrozanski** [comment]
Validators tokens' can be `bonded`, `unbonding`, or `unbonded` - delegators tokens can be `delegated` or `undelegated` in ADDITION to being `bonded`, `unbonding`, or `unbonded`

**Comment by jbibla** [comment]
@rigelrozanski should we avoid calling this the `Staking` section or the `My Stake` tab?

**Comment by rigelrozanski** [comment]
IMO I would remove all reference to the word "stake" in the UI - I find it confusing - alternatively (IMO less desirable) we could remove absolutely all reference to the word `bond` and replace it with `stake` (aka we would now use `staked`, `unstaking`, or `unstaked`) - I don't we we should do the latter

**Comment by rigelrozanski** [comment]
side thought - I wonder if we should rename the staking module _bondage_ - it's kinda confusing because the module deals with both bonding and delegations - not sure... maybe this should still be the one use case for the word staking; _ the system of bonding and delegating_

**Comment by faboweb** [comment]
> I wonder if we should rename the staking module to bondage

Let's not go there. This will be weird for developers. And we don't want to be seen as weird, we want to show trust in our code and in our platform.

**Comment by NodeGuy** [comment]
We agreed in the meeting to change the header to `Undelegating Validators` in `staking1`.

**Comment by rigelrozanski** [comment]
@NodeGuy (CC @faboweb @jbibla ) 

That doesn't make any sense!!! - please refer to my original language discussions - https://github.com/cosmos/voyager/issues/1283#issuecomment-425148848

The validator object doesn't delegate whatsoever (however the operator of the validator _does_ have a self-delegation) - there are a number of different situations which will cause the validator's tokens to move from the `bonded` state to an `unbonding` state - the most correct term to use to describe what you are getting at is `unbonding validator`

**Comment by faboweb** [comment]
We want to avoid the use of the word `bonding` to not confuse users. Anyway `undelegating validator` is temporary and will be replaced by `undelgation transactions`.

**Comment by jbibla** [comment]
takeaways from the call with @faboweb and @rigelrozanski :

*General*
- [ ] not going to use Bonding, Bonded, Unbonding (the B words) to communicate token state. instead we will imply this with the action words - Delegation and associated terms

*TmBalance*
- [ ] change "Unbonded" to "Available"

*LiValidator and PageValidator*
- [ ] display three status' / states (Active, Jailed, Inactive) 

*My Delegations Tab*
- [ ] “Bonded Steak” filter is technically innaccurate - replace with "Delegated Steak"
- [ ] display two lists: "Active Delegations" and "Inactive Delegations"

**Comment by jbibla** [comment]
thank you for the time and ideas!

this is being tracked separately #1378.

**Comment by NodeGuy** [comment]
Thank you, @jbibla.  Would you please put that somewhere that's easy to find, like a Google Doc?  I imagine we're going to need to reference it frequently in the future.

**Comment by faboweb** [comment]
Great idea

**Comment by rigelrozanski** [comment]
May I suggest a docs section in the voyager repo to house the most updated language decisions/discussions?
