### ISSUE TITLE
Show all decimals for amounts

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1366]
Description:

~Show only 2 decimals~ (JB EDIT - SHOW ALL DECIMALS)

<img width="905" alt="screen shot 2018-09-26 at 6 42 25 pm" src="https://user-images.githubusercontent.com/31522760/46095143-12e7e580-c1bc-11e8-9413-1826060a7f31.png">

**Comment by jbibla** [comment]
are we sure we're going with 2 decimals? regardless, it should always be consistent!

**Comment by jbibla** [comment]
i think we need to make a final decision on how many decimals we will show or if we need a design / mechanism like we have for bech32 addresses. 

then we should make sure this is consistent across the app.

**Comment by faboweb** [comment]
Do you have a proposal for a design standard?

**Comment by jbibla** [comment]
i suppose we need to show the full length of the decimal. we will have to change the font size for everything after the decimal and or the whole number.

**Comment by faboweb** [comment]
I like the idea of showing decimals in small.

**Comment by faboweb** [comment]
Decision: We show all decimals but try to style it a little.
