### ISSUE TITLE
Bonded validator error when bondedAtoms < 1

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1369]
Description:

I bonded to a validator which I have 0 < steak < 1 bonded due to slashes showing that `My Stake` is `NaN`:

```
committedDelegations{
        cosmosaccaddr18thamkhnj9wz8pa4nhnp9rldprgant57ryzag7:  4.7e-9
...
}
```

<img width="929" alt="screen shot 2018-09-27 at 7 14 16 pm" src="https://user-images.githubusercontent.com/31522760/46163035-51e46c80-c28a-11e8-8ab0-5c4b73ac966d.png">

**Discussion**: 

What should we do with the leftover bonded atoms ?

**Comment by faboweb** [comment]
On the validator page, I showed `< 0.01`. Would that be sufficient?

**Comment by fedekunze** [comment]
yeah but the thing is that you can't do anything with `< 0.01`, not even with < 1

**Comment by fedekunze** [comment]
I remember that we discussed to not be able to redelegate if the bonded amount was < 1

**Comment by faboweb** [comment]
You can undelegate and redelegate < 1 token (because we are undelegating and redelegating shares not tokens) but you can't delegate < 1 token. This is how it is currently implemented in the SDK.
We could be hiding validators with < 1 token delegation and hide decimals completely. This would already implement future SDK changes.

**Comment by fedekunze** [comment]
> You can undelegate and redelegate < 1 token (because we are undelegating and redelegating shares not tokens)

ohh, I thought you were also talking about redelegation when you mentioned about not allowing users to put decimals on the `ModalStake` amount input.

We'll have to add a condition then on the submission button depending if it's delegation or redelegation to check those cases, change the input `step` and add some tests.

**Comment by faboweb** [comment]
Maybe this is all to complicated. Let's discuss in the Tuesday meeting.

**Comment by NodeGuy** [comment]
What did we decide in the meeting?

**Comment by faboweb** [comment]
We can't hide tokens for now. So we go with the `< 0.01` term. This may already be solved.

**Comment by fedekunze** [comment]
Fixed on develop
