### ISSUE TITLE
improve error handling in tests

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1373]
As far as I remember that and issues where `commit`s and `dispatch`es to the store would have types that do not exist in the store. So "integration" errors.
Plus asynchronous errors not caught by our code.

> This might be a better approach to handling the problem: https://vuejs.org/v2/api/#errorHandler

Great idea, let's try this.

_Originally posted by @faboweb in https://github.com/cosmos/voyager/issues/1344#issuecomment-425378688_

**Comment by faboweb** [comment]
@jbibla can you please format the issue so it is readable.

**Comment by faboweb** [comment]
Is this done with #1542 ?

**Comment by jbibla** [comment]
yeah looks like it's being used in main.js - what is guru meditation lol?

**Comment by faboweb** [comment]
https://de.wikipedia.org/wiki/Guru_Meditation
