### ISSUE TITLE
Steak is now called STAKE

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1378]
find and replace `steak` with `stake`

**Comment by faboweb** [comment]
This is blocked until the staking denom of the network actually says `stake`.

**Comment by fedekunze** [comment]
@faboweb I think @jbibla refers to the mocked LCD mostly, since we can get the testnet bonding denom from staking `params`. So technically it's not blocked

**Comment by faboweb** [comment]
If we change this, the staking denom we manually set will mostly say `stake` but in the wallet it will still show the actual denom `steak`.

**Comment by jbibla** [comment]
when we release voyager for gaia-9000 - `steak` should no longer exist. in the mocked LCD and in the UI i suppose.

**Comment by faboweb** [comment]
unblocking this as our next release will not be before gaia-9000

**Comment by faboweb** [comment]
Can we make it both `stakes`?

**Comment by zmanian** [comment]
I would need get @greg-szabo  to sign the `gen-txs` again.

I need to figure out how to get the validator bonding txs to be in `stake` before GoS but I don't want to block 9000 on it.

**Comment by greg-szabo** [comment]
I ran the `testnet` command, apparently it's not reset there?

**Comment by zmanian** [comment]
Depends on https://github.com/cosmos/cosmos-sdk/pull/2752/files

**Comment by faboweb** [comment]
Doesn't work with SDK version 0.26.1. It still requires the staking denom to be "steak".
