### ISSUE TITLE
move tabs into balance header

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1382]
the way we have tabs implemented is as follows (after the refactor):
```
{
    path: `/staking`,
    name: `staking`,
    component: staking(`Staking`),
    redirect: `/staking/my-delegations/`,
    children: [
      {
        path: `my-delegations`,
        name: `My Delegations`,
        component: require(`./components/staking/TabMyDelegations`).default
      },
      {
        path: `Validators`,
        name: `Validators`,
        component: require(`./components/staking/TabValidators`).default
      }
    ]
  },
```

you'll notice that we're using a redirect to move users from `/staking` to `/staking/my-delegations` - i'd like to propose that we use the `<router-view>` element in the template and remove the need for a redirect as documented in the [vue-router documentation](https://router.vuejs.org/guide/essentials/nested-routes.html). 

additionally, i'd propose that we drop the naming convention of `TabMyDelegations` and instead stick with `PageMyDelegations` or take this one step further and drop the concept of `Page` altogether ...  just name the files `MyDelegations` and `ValidatorIndex` respectively.

**Comment by faboweb** [comment]
> you'll notice that we're using a redirect to move users from /staking to /staking/my-delegations - i'd like to propose that we use the <router-view> element in the template and remove the need for a redirect as documented in the vue-router documentation.

👍 

> additionally, i'd propose that we drop the naming convention of TabMyDelegations and instead stick with PageMyDelegations or take this one step further and drop the concept of Page altogether ... just name the files MyDelegations and ValidatorIndex respectively.

I would stick with a prefix. I think this helps to easily get that the component is a page. The extra letters do not hurt imo. I am also not 100% sure to drop the `Tab` prefix. Pages have headers, Tabs do not have headers as far as I know.

**Comment by NodeGuy** [comment]
Do you mean you want `/staking` to represent the `My Delegations` tab and `staking/Validators` to represent the `Validators` tab?

**Comment by NodeGuy** [comment]
URLs can include uppercase letters and spaces: https://tools.ietf.org/html/rfc1738

I'd prefer not to have an extra layer of translation, e.g., using `My Delegations` as the URL for `My Delegations` is more clear to me than `my-delegations`.

**Comment by jbibla** [comment]
will rename this issue and use #1382 for addressing the tabs
