### ISSUE TITLE
Reconsider use of tape-promise for E2E tests.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1384]
[tape-promise currently doesn't have proper support for t.test()](https://github.com/jprichardson/tape-promise/issues/17#issuecomment-425276035)

We are using `t.test()` with it so we should fix tape-promise to support `t.test()` properly, stop using `t.test()`, or stop using tape-promise.

**Comment by faboweb** [comment]
👍
what would you propose? switching to jest to be uniform in the project?

**Comment by NodeGuy** [comment]
I vote for switching to Jest.

**Comment by faboweb** [comment]
Closing in favor of https://github.com/cosmos/voyager/issues/1395
