### ISSUE TITLE
user onboarding improvements

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1386]
from hugh and jb #1117 

- [x] says tokens, then atoms - inconsistent
- [x] only concerned with atoms, then when you login there are 3 tokens? - confusing
- [x] tutorial should have back button (JB)
- [x] tutorial progress indicators are not visible enough (JB)
- [x] update voting image

**Comment by fedekunze** [comment]
I think we should do this on the 2 weeks prior to voyager launch

**Comment by jbibla** [comment]
sure! will do!
