### ISSUE TITLE
display the unbonding tx in the "Unstaked Validators" list instead of the validator Li

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1387]
Split from https://github.com/cosmos/voyager/issues/1364#issuecomment-425074861.

![46092551-64d93d00-c1b5-11e8-8323-ea73b0505ba5](https://user-images.githubusercontent.com/2148537/46308914-e56ab580-c588-11e8-9743-f00332f810f4.png)

**Comment by sabau** [comment]
Just to be sure: should we fetch the transactions related to unbounding or it's enough to show the data coming from `/stake/delegators/{addr}/unbonding_delegations`

```
[
  {
    "balance": {
      "amount": "3",
      "denom": "steak"
    },
    "creation_height": "1379",
    "delegator_addr": "cosmos1ccwqds0dd6cxp44a7rpc6kscm7zj6jdcykaeut",
    "initial_balance": {
      "amount": "3",
      "denom": "steak"
    },
    "min_time": "2018-12-14T15:02:05.203889Z",
    "validator_addr": "cosmosvaloper1ccwqds0dd6cxp44a7rpc6kscm7zj6jdcpzfvsc"
  }
]
```

**Comment by faboweb** [comment]
Maybe also add redelegations as undelegations?

**Comment by sabau** [comment]
As for now it seems we can't have more than an unbounding transaction per validator: "existing unbonding delegation found"

@cwgoes if I understood you are on this right?

**Comment by cwgoes** [comment]
> If I understood you are on this right?

Yes. Working on some changes to fee distribution first but hopefully multiple unbonding delegations per validator should come long in a week or two - tracking issue here: https://github.com/cosmos/cosmos-sdk/issues/1402
