### ISSUE TITLE
remove TmPage

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1391]
`TmPage` is a small component that doesn't add a lot of value. we no longer have `h2` and `h3` on each `Page` - and I think our code will be simpler and cleaner if we just include the necessary components on each page. 

```
.tm-page
  tm-page-header
    h2(v-if="title", slot='title') {{ title }}
    h3(v-if="subtitle", slot='subtitle') {{ subtitle }}
    template(slot='menu-body'): slot(name="menu-body")
    div(slot="menu"): slot(name="menu")
  main.tm-page-main: slot
```

**Comment by fedekunze** [comment]
removing TmPage causes #1522 's E2E tests to fail

**Comment by jbibla** [comment]
well, it depends on the page - but i don't think we need h2, h3, or any slots ... so instead of passing in everything to `TmPage` just remove the component and add whatever is needed for the page to render the same way... does that make sense?

**Comment by jbibla** [comment]
i agree with closing this, but please include a note about why @faboweb
