### ISSUE TITLE
PageValidator Bonded stake ≠ than the one displayed in LiValidator

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1397]
Description:

The bonded tokens displayed are different

PageValidator: 

<img width="1046" alt="screen shot 2018-10-02 at 1 27 53 pm" src="https://user-images.githubusercontent.com/31522760/46346265-c4b56500-c647-11e8-96fa-d7f52e76b820.png">

LiValidator:

<img width="1039" alt="screen shot 2018-10-02 at 1 34 32 pm" src="https://user-images.githubusercontent.com/31522760/46346329-f4646d00-c647-11e8-9152-24131f4605c6.png">

**Comment by faboweb** [comment]
PageValidator still shows shares. I think this is fixed in my PR.

**Comment by fedekunze** [comment]
@faboweb Saw that, added a comment on https://github.com/cosmos/voyager/pull/1367#pullrequestreview-160682044
