### ISSUE TITLE
minor style updates

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1411]
and some other clean up items like

- use the correct font-family (sf pro text / sf pro display)
- address redundant headers
- notification background color

**Comment by jbibla** [comment]
these issues have been addressed or will be addressed in other tickets.

**Comment by faboweb** [comment]
we don't use sf pro anymore I thought @nylira

**Comment by jbibla** [comment]
this is true. i haven't started using ubuntu in voyager yet.

**Comment by faboweb** [comment]
ok my bad
