### ISSUE TITLE
Include Feedback section on Preferences

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1421]
Description:

I'd be nice to have a feedback form accessible _within_ voyager to provide feedback about the app which sends the comments to our dev team. The current way to do it is to click on Help and then open an issue manually

**Comment by jbibla** [comment]
would be cool if on form submission a bot created a github issue for us with the feedback. this is easy to do with zapier.

**Comment by faboweb** [comment]
Pulling in @nylira for some ideas you had.

**Comment by faboweb** [comment]
Check complexity first

**Comment by jbibla** [comment]
... and proceed in next feature focussed sprint
