### ISSUE TITLE
Onboarding niggles

### ISSUE THREAD

**Issue by ricburton** [cosmos/voyager#1423]
UI Version: 0.10.6

Amazing progress since I last checked in!

Some tiny onboarding niggles:

My original seed phrase didn’t work. Was there a breaking change there?
<img width="174" alt="screen shot 2018-10-06 at 12 28 29 pm" src="https://user-images.githubusercontent.com/438160/46570880-592f0880-c963-11e8-898c-46b9dc91f5db.png">

When bonding, the modal is off-center on my screen:

![screen shot 2018-10-06 at 12 23 45 pm](https://user-images.githubusercontent.com/438160/46570881-5e8c5300-c963-11e8-9e4e-e0b595db7a40.png)

Would be sweet if this modal popped up the instant I delegate with "pending" before "success". I was left wondering what was happening for a little while:

![screen shot 2018-10-06 at 12 24 07 pm](https://user-images.githubusercontent.com/438160/46570888-88457a00-c963-11e8-9521-fbeb8d3330ce.png)

After delegating, I don’t see the validator I just delegated to in the list. Does it take some time to process?:

![screen shot 2018-10-06 at 12 24 32 pm](https://user-images.githubusercontent.com/438160/46570893-9e533a80-c963-11e8-8db7-f7bcd869819d.png)

Since everyone has 0, I’m guessing it’s not running or live now.

Great work everyone. 👍

**Comment by jbibla** [comment]
> Amazing progress since I last checked in!

thank you for the feedback @ricburton ! means a lot! 

> My original seed phrase didn’t work. Was there a breaking change there?

good question. we'll investigate. @faboweb @NodeGuy do you happen to know?

> When bonding, the modal is off-center on my screen:

that's on purpose 🤣 a la Google Inbox. i guess we need to make it seem more like it's on purpose 😛 

> Would be sweet if this modal popped up the instant I delegate with "pending" before "success". I was left wondering what was happening for a little while:

i absolutely agree. we are actively improving the transitions and the ux between hitting submit and confirming the transactions are going through. will be part of implementing #1284. we don't want to leave anyone wondering 👍 

> After delegating, I don’t see the validator I just delegated to in the list. Does it take some time to process?

i'll investigate.

--- 

stay tuned for the new transaction history and governance features coming soon. as always, we really do appreciate the feedback!!

**Comment by fedekunze** [comment]
Thanks for the feedback @ricburton ! 

> Would be sweet if this modal popped up the instant I delegate with "pending" before "success". I was left wondering what was happening for a little while:

Yeah, I've run into this issue before and agree that should fix it. I'm curious though why does it take so long to show the notification... We'll look into it

**Comment by faboweb** [comment]
> My original seed phrase didn’t work. Was there a breaking change there?

Yes, we changed the seed phrase structure. I think it was 12 words and now it is 24 words.

**Comment by faboweb** [comment]
Closing this issue as all the feedback has been incorporated in individual issues. Thank you again.
