### ISSUE TITLE
Integrate Tendermint UI library

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1432]
We decided to fuse https://github.com/tendermint/ui into this repository.

Scope:
- [ ] implement decisions out of #1430

**Comment by fedekunze** [comment]
I think we should add some folders to the `common` as well in order to categorize better the TmUI components. `common` is currently very packed with components

**Comment by jbibla** [comment]
good thinking @fedekunze - i would propose including a folder for `session` and for `modals`. are there others you can think of?

**Comment by fedekunze** [comment]
https://www.notion.so/cosmosvoyager/Repository-Architecture-408ed911bc524d37b05ab562be78baf7

**Comment by faboweb** [comment]
> do we need to still use the Tm prefix

not really

**Comment by faboweb** [comment]
How about making "session" an own folder: "components/session"?
