### ISSUE TITLE
Migrate to latest SDK develop

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1433]
In order to start on governance we should migrate to the latest SDK code.

Concerns:
- [ ] we will probably not be able to connect to gaia-8001 after

**Comment by faboweb** [comment]
Maybe create a `hotfixes` branch for bugs on the old network.

**Comment by NodeGuy** [comment]
Hmm, I wonder if we can do better here.  Possibilities:

* monorepo with SDK & Voyager
* coordinated release cadence:
  1. SDK release (0 weeks)
  1. New testnet is launched from SDK release (2 weeks)
  1. Voyager publishes release that works with new testnet (4 weeks)
  1.  Repeat.

**Comment by jbibla** [comment]
> Maybe create a hotfixes branch for bugs on the old network.

perhaps we should try a feature branch for new SDK + governance. we can merge into develop and release when the testnet is up.
