### ISSUE TITLE
measure attack surface of dependencies

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1435]
89% of our code is from modules:

```
$ npx @intrinsic/loc

_)      |       _)         _)      
 | __ \ __|  __| | __ \ __| |  __| 
 | |  | |   |    | |  |\__\ | (    
_|_| _|\__|_|   _|_| _|___/_|\___| 


Your application code:    229,406 lines (10.88%) 
  `node_modules` code:  1,878,195 lines (89.12%)
```

Find a way to generate statistics about the modules so that we can measure a cost/benefit ratio for each one where the cost is the lines of code (or bytes) of code in the module (and all of its dependencies), and the benefit is a metric of how often it's used in Voyager.  This will enable us to identify and to prune modules providing the least benefit for the greatest cost.

**Comment by jbibla** [comment]
> 229,406 lines

woah

**Comment by faboweb** [comment]
#ui-development ;D

**Comment by NodeGuy** [comment]
#ui-development?

**Comment by NodeGuy** [comment]
Oh sure, now I understand what you mean.  Yes, I agree.

**Comment by fedekunze** [comment]
Moved to #2233
