### ISSUE TITLE
Refactor ShortAddress

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1437]
Currently the component handles other formats that are not bech32. I don't hink we need this and it also hides wrong addresses.
Additionally we want to rename ShortAddress to ShortBech32.

**Comment by jbibla** [comment]
thanks for making this ticket.

**Comment by jbibla** [comment]
curious, in the spirit of small focussed components - should verification / validation be a part of it at all?

**Comment by faboweb** [comment]
if not, then we should expect bech32 and remove all exceeding code

**Comment by NodeGuy** [comment]
> curious, in the spirit of small focussed components - should verification / validation be a part of it at all?

Yes, you can never have too much of this (with rare exceptions).
