### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\hideki\.cosmos-voyager\mock\genesis.json'

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1438]
https://sentry.io/tendermint/cosmos-voyager/issues/720197105/

```
Error: ENOENT: no such file or directory, open 'C:\Users\hideki\.cosmos-voyager\mock\genesis.json'
  at None (/C:/Users/hideki/.cosmos-voyager/resources/app/dist/index.html)
```

**Comment by NodeGuy** [comment]
The first problem is `TypeError: Cannot read property 'destroy' of undefined` at 07:12:12.

**Comment by NodeGuy** [comment]
Closing because this is a cascading error after https://github.com/cosmos/voyager/issues/1440.
