### ISSUE TITLE
tx components should display all the decimals

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1442]
use `num.full()`

blocked by #1432

**Comment by fedekunze** [comment]
I don't think this is completely blocked if you use `yarn link`

**Comment by faboweb** [comment]
All the components? What about the balance header?

**Comment by jbibla** [comment]
transaction components

**Comment by faboweb** [comment]
> this was about transaction components.

my bad

**Comment by fedekunze** [comment]
<img width="1408" alt="screen shot 2019-03-05 at 10 31 43 am" src="https://user-images.githubusercontent.com/31522760/53818157-ef457a00-3f67-11e9-827f-c4f0979e557c.png">

no scientific notation plz

**Comment by jbibla** [comment]
lol yes, for sure. why is that happening?

**Comment by fedekunze** [comment]
🤷‍♂️

**Comment by faboweb** [comment]
This looks like a JS issue "adding a number and a string".
There shouldn't be values in Cosmos that are that small.

**Comment by fedekunze** [comment]
It’s actually BN, we have to parse it to string before displaying it

**Comment by fedekunze** [comment]
fixed on develop
