### ISSUE TITLE
running jest <FileName> doesn't update code cov when running yarn test:coverage

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1444]
this would be nice for my workflow 😄 

running `yarn test:unit` updates the code cov at `http://127.0.0.1:8080` but `jest FileName` doesn't.

using the `refactor` label because its the closest thing to a `developer` label.

**Comment by faboweb** [comment]
`jest fileX` only updates the coverage for `fileX` and imports for that file. The website for the coverage is newly written every time. The problem: the navigation changes. You may nee to go back to http://127.0.0.1:8080 and navigate to your file from there. Can you try again?

**Comment by faboweb** [comment]
ping @jbibla

**Comment by jbibla** [comment]
we can close for now.
