### ISSUE TITLE
Bonded stake value is too long on LiValidator

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1449]
UI Version: 0.10.6

Description:

![image](https://user-images.githubusercontent.com/5869273/46737937-20619d00-cc9d-11e8-940f-09777f380a31.png)

**Comment by NodeGuy** [comment]
What should happen instead here?

**Comment by faboweb** [comment]
Either shorten the value, increase the size of the field or come up with a different design where tokens have a lote more space. Do you have any idea?

**Comment by fedekunze** [comment]
lol I raised this issue on the PR review

**Comment by jbibla** [comment]
aw 😭 sorry guys.

**Comment by NodeGuy** [comment]
In this case I think it's appropriate to round the amount.

**Comment by jbibla** [comment]
i've been thinking lately that we should round to 4 decimal places everywhere but show full decimals in all form fields for making accurate transactions.
