### ISSUE TITLE
Staking wording updates

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1454]
*General*
- [x] not going to use Bonding, Bonded, Unbonding (the B words) to communicate token state. instead we will imply this with the action words - Delegation and associated terms

*TmBalance*
- [x] change "Unbonded" to "Available"

*LiValidator and PageValidator*
- [x] display three status' / states (Active, Jailed, Inactive) 

*My Delegations Tab*
- [x] “Bonded Steak” filter is technically innaccurate - replace with "Delegated Steak"
- [x] display two lists: "Active Delegations" and "Inactive Delegations"

_Originally posted by @jbibla in https://github.com/cosmos/voyager/issues/1365#issuecomment-428295701_

- [ ] persist these decisions in a `.md` file in the repository

**Comment by jbibla** [comment]
> persist these decisions in a .md file in the repository

not sure what the purpose of moving this issue into an md file would be.

**Comment by NodeGuy** [comment]
> not sure what the purpose of moving this issue into an md file would be.

Remembering that this is open source and a basis for future projects, it would be helpful and easy-to-find guidance for consistent terminology.
