### ISSUE TITLE
Voyager ran into an error

### ISSUE THREAD

**Issue by wannabit-mina** [cosmos/voyager#1457]
UI Version: 0.10.7

Description:
I got this error after "yarn start".

"Voyager ran into an error
spawn /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli ENOENT"

I am on a Ubuntu 18.04.1 LTS..

Thu Oct 11 2018 16:02:08 GMT+0900 (KST) Running Cosmos-UI
main-process: initializing data directory (/home/minachoi/.cosmos-voyager-dev/gaia-8001)
main-process: spawning /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli with args ""version""
main-process: [Uncaught Exception] Child gaiacli produced an unhandled exception: Error: spawn /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli ENOENT
main-process: View has booted
Thu Oct 11 2018 16:13:27 GMT+0900 (KST) Running Cosmos-UI
main-process: root exists (/home/minachoi/.cosmos-voyager-dev/gaia-8001)
main-process: configs are compatible with current app version
main-process: spawning /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli with args ""version""
main-process: [Uncaught Exception] Child gaiacli produced an unhandled exception: Error: spawn /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli ENOENT
main-process: View has booted
Thu Oct 11 2018 16:28:07 GMT+0900 (KST) Running Cosmos-UI
main-process: root exists (/home/minachoi/.cosmos-voyager-dev/gaia-8001)
main-process: configs are compatible with current app version
main-process: spawning /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli with args ""version""
main-process: [Uncaught Exception] Child gaiacli produced an unhandled exception: Error: spawn /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli ENOENT
main-process: View has booted
Thu Oct 11 2018 16:44:00 GMT+0900 (KST) Running Cosmos-UI
main-process: root exists (/home/minachoi/.cosmos-voyager-dev/gaia-8001)
main-process: configs are compatible with current app version
main-process: spawning /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli with args ""version""
main-process: [Uncaught Exception] Child gaiacli produced an unhandled exception: Error: spawn /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli ENOENT
main-process: View has booted

**Comment by faboweb** [comment]
There is no version `0.2.28`. Which version or commit are you on?
This error looks like yo didn't build gaia. Did you run `yarn build:gaia` prior to starting?

**Comment by wannabit-mina** [comment]
Sorry. I meant version 0.10.7
I already ran "yarn build:gaia" and "yarn build:testnets"

**Comment by faboweb** [comment]
did `yarn build:gaia` produce any error? does the file `/home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli` exist?

**Comment by wannabit-mina** [comment]
yes. 
> /home/minachoi/voyager/builds/gaia/linux_amd64/gaiacli
exist

**Comment by wannabit-mina** [comment]
first, I tried on windows but it didn't work properly: yarn build:gaia, yarn build:testnets

I checked voyager code ran properly on Mac.

I installed ubuntu on virtual box.
but I failed to run 'yarn start'

**Comment by faboweb** [comment]
Thank you for your feedback. I will investigate this further. Is running the development environment on Mac enough for you for now?

**Comment by faboweb** [comment]
Replicated the error. 👍

**Comment by faboweb** [comment]
Can you try the branch `fabo/1457-fix-gaia-not-found` ?

**Comment by wannabit-mina** [comment]
I tried the fixed version. 
now it finds Gaia but I have another error, same as #1461

in my case, the error is `Data was created with an incompatible app version data=0.10.7 app=0.8001.1`

**Comment by faboweb** [comment]
See #1461, sorry for the inconveniences

**Comment by faboweb** [comment]
Hey! which version are you running?

**Comment by giatom** [comment]
I am new to the space and I need just a wallet to which I can transfer your currency. I downloaded your wallet for Windows but it shows this error. What version should I download for storing your tokens?

**Comment by faboweb** [comment]
I just tested version 0.8001.1 on Windows and it worked. Could you try again?
The message states, that the file `\resources\app\bin\gaiacli.exe` is not available. Can you check if it there?

**Comment by giatom** [comment]
There is no file “bin”
![image](https://user-images.githubusercontent.com/44807448/48123643-8127c980-e28b-11e8-8557-b3bc892bc628.png)

**Comment by giatom** [comment]
Yes, my friend. I have downloaded once more but it still does not work.

**Comment by faboweb** [comment]
Can you try another unzipping tool?
Here is the content from that file:
![image](https://user-images.githubusercontent.com/5869273/48138145-edaec280-e2a3-11e8-9ff4-3335d969d8ff.png)

**Comment by giatom** [comment]
![image](https://user-images.githubusercontent.com/44807448/48139030-96661d80-e2b6-11e8-8068-5767a954d97f.png)

**Comment by giatom** [comment]
Did you download the version for Windows? Did you check it for the availability of bin?

**Comment by faboweb** [comment]
Yes, I downloaded the same version I linked here on Windows and Mac. I just unzipped it and the filesystem is as expected.

**Comment by NodeGuy** [comment]
Welcome, @giatom.

> I am new to the space and I need just a wallet to which I can transfer your currency.

Please be advised that this is alpha quality software and should not yet be relied upon to store anything of value.

**Comment by giatom** [comment]
I want to buy your tokens but I do not know where to store them. That's why I want to install your wallet. Or if there is another way to store them then, please, tell me.

**Comment by fedekunze** [comment]
@giatom Atoms are _not_ available or traded on exchanges yet. They will be allocated to fundraiser participants after mainnet launch. You will be able to retrieve your fundraiser allocations with your seed phrase through the Voyager interface. Token transfers, i.e. trading, won't be enabled until mainnet is stable in case a catastrophic bug causes the Cosmos Hub to perform a genesis rollback.

**Comment by giatom** [comment]
Ok, I have puzzled out the wallet and I succeeded in its installing on another computer.
Where and when can I buy your tokens?

**Comment by faboweb** [comment]
You currently can't buy the atom. I'm closing this issue as the initial problem is solved.
