### ISSUE TITLE
ERROR: Data was created with an incompatible app version data=0.10.2 app=0.8001.1

### ISSUE THREAD

**Issue by jim380** [cosmos/voyager#1461]
**UI Version:** 0.8001.1

**Description:** error upon launching: ```Data was created with an incompatible app version data=0.10.2 app=0.8001.1```
![photo_2018-10-11_14-21-56](https://user-images.githubusercontent.com/31609693/46834883-7f88e580-cd61-11e8-94d4-9ffd2a670f56.jpg)

**Log:** 
[main.log](https://github.com/cosmos/voyager/files/2470783/main.log)

**Comment by faboweb** [comment]
Thanks for filing this issue.
To solve this problem quickly change the content of `~/.cosmos-voyager[-dev]/gaia-8001/app_version` to `0.8001.1`.

**Comment by Wason1** [comment]
I just got this error

**Comment by faboweb** [comment]
> To solve this problem quickly change the content of ~/.cosmos-voyager[-dev]/gaia-8001/app_version to 0.8001.1.
