### ISSUE TITLE
Create LiTransaction for governance

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1464]
Description:

Required to display governance txs on the Transaction Page

- [x] TmUI Components
- [ ] Integrate to voyager wallet

**Comment by fedekunze** [comment]
@jbibla any idea of the colors we should use for each of the gov txs ?

**Comment by faboweb** [comment]
Do we 100% need this prelaunch?

**Comment by fedekunze** [comment]
imo it's required. It shouldn't take too much time

**Comment by jbibla** [comment]
re: colors - as long as they are the same for all governance txs we'll be fine!

**Comment by NodeGuy** [comment]
Blocked because waiting for new release of tendermint/ui to be published.

**Comment by faboweb** [comment]
published 0.3.1
