### ISSUE TITLE
Add badge with counter when displayed notification is repeated

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1468]
Description:

This is to avoid repeating notifications. Whenever a new notification is about to be displayed, check if it already exists and show [badge](https://getbootstrap.com/docs/4.1/components/badge/) with increased counter

**Comment by faboweb** [comment]
I like the idea. @jbibla had some ideas about not showing notifications at all, as far as I remember.

**Comment by jbibla** [comment]
it's true! we are abusing the notifications. 

https://github.com/cosmos/voyager/issues/1266#issuecomment-429463764

@fedekunze please provide an example of a notification that _should_ appear as they do now, and the situation where more than one should be displayed at a time.

😄
