### ISSUE TITLE
Voting power not available on "My Validators" page.

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1473]
Voting power always shows `n/a` on the `My Validators` page.

![image](https://user-images.githubusercontent.com/5869273/47076606-68357680-d1ff-11e8-8e6a-97521a301921.png)

**Comment by fedekunze** [comment]
yeah I added `n/a` when the validator is not on the active validator set I think

**Comment by faboweb** [comment]
My one validator should be in the set. ;)

**Comment by jbibla** [comment]
why `staking2`? this should work now!

**Comment by jbibla** [comment]
sounds like a `staking1` bug, not `staking2`

**Comment by NodeGuy** [comment]
Agreed.
