### ISSUE TITLE
Add local testnet script for new single node flow

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1474]
Currently a dev needs to overwrite the node urls by starting Voyager with `LCD_URL=http://localhost:9070 RPC_URL=http://localhost:26657 yarn start local-testnet`. I think we could add this as a script `yarn start:local` to make it more convenient.

**Comment by jbibla** [comment]
sounds reasonable. no discussion required.

**Comment by faboweb** [comment]
Done
