### ISSUE TITLE
Split delegator endpoint on lcdClient and lcdClientMock

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1489]
Description:

https://github.com/cosmos/cosmos-sdk/issues/2258 was merged so we will need to update these files and logic

**Comment by NodeGuy** [comment]
Please copy and paste the relevant information into this issue so that (ideally) the assigned developer won't have to reference the other one.

**Comment by fedekunze** [comment]
Blocked until we update sdk version

**Comment by jbibla** [comment]
@fedekunze please specify which version

**Comment by faboweb** [comment]
Done
