### ISSUE TITLE
sort by on validator table doesn't align with table columns

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1497]
<img width="930" alt="screen shot 2018-10-29 at 10 30 58 am" src="https://user-images.githubusercontent.com/6021933/47656590-c0f10180-db65-11e8-97fa-379fca030c54.png">

**Comment by NodeGuy** [comment]
How about we use a `TABLE` element?

**Comment by jbibla** [comment]
i would love to use a table element.
