### ISSUE TITLE
Unit tests produce errors and warnings but do not fail

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1509]
Warnings and errors should produce an exit code 1 to show the tests have failed.

**Comment by NodeGuy** [comment]
Can you provide any examples?

**Comment by faboweb** [comment]
i.e.
```
 PASS  test/unit/specs/store/store.spec.js
  ● Console

    console.error app/src/renderer/vuex/store.js:87
      Encrypting the state failed, removing cached state.
```

```
     [vue-router] missing param for named route "validator": Expected "validator" to be defined
    console.warn node_modules/vue-router/dist/vue-router.common.js:18
```

**Comment by NodeGuy** [comment]
Your first example (`Encrypting the state failed, removing cached state.`) is a result of expected behavior from a passing test.  The test is deliberately provoking the error message.

**Comment by faboweb** [comment]
Shouldn't then the `console.error` function be mocked out?

**Comment by NodeGuy** [comment]
That would be one way to approach it, yes.  I think a better design would be to throw an exception and let higher-level code decide how to report it.

**Comment by faboweb** [comment]
Also a good strategy.
