### ISSUE TITLE
more graceful failures

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1511]
this may be covered by some other tickets and should be addressed in the sprint after gov1 ... but i wanted to log it as an example of an opportunity for improvement.

if you refresh voyager but voyager cannot find a good node to connect to this is what the user sees:

<img width="1192" alt="screen shot 2018-11-01 at 12 19 46 pm" src="https://user-images.githubusercontent.com/6021933/47864635-7e7f2d00-ddd0-11e8-9cf3-29e963b08808.png">

1. we don't need to notifications in the top right corner here

2a. a more graceful failure = **do not dispay this full screen modal** - but instead rely on the network-connectivity-bar to change states from green to orange and display 1 non-invasive popup that says "we're going to keep trying to connect to a good node for you. in the mean time, your experience may be degraded and we would recommend against making any transactions". 

2b. part two of this should include disabling all submit buttons and some in app messaging about how maybe some of the data is not accurate.

3. if for some reason we _absolutely_ have to show this full screen modal - it should include an input so the user can add an IP if they know one.

**Comment by faboweb** [comment]
let's do it! thx for opening this issue

**Comment by faboweb** [comment]
@jbibla in which cases would `if for some reason we _absolutely_ have to show this full screen modal - it should include an input so the user can add an IP if they know one.` happen?

**Comment by faboweb** [comment]
Working on this in #1533

**Comment by faboweb** [comment]
Done in #1533
