### ISSUE TITLE
Can't undelegate: "invalid Bech32 prefix; expected cosmos, got cosmosvaloper"

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1517]
UI Version: 03067df8325c49d19fffe9e7e35521f09c534369

Description:

```
$ yarn build:gaia
$ yarn build:local --overwrite=true
$ yarn start local-testnet
```

1. Log in using the `local` account.
1. Undelegate 1 atom.

A notification reports success but the undelegation fails:

![screen shot 2018-11-05 at 1 18 19 pm](https://user-images.githubusercontent.com/2148537/48018022-c0281480-e0fd-11e8-8925-ac94dedcd32a.png)

The HTTP response is `invalid Bech32 prefix; expected cosmos, got cosmosvaloper`.

**Comment by faboweb** [comment]
Can't replicate this. You're sure you did `yarn build:gaia`?
