### ISSUE TITLE
Create a list of attack vectors

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1523]
Create a list of possible attack vectors

Timebox: 2days

**Comment by NodeGuy** [comment]
Already done: https://docs.google.com/document/d/1WOzU-518hsnScDvgbH6h8y2mb09LrzexTvUn7wISDZE/edit

**Comment by faboweb** [comment]
This doesn't feel like those are all possible attack vectors.

**Comment by NodeGuy** [comment]
It's not.  A threat model is never finished.

Security is not a black-and-white art, it's about economics.  I could list 1,000 attack vectors but most would be uninteresting because they're not cost effective.  A threat model is a living document that grows as we learn more about the domain.

**Comment by faboweb** [comment]
Should we actively explore some more attack vectors while we have you?

**Comment by NodeGuy** [comment]
I'm currently exploring another one involving key revocation but think I'm already at the point of diminishing returns and that my remaining time would best be spent elsewhere.  I enjoy the topic but I'm not a security expert.
