### ISSUE TITLE
Improve notification on no node found situation

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1532]
In the case of no connection:
do not dispay the full screen modal - but instead rely on the network-connectivity-bar to change states from green to orange and display 1 non-invasive popup that says "we're going to keep trying to connect to a good node for you. in the mean time, your experience may be degraded and we would recommend against making any transactions".

also: prevent notification popup spam like here:
<img width="1192" alt="screen shot 2018-11-01 at 12 19 46 pm" src="https://user-images.githubusercontent.com/6021933/47864635-7e7f2d00-ddd0-11e8-9cf3-29e963b08808.png">

**Comment by NodeGuy** [comment]
Duplicate of https://github.com/cosmos/voyager/issues/1511.

**Comment by faboweb** [comment]
This is split out from that issue.

**Comment by NodeGuy** [comment]
Oh, sorry.

**Comment by faboweb** [comment]
Change naming to "Node is not reachable"
Add option to retry or use mocked version

**Comment by faboweb** [comment]
Working on this in #1533

**Comment by faboweb** [comment]
Done in #1533
