### ISSUE TITLE
Cleanup lcdClientMock and unit tests

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1534]
Description:

I've noticed that some of the unit tests use the `lcdClientMock` examples and some not, also the file is huge with >1k LOC. 

Ideally we'd use contract tests and get the mocked values directly from the SDK's Gaia-lite swagger file (cc: @NodeGuy), but in the meantime I think doing a cleanup and splitting the file into (1) mocked values and (2) logic, funcs, etc.

Also note that there's already some mocked values in the following folder: https://github.com/cosmos/voyager/tree/develop/test/unit/specs/store/json

**Comment by faboweb** [comment]
Ah so the scope is only? 
> splitting the file into (1) mocked values and (2) logic, funcs, etc.

**Comment by fedekunze** [comment]
Yes, and ensuring that all tests use the same mocked values from (1)

**Comment by fedekunze** [comment]
Closing as we'll deprecate the lcdClientMock file #1742
