### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1537]
Description:

User got Internal server error when querying accounts and validators

Sentry [ref1](https://sentry.io/tendermint/cosmos-voyager/issues/755942289/) and [ref2](https://sentry.io/tendermint/cosmos-voyager/issues/755942292/)

```
GET http://localhost:9071/stake/validators [500]
--
Error: couldn't query account. Error: ABCIQuery: Post http://104.237.6.136:26657: read tcp 192.168.100.128:65015->104.237.6.136:26657: read: connection reset by peer
```

**Comment by faboweb** [comment]
Is this an error the LCD produces because it can't connect to the network? Do you have a proposal on how to solve this?

**Comment by faboweb** [comment]
Still needs to be reproduced.

**Comment by fedekunze** [comment]
I couldn't reproduce this...

**Comment by fedekunze** [comment]
Closing as this is now catched on the request
