### ISSUE TITLE
Consistent way of writing unit tests

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1543]
Description:

There are currently two ways we're doing unit testing:

1. `describe()` and `it()` (eg: [PageStaking.spec.js](https://github.com/cosmos/voyager/blob/develop/test/unit/specs/components/staking/PageStaking.spec.js))
2. `test()` (eg: [DelegationModal.spec.js](https://github.com/cosmos/voyager/blob/develop/test/unit/specs/components/staking/DelegationModal.spec.js))

We should stick with one or another, so we'd have to choose either `1.` or `2.`, update our coding guidelines with the decision and do a refactor of our unit tests.

**Comment by NodeGuy** [comment]
I used `test` in DelegationModal because it's the default in Jest before I saw that we are using `it` elsewhere.  I'm happy for us to `it` consistently.

**Comment by fedekunze** [comment]
I like `it` more as well

**Comment by faboweb** [comment]
I like how the jasmine syntax reads more like a real description (spec):

it should return an object property x when I give it input y

**Comment by faboweb** [comment]
@jbibla how comes you think this is such a complex task?

**Comment by jbibla** [comment]
i suppose if we're only changing `test` to `it` then all the tests should pass and it will be a bunny rabbit task not an elephant.
