### ISSUE TITLE
order and architecture of vue files

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1544]
it would be nice if we could agree on the order of the `<script>` section of our `vue` files and enforce these rules.

- order of imports
- name, computed, data, props, methods etc...

**Comment by jbibla** [comment]
we should use a tool to do this - if it exists

**Comment by faboweb** [comment]
maybe a prettier plugin for vue

**Comment by faboweb** [comment]
maybe eslint > sort object properties
