### ISSUE TITLE
misc. fixes

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1556]
- `LiProposal` status indicator is not in the right place
- `TmDataError` missing from `PageProposal` and `PageTransactions`
- `PageValidator` back button goes to wrong tab
- proper messaging for `TabMyDelegations`
- proper messaging for `PageTransactions`

**Comment by fedekunze** [comment]
++++. Can you elaborate on the `proper messaging for ...` points ?

**Comment by jbibla** [comment]
proper messaging for TabMyDelegations: 
<img width="889" alt="screen shot 2018-11-13 at 8 30 21 am" src="https://user-images.githubusercontent.com/6021933/48416541-815a1600-e71e-11e8-83f0-5e6f58b1ec02.png">

proper messaging for PageTransactions:
<img width="889" alt="screen shot 2018-11-13 at 8 30 35 am" src="https://user-images.githubusercontent.com/6021933/48416525-73a49080-e71e-11e8-8abe-163037dc6cd7.png">
