### ISSUE TITLE
Scrolling bug on TabMyDelegations

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1572]
**Description:**

There's a scroll related bug on the `TabMyDelegations` page that displays an empty page (see screenshot).

**Steps to reproduce** (using `yarn start` with old testnet):

1. Go to `Staking` > tab `Validators`
2. Scroll all the way to the bottom of the validators index
3. Click tab `My Delegations`
4. Tab displays empty page

<img width="1234" alt="screen shot 2018-11-14 at 12 02 17 pm" src="https://user-images.githubusercontent.com/31522760/48478635-2818e200-e805-11e8-9c07-8a44539be5ff.png">

**Comment by fedekunze** [comment]
cc: @jbibla

**Comment by fedekunze** [comment]
we'll probably have to check this on other existing tabs as well

**Comment by jbibla** [comment]
do you know what the problem is?

my guess: the scroll position doesn't reset when changing routes.

**Comment by faboweb** [comment]
>  the scroll position doesn't reset when changing routes.

that was our guess as well

**Comment by fedekunze** [comment]
can't reproduce on local testnet since we only have one validator

**Comment by faboweb** [comment]
You could use the mocked connection and edit lcdClientMock to have 50 validators

**Comment by jbibla** [comment]
it's not obvious to me why we need the perfect scroll plugin. can we remove this and rely on css?

**Comment by faboweb** [comment]
Can you ask @nylira why he added it in the first place? Maybe it serves a purpose.

**Comment by jbibla** [comment]
from @nylira: "it was to normalize the app design between multiple operating systems. For example, Windows and Linux have ugly default scrollbars that we cannot style. It also eats into the horizontal space of the app itself, as well as making scrolling popups and panels look not as great."

i would vote to remove it. i have no issue with native scrollbars and don't think we need this extra dependency. 

i will also fix the bug reported in this issue.

**Comment by faboweb** [comment]
I remember that there was an issue on Windows with the scrollbar. Could you check there first before removing the plugin?

**Comment by jbibla** [comment]
> I remember that there was an issue on Windows with the scrollbar. Could you check there first before removing the plugin?

i'm going to open a ticket to address this as it is a low priority refactor and requires much work to work properly without it.
