### ISSUE TITLE
Internal error: parse error near equal

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1575]
1.  `yarn start local-testnet`
1.  Click `Transactions`

Result:

500 Internal Server Error

`TxSearch: Response error: RPC error -32603 - Internal error: parse error near equal (line 1 symbol 8 - line 1 symbol 9):"="`

![screen shot 2018-11-14 at 4 12 39 pm](https://user-images.githubusercontent.com/2148537/48512692-27de0e00-e828-11e8-93f8-c8619caa9a53.png)

**Comment by fedekunze** [comment]
thanks for filing this ! I missed the `' '` that had to wrap the `action`
