### ISSUE TITLE
Page Wallet doesn't use 100% width

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1589]
Description:

there's a lot of space not being used on the left side of `PageWallet`

<img width="1423" alt="screen shot 2018-11-18 at 5 31 46 pm" src="https://user-images.githubusercontent.com/31522760/48677791-7ec24b00-eb7a-11e8-96bb-740ccf847db1.png">

**Comment by faboweb** [comment]
fixed with updating to latest tendermint ui
