### ISSUE TITLE
Proposal tally not being updated after voting

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1591]
SDK Version: `0.26.1-rc1`

Description:

Proposal still showing 0 for all tally results after successful voting

Proposal tally : 
```
tally_result: { 
abstain: "0.0000000000"
no: "0.0000000000"
no_with_veto: "0.0000000000"
yes: "0.0000000000"
}
```

While get proposal votes is working fine:

```
option: "No"
proposal_id: "2"
voter: "cosmos15ukq6kf84hzjgsheeetd656q655ehs3sv5gw8w"
```

cc: @jackzampolin @cwgoes

**Comment by sunnya97** [comment]
Is the voter staked?  Cause if not, their vote should not be contributing to the results.

**Comment by fedekunze** [comment]
Closing as per our discussion with Sunny
