### ISSUE TITLE
Page Send doesn't allow sending decimal amount

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1592]
Description:

Steps 

- Go to `Wallet` and click `Send` on any Coin.
- On the Send Page add any decimal amount (eg: `1.5`)

The button is not disabled but it doesn't allow sending decimals either. If you change the amount to an integer and click `Send Tokens` then it shows the confirmation popup.

We should be able to send decimals, but if not, we should disable the `Send Tokens` button, it's bad UX.

**Comment by jbibla** [comment]
> We should be able to send decimals

👍

**Comment by fedekunze** [comment]
Actually we can't support decimals. Closing in favour of #1594
