### ISSUE TITLE
Disable all transfer buttons if amount is not int

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1594]
Description:

On the newest version I'm getting the following error if I try to delegate/deposit/send an amount with decimals

`math/big: cannot unmarshal "1.2" into a *big.Int`

**Comment by jbibla** [comment]
how is it not possible to use decimals if the total value is in decimals?

**Comment by faboweb** [comment]
thank you for asking @jbibla, I find it also very weird

I think we discussed this before but let's pull in @cwgoes and @rigelrozanski for clarification

**Comment by fedekunze** [comment]
> how is it not possible to use decimals if the total value is in decimals?

🤷‍♂️

**Comment by fedekunze** [comment]
Will report this to the All in Hands

**Comment by cwgoes** [comment]
Gaia does not support decimal tokens. As far as I know it has never done so. I don't know what Voyager did previously or what might have changed recently. Likely we will have some "unit denomination" which should be visualized to the user (so all amounts should be divided by `1e18` or something) - that could be configured in Voyager.

**Comment by faboweb** [comment]
Validator Tokens are in SDK.Dec and Shares are in SDK.Dec. Calculating tokens from shares will probably produce a decimal.
But I remember that we said a user can only undelegate full tokens from a validator.

So summing up:
We do display only the possible undelegatable amount of tokens (rounded down) as stake per validator. We don't ever show decimals.

Correct?

**Comment by cwgoes** [comment]
Sounds good to me.

**Comment by faboweb** [comment]
Thank you @cwgoes for your patience :)

**Comment by rigelrozanski** [comment]
@faboweb  "undelegate full tokens" <- this means nano-atoms though! not full atoms! - the base unit for a "whole token" is a nano-atom

**Comment by faboweb** [comment]
Thank you @rigelrozanski for following up and clarifying. :) We came to the same solution yesterday with Chris. Let's increase the amount of tokens on the next testnet to x * 10^18 to be more representative of the actual values. We will do the same on our local testnet setups.
