### ISSUE TITLE
use eslint "sort-keys" 

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1599]
adding `"sort-keys": ["error", "asc", { caseSensitive: true, natural: true }]` will result in 800+ errors that need to be fixed manually. 

i am in favour of this change but want to make sure we all agree it's worth it.

**Comment by faboweb** [comment]
> 800+ errors that need to be fixed manually

wooooooooooooot ?!??!?!!!

**Comment by jbibla** [comment]
yeah, 800 properties in objects that are not sorted ...

**Comment by sabau** [comment]
I think this ocxuld be fixed with eslint --fix automatically
