### ISSUE TITLE
use tooltips to explain why buttons are disabled 

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1601]
- tm modal for delegation and undelegation
- probably needs to be a part of tm-btn component

**Comment by faboweb** [comment]
I agree that the modal explaining why a button is disabled is not the best UX.
I am not sure the tooltip is the best solution. A user would need to hover over the button to get those information. I think a form should state why a button is disabled in text always visible.

**Comment by jbibla** [comment]
> I think a form should state why a button is disabled in text always visible.

ah! interesting idea. i would like to investigate this design pattern.

**Comment by fedekunze** [comment]
Decision: 
- Include message bellow input fields on forms
- Add tooltip elsewhere

**Comment by fedekunze** [comment]
actually thinking it twice I think we should only disable the buttons when all the form fields are blank. Otherwise we should display the message.

For open modal buttons we can show the tooltip

**Comment by fedekunze** [comment]
@jbibla FYI @sabau is going to tackle adding the messages to the forms

**Comment by jbibla** [comment]
> we should only disable the buttons when all the form fields are blank

which buttons?

> For open modal buttons we can show the tooltip

this ticket is for adding a tooltip to disabled buttons on `PageProposal` and `PageValidator`.

**Comment by jbibla** [comment]
currently, including tooltips only when a button is disabled is not possible out of the box. the solution would be to either add a message for enabled buttons (which is redundant and would not be consistent with other buttons throughout the app) or duplicate buttons in the template to account for the various states (`v-if` for `availableAtoms` `connected` `oldBondedAtoms` etc...). my thinking has changed on this subject and i no longer thing that using tooltips for disabled buttons is the right thing to do.

since we have the new `Connecting...` value for buttons I think we should 1) leave all modal-triggering -buttons enabled and rely on proper form validation to communicate with the use and 2) disable form submission buttons unless a minimum amount of information is included (i think this is already the case). 

i would like to close this ticket and open a new ticket to address proper form validation and error messages to continue the work @sabau completed in https://github.com/cosmos/voyager/pull/1710.

this would mean that modal-triggering-buttons will only be disabled based on `connected` and form submit buttons would be enabled when a minimum amount of info is included. also, we need to display inline error messages on form elements _and_ keep the modals open unless there is a successful submission.

**Comment by faboweb** [comment]
> keep the modals open unless there is a successful submission

why?

**Comment by jbibla** [comment]
because if it is not a successful submission then the user can adjust the inputs or try again. i suppose if we implement the loading icon in the sidebar this problem would be addressed that way. 

ok, aside from the last point about leaving the modal open - do you agree with the strategy outlined above?

**Comment by sabau** [comment]
This is something I experienced a couple of time, I filled a proposal with a very cool description and clicked outside by mistake (the description was too long but back then we didn't had the feedback about that) when I reopened the modal it was blank.
Basically the modal closes and you loses your input, for me it would be equivalently nice to the user:

- keep it open except for explicit [X] click
- ask (can be annoying)
- store the temporary data and keep them when you reopen (but this comes with some problems sometimes AKA time/state based validations will break if your account has no more atoms or a certain time has passed etc..)

**Comment by faboweb** [comment]
I am on board and like the feedback from @sabau

**Comment by jbibla** [comment]
highly related to the "persist" part of #1631

**Comment by jbibla** [comment]
closed in favour of #1631 and https://github.com/cosmos/voyager/issues/1754
