### ISSUE TITLE
Validator not appearing in my delegations list right after delegating

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1618]
After delegating, I don’t see the validator I just delegated to in the list. Does it take some time to process?:

from https://github.com/cosmos/voyager/issues/1423

Can't easily reproduce as we don't have a multi node setup (testnet).

**Comment by fedekunze** [comment]
you can build overwrite the local testnet build

**Comment by faboweb** [comment]
May be an optimistic UI problem

**Comment by fedekunze** [comment]
> Does it take some time to process?

Moving to #1702
