### ISSUE TITLE
Display atoms instead of sub-atoms

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1627]
Follow up of #1594

We are currently interpreting values (tokens) from the SDK wrong. Tokens will always be send in the form of "sub-atoms" where 1 atom = 10^18 sub-atoms. 
We should keep sub-atoms (as BigNumber) in the state. But we will show tokens in the form of 1 atom. This means we need to:
- [ ] increase the amount of default tokens on a local node to reflect this increased amount
- [ ] create a displaying function to show  atoms from sub-atoms
- [ ] create a input conversion function to convert user inputs to sub-atoms

**Comment by faboweb** [comment]
Let's discuss this Chris.

**Comment by jbibla** [comment]
> Tokens will always be send in the form of "sub-atoms" where 1 atom = 10^18 sub-atoms.

we discussed addressing this in the REST API instead of on the client. this will be important for all clients and wallet providers.

**Comment by jbibla** [comment]
can we link this in the SDK repo and close this issue?

**Comment by faboweb** [comment]
https://github.com/cosmos/cosmos-sdk/issues/3261

**Comment by jbibla** [comment]
danke!

**Comment by faboweb** [comment]
Will not be done in the SDK
