### ISSUE TITLE
Page validator commission style bug

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1641]
Description:
<img width="1159" alt="screen shot 2018-11-26 at 11 28 48 am" src="https://user-images.githubusercontent.com/31522760/49011371-7a97be00-f176-11e8-8397-4678ff29a3ee.png">

**Comment by jbibla** [comment]
i guess it's not using `num.percent`? that's too many zeros. 

but "delegated steak" is also too small - i guess these components are not flexible enough. 

to fix this, we probably need to use some percentages OR flex
