### ISSUE TITLE
What should we show as transactions ? 

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1647]
Description:

On governance we're not displaying `Voting` transactions because they don't involve a transfer of funds besides of the use of `Gas`. Same happens with redelegations, as delegation amounts are moved from one validator to another (ie. `unbonding-delegation` from source validator + `delegation` to dst validator) but the user doesn't input any amount. 

Should we include all transactions that involve gas on the Tx history page ?

**Comment by jbibla** [comment]
yes 👍

**Comment by faboweb** [comment]
Decided
