### ISSUE TITLE
Weekly Internal Testing

### ISSUE THREAD

**Issue by zramsay** [cosmos/voyager#1650]
Tracking issue for whoever is assigned for weekly testing.

**Comment by okwme** [comment]
voyager review:

went to cosmos network

don't see anything on the page

oh wait, in the footer

Binary releases are available here. Is a binary release the same thing as an application?

i see a link that says mac

dont do fundraiser seed ok ok ok

kind of a big boy file, 160MB

found the folder, found the icon

can't be opened security warning

system preferences, security, general, open anyway



connecting, querying node, found, sign in

RAN INTO AN ERROR

```
The gaiacli rest-server (LCD) experienced an error: panic: resource temporarily unavailable goroutine 1 [running]: github.com/cosmos/cosmos-sdk/client/lcd.createHandler(0xc420b16690, 0x5, 0x7fff5fbffcdc) /go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:78 +0x634
```



view app logs:

see the same error, seems to be trying over and over again



create an issue:

not gonna create an issue



what does the error mean?

what should i do now?

is this a testnet thing or something wrong with voyager?

did i do something wrong or is it broken?



back to the readme

aha, no active testnet, you have to run a local node to test VOYAGER out

how did i miss that before?



click local node

click Build Gaia

start docker

run `yarn:build` , hm they must want me to download the voyager repo beforehand

LUCKILY I AM A GENIUS PROGRAMMER WHO KNOWS HOW TO DO THAT

click download zip on the github

put it in my downloads folder (i'm not planning on contributing to this project why would i clone it)

unzip

right click, services, new iterm window here

`yarn build:gaia` 

takes a long time

thinking about using status, balance and gnosis safe and it's a pain to use testflight but so much nicer than this. is there something like that for apple app store? testing alpha software?

done with all the downloads but doing something else now, github something,  building Cosmos SDK that sounds good

going to check twitter this is taking forever

omg it's finally done

ok seems successful but i forgot where i was in the tutorial

oh yea local node, find that link in the read me and click again to get to the right section

automatically sounds good, copy past that and....

`Error: Cannot find module 'fs-extra'`

LUCKILY I AM A GENIUS PROGRAMMER WHO KNOWS THAT I SHOULD RUN YARN FIRST

uhoh

```
[1/5] 🔍  Validating package.json...
error cosmos-voyager@0.8001.1: The engine "node" is incompatible with this module. Expected version ">=10.13.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

okkk again genius programmer knows how to update node to version 10.13

try `yarn` again

now `yarn build:local --overwrite=true`

that was quick

followed instructions:

`yarn start local-testnet`

shit i forgot the username and password... wish someone had told me to copy and paste it!



ok so now my whole screen is taken over by voyager and there's a control panel open on the right

select account is set to "local"

i think password was 1234567890 ill try that



jassss



ok screen is way too big for this application

but looks like i've got some steak and some localcoin, both with toooons of decimals for some reason

there's a total steak of 150, and available steak of 50

getting hungry

i see local testnet in the bottom with a green lock, i must be safe here

i see 28, 29, 30 idk what that is but i'm gonna click it, view block details!

oh sent back to my browser, cosmos explorer is offline, uhoh

ok back to voyager

oops the icon on my running apps that looks like voyager is the last application instance that i opened with the fatal error on the screen, lemme close that app

ok found it in the electron icon (no idea what electron is but OK)



click transactions, nothing to see here

staking, see local, delegated steak is 100, rewards, voting power, uptime looks bad only 0%, commission is .10%... let's see point ten percent is 10% of 1% right? so 0.001? idk what the means but combining percentage with decimal is kinda weird. n/a slashes,,,,

the validator list link!

ok looks the same page only without the link

didn't realize there was tab options tho

gonna check out the parameters one

was bewildered until i started hovering over the infos, all very informative... wish i had read the staking pool one first tho

ok clicking governance

nothing to see here

oh i can create a proposal ok

weird alignment on the page, the box that popped up is right and bottom aligned, the "no governance proposals" is still there. maybe it's cause i'm on a big screen or maybe this is a modal but it didn't pop up right...

making a funny proposal

adding 100 deposit amount but auto-corrected to 50

my account password.... was 1234567890 right?

show password to make sure, yup

submit proposal,,,, wait

hey there it is!

looks green looks good

proposal #1, no votes, no abstains, i'm gonna click it

there it is with all 50 of my steak deposited

i still have 50 available steak in the top toolbar, i wonder what that means

can i still spend steak that i have deposited?

i'm gonna vote

another bad modal, its bottom aligned and not totally right aligned but def not centered

clicking yes obv

password

vote

success message but nothing else changes....

go back, vote looks the same, didn't change any numbers...

ok, back to wallet

hmm only have localcoin now, maybe that steak did get taken away?

clicking send

sent to ....

click the cosmos...gfrc, not sure but that is probably my ..... username?

yay it copied it

1 local coin, password, hit return

popup to confirm

yes

sent!

still on the wallet page, i guess they think i wanna do another transaction?



back button, still have 1000 localcoin, oh yea i sent it to myself : )

clicking preferences cause idk what else to do now

live testnet

i thought i was on local testnet? i guess that's also a live testnet

node ip, interesting. clicking it. nothing happens

even though there's an arrow icon like it'll take me somewhere?

launch tutorial?

i didn't see this before... 

cool, thanks for the info but the little dots below the photos didn't change with the slides, were they supposed to?

ok i'm done gonna sign out

yay come again soon

hm blocks are still increasing, i wonder if i'm connected to the network even thought i'm not signed in?

what does that mean tho? my node is secured but am i running it?

i'm shutting it down

<3

**Comment by fedekunze** [comment]
Lmao @okwme thanks !

**Comment by sabau** [comment]
we should add this to the README

**Comment by faboweb** [comment]
Amazing review @okwme thanks a lot.
