### ISSUE TITLE
Inactive Delegations

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/voyager#1664]
Should the `Inactive Delegations` section should the unbonding amount? In this case, I bonded 5steak and then immediately unbonded 5steak, but it's not clear that I did so from this screen (says 100 which was my original).

![screen shot 2018-11-29 at 9 49 23 am](https://user-images.githubusercontent.com/5265989/49229863-680ec600-f3bc-11e8-826b-c12be0a4d151.png)

**Comment by faboweb** [comment]
Also referenced in #1387 
I will close this one and mark #1387 high prio
