### ISSUE TITLE
Voyager ran into an error

### ISSUE THREAD

**Issue by zramsay** [cosmos/voyager#1665]
UI Version: 0.8001.1

The gaiacli rest-server (LCD) experienced an error: panic: resource temporarily unavailable goroutine 1 [running]: github.com/cosmos/cosmos-sdk/client/lcd.createHandler(0xc420179500, 0x5, 0x7ffeefbffc94) /go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:78 +0x634 github.com/cosmos/cosmos-sdk/client/lcd.ServeCommand.func1(0xc420b3c900, 0xc4201b1080, 0x0, 0x8, 0x0, 0x0)

**Comment by zramsay** [comment]
![screen shot 2018-11-29 at 09 57 09](https://user-images.githubusercontent.com/8304391/49230200-1f0b4180-f3bd-11e8-9df4-503935f1981a.png)

also, i can't go back to the app from this view

**Comment by faboweb** [comment]
We will not work on this, as this will not be important anymore when on web.
