### ISSUE TITLE
Top right icons problem

### ISSUE THREAD

**Issue by zramsay** [cosmos/voyager#1667]
UI Version: 0.8001.1

Description:

- Clicking on refresh produces no evidence that a refresh was attempted
- clicking on search does nothing

**Comment by zramsay** [comment]
also, these down arrows aren't formatted correctly

![screen shot 2018-11-29 at 09 39 37](https://user-images.githubusercontent.com/8304391/49230729-57f7e600-f3be-11e8-8ec8-9136fbdbc14d.png)

**Comment by sabau** [comment]
Seems to be fixed. I found problems in a single page, PR ready!
