### ISSUE TITLE
Governance Proposal voting

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1683]
UI Version: 0.X.X

Description:

## Problem
After double voting on a proposal I get an error message saying that my action is already in the cache and I'm prevented to act on this proposal and on others too.

## Steps
- Create a proposal
- Deposit (I did it 1 + 2 + 40) 43 Steak then the Vote button is enabled
- Vote for it, let's say YES
- Vote again with the same value
- Every other action gets blocked: *Invalid Sequence. Got 9 expected 10*

## Possible solution
As far as I understood the root cause is the double voting with identical value, it will try to create two identical blocks, we can prevent this by storing in the state the last vote and disable just that value so you can't vote twice with the same value

Related: https://github.com/cosmos/cosmos-sdk/issues/3002

**Comment by jbibla** [comment]
is double voting supposed to be permitted?

**Comment by faboweb** [comment]
> is double voting supposed to be permitted?

no. but you can change your vote.

**Comment by fedekunze** [comment]
> is double voting supposed to be permitted?

you can vote as many times you want if the proposal is still on voting period. You just need to pay gas every time

**Comment by jbibla** [comment]
isn't the sequence number supposed to address this?

**Comment by faboweb** [comment]
> isn't the sequence number supposed to address this?

yes you are right, maybe there is a bug in incrementing the sequence on our side.

**Comment by faboweb** [comment]
I would still disable the option to vote for the same for a better UX.

**Comment by sabau** [comment]
I'm trying to reproduce it but it doesn't happen anymore

**Comment by jbibla** [comment]
> I would still disable the option to vote for the same for a better UX.

but if a user is allowed to vote more than once - shouldn't we permit this?

**Comment by faboweb** [comment]
> but if a user is allowed to vote more than once - shouldn't we permit this?

I suppose this would only confuse the user. "Have I voted already? Why can I vote 'Yes' again?". I would disable all options, that don't bring any value to the user.

**Comment by fedekunze** [comment]
> Why can I vote 'Yes' again?". I would disable all options, that don't bring any value to the user.

We should display the previous vote by the user somewhere on the proposal, that's the main issue here imo. 

Thus, I disagree with disabling voting for the same option, if users want to throw away their funds we shouldn't prevent them to do so

**Comment by faboweb** [comment]
> if users want to throw away their funds we shouldn't prevent them to do so

what's the reasoning here?

**Comment by fedekunze** [comment]
I guess the question is more why are you preventing them to do it ? I know it's not "bringing value" but if they choose to do so then be it

**Comment by fedekunze** [comment]
maybe add an additional confirmation with a note like 
`
You already vote ${this.option} on this proposal. Do you still want to send an additional transaction (with gas costs) ?
`
But definitely not preventing them to vote twice on the same option

**Comment by faboweb** [comment]
> why are you preventing them to do it

reduced complexity is always better for UX. preventing users to make errors as well. We are also i.e. validating form inputs. just because the user is in theory able to perform some action in the backend shouldn't mean the UI allows the user to do so.

**Comment by sabau** [comment]
So the outcome for this if I got it correctly should be:
- At loading get your last vote, if you voted in another session, reopened the app, we should behave in the same way as if you voted right now
- Save in the store your action even before the reply from the APIs, so speedy users won't have surprises
- once you get back the data add/update your last vote in the store 
  - I've seen that in the /proposals response this information is not there (who voted what) we just have a summary. 
- do something with this information: either block that vote option and / or show the datetime when you voted there

**Comment by sabau** [comment]
nice to have: show the datetime of your vote
- query the transaction that contain your most recent vote

**Comment by jbibla** [comment]
is "voting again" the same as changing your vote? if i vote "yes" and "no" on the same proposal - what is the expected result?

**Comment by fedekunze** [comment]
> is "voting again" the same as changing your vote? if i vote "yes" and "no" on the same proposal - what is the expected result?

that your final vote is "No"

**Comment by jbibla** [comment]
so it's not "voting again" then - it's "changing your vote" - which should be permitted @faboweb

**Comment by faboweb** [comment]
I am all for "changing your vote". I understood the discussion was around if we should allow "voting again" (with the same option).
