### ISSUE TITLE
Weird display effect when redirecting to Transactions page

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1691]
Description:

The effect is very fast, but it's annoying. 

Steps to reproduce:

- Go to a random page
- Click `Transactions` on the sidebar

**Comment by sabau** [comment]
I've checked and this happens when we switch tab, then all the transactions gets collected, and for a tiny amount of time you see the old list / no list message.
This will probably be addressed with the new graphics. Should we add a spinner in the meanwhile?

**Comment by sabau** [comment]
Practically this is the spinner
- the first time appears, and it stays there for a fraction of second,
- then once at least one transaction is in the store it doesn't appear anymore. and once the extra transactions has been fetched they are displayed.

A possible improvement I can see is to welcome the new transactions with a little animation and do the same to make the spinner disappear a bit more slowly the first time

Actually we can use the same technique also on other modals but probably this isn't the right place for this discussion

**Comment by sabau** [comment]
I think we should tackle this when we merge the repositories directly in the tm ui components

```
<transition name="transition"><...current compoment /></transition>
```

and some tiny css to manage Vue
```
.transition-enter-active, .transition-leave-active {
  transition: opacity 0.25s ease-out;
}

.transition-enter, .transition-leave-to {
  opacity: 0;
}
```

**Comment by faboweb** [comment]
> Should we add a spinner in the meanwhile?

Good easy fix.

I also like the animation idea. Let's discuss this tomorrow

**Comment by sabau** [comment]
I just tried in the pug world and it adds the classes out of the box XD so once will be merged is a 5 minutes fix

**Comment by faboweb** [comment]
Waiting for tendermint/ui merge

**Comment by sabau** [comment]
Seems not a problem anymore XD

**Comment by jbibla** [comment]
![giphy-3](https://user-images.githubusercontent.com/6021933/53175810-0f328080-35ed-11e9-89b6-6b4dd3073bba.gif)
