### ISSUE TITLE
Transaction progress indicators

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1702]
UI Version: 0.X.X

Description:
I experienced some lag between actions, while this is OK on Desktop app, it can be less accepted by a web user. We can add some spinner just to know that something is happening, either on the whole application or contextualised (probably the last PR from @faboweb already started in this direction)

Epic: #1284

**Comment by jbibla** [comment]
definitely! we are moving towards a more optimistic ui: actions should be instant and should not block on pre-loading content. there are a number of issues open to address these kinds of things.

#1284 
#1596 
#865 
#984 

(there may be others)

**Comment by sabau** [comment]
Thanks! will use those as reference

**Comment by sabau** [comment]
Can me merged into #1691 fix

**Comment by jbibla** [comment]
looks like this can be closed - the remaining task is being tracked in #1849
