### ISSUE TITLE
Balance header availability not updated after deposit

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1706]
Description:

After creating a proposal the available Steak decreases as expected
After adding some more deposit to the proposal, the header information is not updated, on the ohter hands other places are updated (the wallet is OK i.e.)

**Comment by fedekunze** [comment]
same happens with gas only transactions

**Comment by jbibla** [comment]
> the header information is not updated

which header are you referring to? (screenshots welcome 😄)

**Comment by fedekunze** [comment]
the user balance is not reduced

**Comment by fedekunze** [comment]
just tested and it's not yet fixed for proposal deposits

**Comment by fedekunze** [comment]
Fixed on #1765

**Comment by fedekunze** [comment]
Sorry indeed this was fixed, the optimistic update on deposit wasn't
