### ISSUE TITLE
ProposalModal Amount bug

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1707]
### Description:
- I can't find a way to choose from which coin I want to Deposit
- Once I have 0 Steaks available the UI let me create a proposal with 1 steak anyway, then an error is thrown (which is OK i think)

Here the response:
[proposalCreation.txt](https://github.com/cosmos/voyager/files/2649983/proposalCreation.txt)

and the error: 
<img width="471" alt="screen shot 2018-12-05 at 19 03 43" src="https://user-images.githubusercontent.com/1656471/49534126-19cc5c00-f8c1-11e8-896b-db2c5f7ebf4e.png">

**Comment by sabau** [comment]
I would touch this logic that define a valid amount:
- between: between(1, this.balance > 0 ? this.balance : 1)

**Comment by fedekunze** [comment]
we should check that we're sending the coins specified on the min deposit (available through the governance parameters)

**Comment by jbibla** [comment]
@sabau 

> I can't find a way to choose from which coin I want to Deposit

i think this is expected - should only be steak (for now) - and atoms (in the future) - and other tokens in the future if and when governance permits them

> Once I have 0 Steaks available the UI let me create a proposal with 1 steak anyway, then an error is thrown (which is OK i think)

i think our approach is to disable the button and add a tooltip if you are not able to do the action. 

also, that error message could use some love 😆 

---

@fedekunze 

> we should check that we're sending the coins specified on the min deposit

definitely!
