### ISSUE TITLE
Tests improvement: some actions are not triggering Vue hooks

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1709]
UI Version: 0.X.X

Description:

I've been playing with the console and it seems during our tests, if we edit an element via DOM
- Field.element.value = something

That will not trigger the data management from Vue, instead we probably should use setData or triggering input

**Comment by fedekunze** [comment]
need to use `Vue.set(Field. element, value, something)`

**Comment by fedekunze** [comment]
eg: 

```
    setProposal(state, proposal) {
      Vue.set(state.proposals, proposal.proposal_id, proposal)
    },
```

**Comment by faboweb** [comment]
@fedekunze does this work for DOM elements as well?

**Comment by faboweb** [comment]
What's the action proposed in this issue?
