### ISSUE TITLE
Use 24 hr format for displaying time

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1720]
Description:

Based on feedback from @cwgoes

**Comment by jbibla** [comment]
what is the thinking here @cwgoes ? something beyond preference?

**Comment by cwgoes** [comment]
I think 24-hour time is unambiguous and ought to be the preferred world format - it's definitely popular among our initial likely userbase.

It doesn't necessarily need to be the default, but a configuration option would be nice.

**Comment by jbibla** [comment]
> a configuration option would be nice

makes sense to me.

**Comment by sabau** [comment]
Agree let's pick the system preferences then eventually we can override them with some config

**Comment by sabau** [comment]
I would like to include in this also some fixes on time: 
- sometimes we use Date instead of moment
- transaction.time seems not to be there for cosmos-sdk/Send transactions

**Comment by sabau** [comment]
Exactly, 
- the type does not match, we are storing an ISO string, but the usages of them seems to like Number
- it seems to be null for some kind of transactions at least (just checked from develop)

**Comment by faboweb** [comment]
Requested: https://github.com/cosmos/cosmos-sdk/issues/3238

**Comment by sabau** [comment]
in the meanwhile the cause of the missed enrichment was just another Type mismatch :)

```
heightsSet: {28, 25, "2", "5", "8"}
```
