### ISSUE TITLE
lcdClient method naming

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1729]
Description:
 
We have some inconsistencies between lcdClient and lcdClientMock methods.
I think it would be easier if we adhere to a common naming: prefixing all the GET calls with either get or query, same with the post/submit

**Comment by fedekunze** [comment]
I don't think we should spend time doing this if we're deprecating the mocked lcd client. @faboweb should we close this ?

**Comment by faboweb** [comment]
> we can still change the names on the LCDClient.js

yeah I think this was mainly the purpose of this ticket ;)
