### ISSUE TITLE
NVM support

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1733]
UI Version: 0.X.X

Description:
We are suggesting using `n` to manage the node version (or native one).

To increase the freedom of choice of developers using Voyager we may also decide to support nvm and add a .nvmrc file at the root of the project, so users that are using it will still be happy

**Comment by sabau** [comment]
True! I meant to support both, then the developer chooses which one to use, for us the effort will be just to specify which version to run o nthe .nvmrc file

**Comment by faboweb** [comment]
Sure let's do it.
