### ISSUE TITLE
Last commission Change date

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1737]
Times fly, it seemed few minutes ago.

![screenshot 2018-12-11 at 16 49 02](https://user-images.githubusercontent.com/1656471/49812018-c3e63100-fd64-11e8-85de-91f8ead338bb.png)

**Comment by jbibla** [comment]
🤦‍♂️

**Comment by jbibla** [comment]
this isn't actually a bug in the JS code. the validator commission update_time being returned is `"0001-01-01T00:00:00Z"` which is techincally 2018 years ago.  so it has something to do with the validator data itself, not the way we are displaying it.

**Comment by faboweb** [comment]
Did you open an issue on the SDK?

**Comment by jbibla** [comment]
no not yet. @jackzampolin do you know anything about this?

some context:
- we spin up a local testnet with our `yarn start local-testnet` command
- this creates a network with 1 validator node
- this validator's `commission.update_time` is `0001-01-01T00:00:00Z`

**Comment by jackzampolin** [comment]
@jbibla I have not heard about this. This is in the validator struct returned from which endpoint?

**Comment by faboweb** [comment]
`GET /stake/validators`

**Comment by jbibla** [comment]
i don’t think it’s an issue with the API - my gut tells me it’s just the default property for “the node that starts the network” … any ideas @sabau ?

of course, programming is all about _going with your gut_.

**Comment by faboweb** [comment]
Let's investigate and close again or open an SDK issue.

**Comment by faboweb** [comment]
Awesome. Thx.

Jordan Bibla <notifications@github.com> schrieb am Mo., 28. Jan. 2019 um
18:29 Uhr:
