### ISSUE TITLE
Wiki and jsDoc

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1739]
Description:

It's gonna take some time but I really think we should start building up our wiki / dump some doc from other sources there. 
Also just a list of references of things you should know may be enough to start (also linking all the cosmos and tendermint docs etc.)

Supports #1694

**Comment by sabau** [comment]
We may also want to use jsdoc / vue-jsdoc to keep the code always aligned with the docs

**Comment by faboweb** [comment]
Good idea
