### ISSUE TITLE
Proposal: change short addresses output

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1741]
**Description**:

Currently the `shortAddress` function only returns the last `x` chars of and address and the bech32 prefix. I'd propose to also display the first `x` characters right after the prefix:

Present display: `cosmos1...d14fd`
Proposed display: `cosmos1714c6...d14fd`

Note: Github also uses this format to shorten the commit hashes/ids: `714c659b6..c2a4444fd`.

**Argument:**

I think this will avoid unnecessary hovering on the address component for looking up the full address displayed by the tooltip since it also shows the first characters.

**Comment by jbibla** [comment]
if you think this will provide important information up front then i agree

**Comment by jtremback** [comment]
I want this, I am a user

**Comment by jbibla** [comment]
@jtremback can you help me understand the use case?
