### ISSUE TITLE
Explorer in Voyager

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1744]
Many users are looking to have a read only block explorer to see the state of the network and verify txs.

Proposed structure:
New page `Network`: Holds information about the current network (similar to first page in old explorer). Can maybe be enriched with data from https://hubble.figment.network/chains/gaia-9002.
![image](https://user-images.githubusercontent.com/5869273/49941223-316b9c00-fee2-11e8-9c73-33b359812834.png)

New page `Blocks`: Holds information about blocks. Similar to our old block explorer in Voyager with blocks flying in. You can search for a block and open it in a new page (able to link to it).

New page `Block`(no link): Holds block meta info (see below). Holds link to transactions page (pre-filtered for block).
![image](https://user-images.githubusercontent.com/5869273/49941495-f9188d80-fee2-11e8-9372-bf51440d0381.png)

(old) Page `Transactions`: Add ability to filter for: `hash`, `block`, `address`. Ability to set those as an URL-query so we can link to it. 
- https://github.com/cosmos/voyager/issues/1719
- https://github.com/cosmos/voyager/issues/1701
- https://github.com/cosmos/voyager/issues/965

**Comment by fedekunze** [comment]
How does the old `Transactions` page relate to the new one ?

**Comment by fedekunze** [comment]
I was initially thinking on having a link on the sidebar that says `Blockchain` and within that we can have a `Network` and `Blocks` tabs (maybe `Transactions` depending on the above question)

**Comment by jbibla** [comment]
New page: Network 👍
New page: Blocks 👍 
New page: Block 👍

**Comment by fedekunze** [comment]
> New page: Network 👍
New page: Blocks 👍
New page: Block 👍

I guess that means 2 sidebar links (one for network and one for blocks ?). I'm down if everyone agrees to have that

**Comment by jbibla** [comment]
> 2 sidebar links

yeah, inside of the network connectivity component (is my proposal).

**Comment by faboweb** [comment]
> network connectivity component

I would also link from there. I am not sure that it is clear, that this component would link to anything. what do you think about that?

**Comment by jbibla** [comment]
> I would also link from there.

sure, let's do both.

**Comment by sabau** [comment]
Just for mainenance I'll split this into 4 tickets
- Store module for blocks
- Blocks page
- Block detail (page or modal eventually poppedup if URL says so)
- Network page

Sounds good? so we can solve this in 4 PRs
