### ISSUE TITLE
rename "local-test" to "no-funds-account"

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1761]
Description:

Run `yarn start local-testnet 4`

Only `main-account` has tokens to spend.

<img width="664" alt="screen shot 2018-12-19 at 12 32 24 pm" src="https://user-images.githubusercontent.com/31522760/50229980-594b7b80-038a-11e9-9518-121a838b9af7.png">

**Comment by faboweb** [comment]
This is expected.

**Comment by fedekunze** [comment]
Then we should add a message on the README to tell users to choose `main-account` instead

**Comment by faboweb** [comment]
Or rename the `local-account` to `no-funds-account` ;)

**Comment by fedekunze** [comment]
I like that better :+1:

**Comment by faboweb** [comment]
Fixed on `web` branch
