### ISSUE TITLE
set custom messages on TmFormMsg.vue

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1762]
Description:

Currently you can't submit a custom error message on `TmFormMsg.vue`, as it only supports the types defined [here](https://github.com/tendermint/ui/blob/develop/src/components/TmFormMsg/TmFormMsg.vue). 

For example, I wanted to display a message for #1707 that the user didn't had the `min_deposit` coin denomination on her balance.

**Comment by faboweb** [comment]
Actually this allows to define a custom message. Just don't define a type and add the message as content. It will be put into the slot.
