### ISSUE TITLE
Refactor vuex modules tests

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1789]
Link to the guide lines: https://www.notion.so/cosmosvoyager/Code-Style-b974391ca44c450191b7719eb0235970

_Originally posted by @faboweb in https://github.com/cosmos/voyager/pull/1782/files/1aed9888d0c2a712cb93e6ca4fad7985477ea18d_

**Comment by faboweb** [comment]
Closing in favor of #1337
