### ISSUE TITLE
Remove hardware session until Ledger is supported

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1793]
Description:

The Ledger session is confusing in the sense that ledger integration has been a WIP epic for a while (_i.e_ not yet working/supported, see #1338) and we're giving the option to sign in with ledger on the welcome page.

Also if you click twice on the icon from the page you can access Voyager without setting any account, which throws lots of errors in the notifications

**Comment by faboweb** [comment]
This is dev flagged anyway and not visible to production users. ;)

**Comment by fedekunze** [comment]
Closing the issue then
