### ISSUE TITLE
Key recovery with seed

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1796]
Description:

Part of the research I've made on different wallets I've particularly liked the way Gnosis safe and uPort have recovery seeds. 

Ideally we should have a the words numbered and then confirmed (see uPort imgs), then use [`POST /keys/{name}/recover`](https://cosmos.network/rpc/#/ICS1/post_keys__name__recover) to recover it

Gnosis Safe (image from Google Play):

![image](https://user-images.githubusercontent.com/31522760/50693689-6e750b00-1016-11e9-983f-f0b9af620bc5.png)

uPort: 

![zxw3geyrfyobbenb ohxw_thumb_21eb](https://user-images.githubusercontent.com/31522760/50693929-3e7a3780-1017-11e9-8984-59971797d8e3.jpg)
![wzty4djvrvew1kadjkxtqg_thumb_21ec](https://user-images.githubusercontent.com/31522760/50693936-4043fb00-1017-11e9-9a8c-3040045cae5f.jpg)

**Comment by jbibla** [comment]
awesome!

**Comment by jbibla** [comment]
looks like we're not going to allow this in the browser for the foreseeable future. will close for now, unfortunately.

**Comment by fedekunze** [comment]
😞

**Comment by faboweb** [comment]
App design is coming up @fedekunze ;)
