### ISSUE TITLE
Add remaining messages to transaction

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1805]
Description:

As far as I know voting and the distribution transaction messages are missing on the LiTransaction

Missing txs: 

**Staking**:

- [ ] MsgCreateValidator
- [ ] MsgEditValidator
- [ ] MsgUnjail

**Governance**:

- [ ] MsgVote

**Distribution**:

- [ ] MsgSetWithdrawAddress
- [ ] MsgWithdrawDelegatorReward
- [ ] MsgWithdrawValidatorCommission

**Comment by jbibla** [comment]
> distribution transaction messages

what are these?

**Comment by fedekunze** [comment]
withdraw commission and rewards

**Comment by faboweb** [comment]
This is staking 2 I assume.

**Comment by jbibla** [comment]
if this is done in the SDK we should show it!

**Comment by faboweb** [comment]
We can tackle this in the context of the explorer then.

**Comment by fedekunze** [comment]
imo we should add voting now and then we can add distribution msgs and the staking MsgEditValidator
