### ISSUE TITLE
"Voyager tester" user testing results

### ISSUE THREAD

**Issue by cwgoes** [cosmos/voyager#1812]
*Version*

develop branch at d33ce3a91e330a13cb2b9d96bd592fe5ed039aa7

*Installation*

I would have liked the option to run Voyager with a custom `gaiad` binary since I already had one built. 

Otherwise the installation process was smooth. I first started Voyager on a local testnet.

*Local testnet, 1st try*

When Voyager starts, it immediately loads the "Sign In" page. As I just installed the software and definitely don't have any accounts yet, this is a bit confusing.

Also, the dropdown under "Select Account" seems to have a blank placeholder.

Upon hovering over the options I see two accounts (which aren't visible until hovered-over), "local-test" and "main-account". I don't know the password to either account, so I click the back button.

I now move to "Create Account", successfully create a new account, and move to the main page, only to encounter an error:

![2019-01-09-112929_823x500_scrot](https://user-images.githubusercontent.com/24760279/50893763-ed48ba00-1401-11e9-840b-7433b6fd9a5b.png)

There are also two red (scary!) notifications in the top right I don't quite understand:

![2019-01-09-113026_491x177_scrot](https://user-images.githubusercontent.com/24760279/50893791-02bde400-1402-11e9-968d-f8731fc6627a.png)

I didn't enable error collection, why would there be an issue "switching it off"? I presume the governance parameter issue has to do with the LCD timeout.

I decide to close Voyager and re-open it.

*Local testnet, 2nd try*

I can't immediately run `yarn start local-testnet` again, because it seems like the existing webpack process / dev server is still running on port 9000:

![2019-01-09-113436_668x438_scrot](https://user-images.githubusercontent.com/24760279/50894044-90013880-1402-11e9-9813-26fa4873fcad.png)

I manually kill the webpack process and try to start again.

This works, but the account I just created doesn't show up in the "Sign In" dropdown. Are local testnet accounts deleted perhaps? (I did not use the `--overwrite` flag)

I go to the Voyager Github and try to find a password for the "local-test" account, seems it might be `1234567890`. And so it is!

Now I sign into that account, but it appears to have no funds, which is strange (wouldn't the local testnet account have funds in genesis). Unfortunate, for I would like to send a transaction. Still, I'll play around.

I see something about "total stake" and "available stake", both of which are zero:

![2019-01-09-113847_478x162_scrot](https://user-images.githubusercontent.com/24760279/50894310-2cc3d600-1403-11e9-9048-2b95b0365fee.png)

I don't know what total / available mean, and there are no tooltips - I guess "total" includes any stake I might have delegated (and thus locked up) at the moment? 

I head on over to the "Staking" tab to see if I have any delegations. Sadly I do not, but there is one validator:

![2019-01-09-114038_1091x785_scrot](https://user-images.githubusercontent.com/24760279/50894391-64cb1900-1403-11e9-99d3-146b4249c44a.png)

I wonder what happened 2018 years ago that caused this validator to decide to change their commission! I also note that "minimum self-delegated stake" is not presently a feature of the SDK state machine (no way for validators to enforce), so I wonder how this field is populated.

Without any tokens, there doesn't seem to be much I can do. I try to submit a proposal, which brings up a nice modal dialog, but "Submit proposal" is greyed-out:

![2019-01-09-114257_726x813_scrot](https://user-images.githubusercontent.com/24760279/50894527-b8d5fd80-1403-11e9-81b1-35888501dc74.png)

Perhaps because I don't have enough funds?

There's also a "search" button at the top right, but it doesn't seem to do anything:

![2019-01-09-114342_1124x850_scrot](https://user-images.githubusercontent.com/24760279/50894574-d30fdb80-1403-11e9-8a57-3574795f9d5c.png)

I try "searching" on the staking page and it does seem to filter the validators by moniker.

I'll try with "main-account" instead.

*Local testnet, 3rd try*

This account has funds! Some "STAKE" and "Localcoin", how exciting. Looks like I have 100 STAKE delegated to the "local_1" validator, but sadly no rewards yet.

I decide I'd like some of my STAKE back, so I try to undelegate. The modal seems rather out of proportion:

![2019-01-09-114705_665x1122_scrot](https://user-images.githubusercontent.com/24760279/50894735-4ca7c980-1404-11e9-9ad0-a8cb31f86f96.png)

The text field behaves oddly; if I enter above 100 stake, it seems to change the amount to 100, but then lets me continue typing numbers after. I decide to try to undelegate more than 100 stake (maybe there's a bug and I can get free stake!)

That doesn't seem to work (although I can apparently submit the transaction):

![2019-01-09-114837_477x92_scrot](https://user-images.githubusercontent.com/24760279/50894820-8973c080-1404-11e9-8ae2-498949417449.png)

I don't understand what that error message has to do with undelegating over 100 stakes (maybe nothing), I'll try to undelegate fewer than 100.

That doesn't work either:

![2019-01-09-114938_486x188_scrot](https://user-images.githubusercontent.com/24760279/50894855-a8725280-1404-11e9-8641-b87756ddef41.png)

I guess I can't get my stake back, so I'll try to delegate some more instead. That also doesn't work (same error about "own delegator address").

I decide to try to write a governance proposal:

![2019-01-09-115142_720x804_scrot](https://user-images.githubusercontent.com/24760279/50894951-f0917500-1404-11e9-8cf9-5aaf07cc4dfe.png)

I notice that the "submit proposal" button is bright blue as soon as I set the deposit to a positive number. I wonder if this is why I couldn't submit a proposal earlier (but it's not obvious that a deposit is necessary).

That doesn't work:

![2019-01-09-115233_466x118_scrot](https://user-images.githubusercontent.com/24760279/50894998-10c13400-1405-11e9-96f4-d0f9fe5d051e.png)

Maybe I need to specify the denomination of deposit? I'm not sure which denominations are permitted. I can't seem to type letters into the "Deposit amount" box, though, so I don't know how to set a denomination.

I play around with just sending tokens, which seems to work. A few other miscellaneous points of feedback:

- On the "Transactions" page, when I hover over a transaction the cursor changes to a hand, but clicking the transaction does nothing.
- I wish the password entry were always a confirmation modal and very consistent, instead of being embedded in the pane with other fields - it's not clear that "Send tokens" will ask for additional confirmation (although it does), and other actions (e.g. submitting a proposal) do not ask for confirmation.
- I can't find a way to send multiple tokens at once in a single transaction. Is this possible? (It definitely is SDK-side)

I'd be glad to test governance and staking if you can advise on the above issues.

**Comment by sabau** [comment]
Thanks for the insights!

Unfortunately the timing wasn't lucky. Yesterday we found this proposals/denominator error,

**Comment by jbibla** [comment]
@fedekunze did we split this?

**Comment by fedekunze** [comment]
@jbibla no, i don't think so

**Comment by jbibla** [comment]
0 - general local development issues (mostly resolved, also we moved to the web)
1 - notify's are alarming #2218 
2 - "Total stake" and "Available stake" can be confusing 
3 - ~Last commission change bug~ https://github.com/cosmos/cosmos-sdk/issues/3411
4 - ~we removed search~
5 - ~undelegation modal styling issues~
6 - ~improvements to form validation~
7 - transaction cursor shouldn't change to a hand https://github.com/cosmos/voyager/issues/2219

8 
> I wish the password entry were always a confirmation modal and very consistent, instead of being embedded in the pane with other fields - it's not clear that "Send tokens" will ask for additional confirmation (although it does), and other actions (e.g. submitting a proposal) do not ask for confirmation.

- though we're not using a modal - the password / signing experience should be more consistent now - and we're moving towards a multi step tx experience #1735 

9 
> I can't find a way to send multiple tokens at once in a single transaction. Is this possible? (It definitely is SDK-side)

no, this is not possible and we don't have plans to implement this feature (unless some users ask for it)

---

thank you so much @cwgoes! we've worked hard to address many of the issues you raised.
