### ISSUE TITLE
No Results msg on no validators

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1818]
Description:

When there are no validators, or the response hasn't been received (in my case because of `Unchecked runtime.lastError: The message port closed before a response was received.`), the Validators tab shows a No Results message. It should display a message that there are no validators on the network.

<img width="1395" alt="screen shot 2019-01-11 at 11 39 03 am" src="https://user-images.githubusercontent.com/31522760/51040234-b0adc780-1595-11e9-8510-05ae10d46ef9.png">

**Comment by faboweb** [comment]
It should show a message that the validators haven' been loaded yet in my opinion.

**Comment by faboweb** [comment]
@fedekunze sorry was asking so late but is there a way to reproduce this?
@sabau in theory this should be handled by your TmPage Pr, isn't it?

**Comment by fedekunze** [comment]
hmmm I don't remember how to reproduce it (not loading validators yet). But this issue was more about the message being displayed more than the not loading validators

**Comment by faboweb** [comment]
Got it tested. 👍 But thank you. :)
