### ISSUE TITLE
style in app notifications 

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#182]

**Comment by nylira** [comment]
Which notifications do you mean? I think the current notifications (generated from `this.$store.commit('notify', ...)` have a decent style already:

<img width="1392" alt="screen shot 2017-12-07 at 12 22 44 pm" src="https://user-images.githubusercontent.com/172531/33697253-5eca50aa-db49-11e7-9768-6ab71cef9614.png">

**Comment by faboweb** [comment]
I think the notifications have not enough contrast to be noticeable. A decent color coding would also be beneficial to the user to catch errors.

Design wise I prefer them simpler like in [Google Inbox](https://codepen.io/yahyaerturan/details/zBOKQL).

![image](https://user-images.githubusercontent.com/5869273/33708927-1921e8cc-db3c-11e7-9472-59553c737148.png)

Tagged the issue as IDEA to signal, that this is not a priority. (ok @jolesbi ?)

**Comment by jolesbi** [comment]
i agree with @faboweb — they can blend into the background. ideally, i'd like to see our "status" colours used everywhere they are applicable. 

- successful notify's should include some green
- unsuccessful notify's should include some red 
etc...

**Comment by faboweb** [comment]
Closing this as "oppinionated". Will reopen when surfaced by user.
