### ISSUE TITLE
Separate linting job on CircleCI

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1842]
Thanks to @fedekunze review I was thinking we have some low hanging fruits improvement:

- Separation of concerns: Having a separate job could make it easier to read the outcome.
- Fast failure: It allows us also to do static file check quickly and not even run other jobs if we know that this will fail anyway

**Comment by fedekunze** [comment]
we already agreed to implement this on the other issue (this is a dup)

**Comment by faboweb** [comment]
#1217

**Comment by faboweb** [comment]
#1221
