### ISSUE TITLE
Explorer: Block Detail

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#1867]
Description:
- Define how it should look: Page or Modal
- Should be accessible directly via URL (i.e. open on incognito tab to check)
- Implement and test

Subticket of: #1744

**Comment by jbibla** [comment]
> Page or Modal

page please!

**Comment by faboweb** [comment]
Should probably be consistent with: validator list > validator

**Comment by jbibla** [comment]
and proposal list > proposal
