### ISSUE TITLE
Optimistic updates: Proposal creation

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1875]
We need to update the proposal list and deduct deposits.

**Comment by fedekunze** [comment]
> We need to update the proposal list

If we do that we'll have to:

1. add the proposal (without id, tally, and others) to the state
2. on the next block the newly created proposal (with all properties) will be returned and we'll have to delete the previous one from the state

I propose to just watch for new block height on the proposal creation and call `getProposals`.

> deduct deposits

👍
