### ISSUE TITLE
missing transaction page no-data-message

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1879]
UI Version: 0.X.X

Description:

<img width="1188" alt="screen shot 2019-01-24 at 12 10 30 am" src="https://user-images.githubusercontent.com/6021933/51656014-47528f00-1f6d-11e9-8156-43500789c989.png">

**Comment by faboweb** [comment]
which branch? even after the TmPage PR by @sabau ?

**Comment by jbibla** [comment]
on latest develop - was his fix on web or develop?

**Comment by faboweb** [comment]
on develop I think

**Comment by jbibla** [comment]
this will be resolved when web gets merged into develop

**Comment by sabau** [comment]
the payload changed, PR almost ready to fix it (tests and mock as to be aligned)
