### ISSUE TITLE
switch from opt-in to opt-out for analytics

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1887]
> Because the user isn't able to opt in. 

i think we need to default to _some amount_ of analytics. i am very open to letting users opt out. re: cookies - we should investigate the requirements here more closely.

_Originally posted by @jbibla in https://github.com/cosmos/voyager/issues/1718#issuecomment-456448624_

**Comment by faboweb** [comment]
This is a prerequesit for removing the pref page

**Comment by jbibla** [comment]
i am having second thoughts about this

**Comment by fedekunze** [comment]
I think GDPR requires opt-in
