### ISSUE TITLE
google analytics event setup

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1888]
set up event tracking in google analytics

**Comment by faboweb** [comment]
This is already setup and is ready to be used for more events.

**Comment by jbibla** [comment]
GA is set up, but we are not passing events AFAIK.

we should consider something like: https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/event-tracking.md

**Comment by faboweb** [comment]
We are only tracking all page changes.

> we should consider something like: https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/event-tracking.md

we can, but should eval the benefit of a dependency if we only use a couple of it's features
