### ISSUE TITLE
ActionModal on smaller screens

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1897]
The `ActionModal` is pretty big. In the case of the `ModalPropose` is spanning more than 100% of the screen on my Mac. Can we improve the styling so it always fits? Google Inboxs modal is about half the size.

ModalPropose
![image](https://user-images.githubusercontent.com/5869273/51898126-8428e680-23b0-11e9-944b-4e8913d742db.png)

ModalSend
![image](https://user-images.githubusercontent.com/5869273/51898170-a6baff80-23b0-11e9-8de0-442a60d84494.png)

**Comment by jbibla** [comment]
#1735 can help make these smaller.

the result of #1871 may help as well.
