### ISSUE TITLE
Remove account_number and sequence

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1900]
Once https://github.com/cosmos/cosmos-sdk/pull/3396 is merge

consider closing #1736

**Comment by jbibla** [comment]
what is the impact of this change?

**Comment by faboweb** [comment]
probably none (less code on our side). it needs to be tested if stargate increments the sequence number correctly on quick sending of multiple txs.

**Comment by faboweb** [comment]
This is actually not possible as we need both properties to create signatures.
