### ISSUE TITLE
Bug in "Copied" for the address

### ISSUE THREAD

**Issue by zramsay** [cosmos/voyager#1910]
UI Version: latest web version

Description:

MacOS: works in Chrome, doesn't show up in Safari, works in Firefox but there is bad formatting

Safari does not copy or show that it is copied:
![screen shot 2019-01-30 at 12 16 47](https://user-images.githubusercontent.com/8304391/52000331-d9392b00-248a-11e9-810f-98c2c445819f.png)

Mozilla works, but see the formatting
![screen shot 2019-01-30 at 12 28 21](https://user-images.githubusercontent.com/8304391/52000366-f110af00-248a-11e9-942a-21d438367fd6.png)

**Comment by faboweb** [comment]
possible solution for copy to clipboard: https://gist.github.com/rproenca/64781c6a1329b48a455b645d361a9aa3

**Comment by jbibla** [comment]
@zramsay we just arrived in the browser - let the cross-browser issues begin 🏁 🏁 🏁
