### ISSUE TITLE
Add message on signing options

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1918]
i think (the action modals) should open but display a message that says you need to sign in to use them.

_Originally posted by @jbibla in https://github.com/cosmos/voyager/pull/1814_

**Comment by faboweb** [comment]
So the thinking here is that the modal is opening but stating that the user needs to sign in first?

**Comment by fedekunze** [comment]
I honestly don't think this issue is necessary, we already give the user the option to log in with the desired method to sign, which makes things pretty clear

**Comment by faboweb** [comment]
Yes we do. This is why I was asking if the issue means showing a "First Sign In" on ActionModals if the user is not signed in. Is that correct or does it mean sth. else?

**Comment by jbibla** [comment]
lol @fedekunze you quoted me and got it wrong #fakenews

<img width="667" alt="screen shot 2019-02-11 at 8 54 45 am" src="https://user-images.githubusercontent.com/6021933/52567608-c273cc00-2dda-11e9-8492-8a06af2e5125.png">

1. action modals should always open for users (whether they are signed in or not)
2. if the user is not signed in, the action modal should prompt the user to sign in

**Comment by faboweb** [comment]
#fakenews

**Comment by fedekunze** [comment]
> 2\. if the user is not signed in, the action modal should prompt the user to sign in

you mean change the action modal's body for a message to sign in ? @jbibla

**Comment by faboweb** [comment]
yes

**Comment by jbibla** [comment]
yep! like "Hey! CooL! You want to DeLeGaTe? Sign up here!"
