### ISSUE TITLE
Add Ledger instructions

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1920]
Description:

How to install Ledger Cosmos App through ledger Live
Maybe link to the delegator guide from Gautier on the Cosmos Docs

**Comment by fedekunze** [comment]
Agree, we should also add it. Maybe on the tutorial steps

**Comment by faboweb** [comment]
I propose we add it on the ledger sign in flow. Sth. like "Setup Ledger Nano S" or "I didn't setup my Ledger Nano S yet".

**Comment by fedekunze** [comment]
> I propose we add it on the ledger sign in flow. Sth. like "Setup Ledger Nano S" or "I didn't setup my Ledger Nano S yet".

👍. Although I'd still update the readme with the link as well
