### ISSUE TITLE
Ensure we're not displaying shares in a validator anywhere in the UI

### ISSUE THREAD

**Issue by cwgoes** [cosmos/voyager#1931]
Instead we should display current tokens of a particular delegation.

Might already not be an issue, just noting.

cc @jackzampolin

**Comment by jbibla** [comment]
will do! 

i proposed somewhere that we don't even send "shares" over the REST API. that might be a bit extreme but it seems kind of unnecessary for UIs to know about this and have to do the math on the client.

**Comment by jackzampolin** [comment]
@jbibla I think thats a pretty good idea. I've added an issue to the SDK to discuss: https://github.com/cosmos/cosmos-sdk/issues/3516 

I think the term is confusing enough that we should remove it from client returns.

**Comment by jbibla** [comment]
thank you @jackzampolin!

**Comment by faboweb** [comment]
I think we are not showing shares anymore anywhere

**Comment by jackzampolin** [comment]
@faboweb I don't know if we have pulled this out of SDK returns tho...
