### ISSUE TITLE
404 page displayed alongside with sidebar

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1949]
Should be rendered without sidebar. Also, is the styling wrong too ?

<img width="1373" alt="screen shot 2019-02-11 at 1 20 02 pm" src="https://user-images.githubusercontent.com/31522760/52562766-d8e04e80-2dff-11e9-8645-8ae24030d09b.png">

**Comment by faboweb** [comment]
> Should be rendered without sidebar.

Hmm, should it? Maybe remove the links on the 404 page and just add an arrow that points to the left?

**Comment by jbibla** [comment]
why would we hide the sidebar?

no, the styling is not _wrong_.

**Comment by faboweb** [comment]
why is it black?^^

**Comment by fedekunze** [comment]
> why is it black?^^

That was my though as well

**Comment by fedekunze** [comment]
> why would we hide the sidebar?

because you can now click on the back arrow on your browser to return to the prev page.

**Comment by faboweb** [comment]
On other 404 pages the navbar is hidden as well. Don't know if good or bad. See https://github.com/x/x

**Comment by jbibla** [comment]
being lost in the cosmos is BLACK.

i don't have strong feelings about any of this. happy to make some adjustments.

**Comment by jbibla** [comment]
closing for now :trollface:

**Comment by fedekunze** [comment]
![image](https://user-images.githubusercontent.com/31522760/52656493-cb59c000-2ef6-11e9-87f3-368796d2d365.png)
