### ISSUE TITLE
Cannot read property code of undefined

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1960]
Description:

Sending a transaction passes but renders an error on the modal:

`Sending tokens failed: Cannot read property 'code' of undefined`

<img width="690" alt="screen shot 2019-02-11 at 11 03 12 am" src="https://user-images.githubusercontent.com/31522760/52700724-eb31c800-2f78-11e9-8982-628bc9ef4a57.png">

**Comment by faboweb** [comment]
The return message changed and doesn't contain `{checktx, delivertx}` anymore.
