### ISSUE TITLE
tutorial background image oversized

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1981]
Description:

on [https://voyager-staging.interblock.io/#/](https://voyager-staging.interblock.io/#/) 

<img width="1679" alt="screen shot 2019-02-15 at 11 12 58 am" src="https://user-images.githubusercontent.com/31522760/52850032-d0935680-3112-11e9-95a6-901a0151ef0c.png">

**Comment by jbibla** [comment]
i noticed this too. i'm implementing autoprefixer to fix a lot of cross browser issues - hopefully this will be resolved by that.

**Comment by faboweb** [comment]
Not fixed with postcss PR

**Comment by jbibla** [comment]
i deleted this image. this is no longer an issue.
