### ISSUE TITLE
Design gas selection

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2008]
From #1721

AC:
- [x] have a design for gas assignment to transactions

**Comment by jbibla** [comment]
https://github.com/cosmos/voyager/issues/1721#issuecomment-466364606

https://zpl.io/blPdgg1

<img width="865" alt="screen shot 2019-02-22 at 2 51 34 pm" src="https://user-images.githubusercontent.com/6021933/53246568-61d57080-36b1-11e9-9da0-d76ace6f540c.png">
