### ISSUE TITLE
Design reward displaying and claiming

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2010]
Ref #1306 

AC:
- [x] have a design for displaying rewards
- [x] have a design for claiming rewards (action modal)

**Comment by jbibla** [comment]
Claiming all rewards at once:
<img width="1180" alt="screen shot 2019-02-22 at 10 04 52 am" src="https://user-images.githubusercontent.com/6021933/53231489-553d2200-3689-11e9-9ff2-68c8eb15a4e5.png">

Claiming reward action modal: 
<img width="1179" alt="screen shot 2019-02-22 at 10 50 33 am" src="https://user-images.githubusercontent.com/6021933/53234390-b8ca4e00-368f-11e9-8171-4e6aeef5182f.png">

Rewards on page validator:
<img width="762" alt="screen shot 2019-02-22 at 10 53 33 am" src="https://user-images.githubusercontent.com/6021933/53234629-3ee69480-3690-11e9-99dd-9fdcdd2eee8a.png">

Rewards on validator li:
<img width="850" alt="screen shot 2019-02-22 at 10 55 35 am" src="https://user-images.githubusercontent.com/6021933/53234697-6b021580-3690-11e9-8e0b-2a3247f49af5.png">

**Comment by jbibla** [comment]
@fedekunze

**Comment by fedekunze** [comment]
Note: You can’t withdraw a custom amount and  you can withdraw all your rewards (from all validators) at once or all from a specific validator

**Comment by faboweb** [comment]
I propose we only allow claiming all at once for now and implement the more specific version if requested.

**Comment by jbibla** [comment]
agreed. claim all or none at all. should still be an input on the action modal - just readonly.

**Comment by fedekunze** [comment]
> should still be an input on the action modal - just readonly.

This might not work as the amount displayed on the amount field can differ from the actual amount withdrawn (i.e displayed < withdrawn)

**Comment by fedekunze** [comment]
also imho I think showing the rewards on the header is a bad idea because of #2044. Also displaying it together with balance will bloat the header. It'd be better to have show and claim rewards on the wallet or  my delegations page, preferably on the former imo

**Comment by faboweb** [comment]
Let's go with Jordans solution for now and see where we can improve in a later iteration.

**Comment by faboweb** [comment]
> This might not work as the amount displayed on the amount field can differ from the actual amount withdrawn (i.e displayed < withdrawn)

is `withdrawn > displayed` so bad? :)

**Comment by fedekunze** [comment]
> Let's go with Jordans solution for now and see where we can improve in a later iteration.

Then we should fix #2044 first

**Comment by fedekunze** [comment]
But I think it's better to get it right now instead of refactor everything later on

**Comment by jbibla** [comment]
> This might not work as the amount displayed on the amount field can differ from the actual amount withdrawn (i.e displayed < withdrawn)

@fedekunze how would this work?

**Comment by jbibla** [comment]
> imho showing the rewards on the header is a bad idea because of #2044. Also displaying it together with balance will bloat the header. It'd be better to have show and claim rewards on the wallet or my delegations page, preferably on the former

i think balance and rewards are the two most important pieces of information for our users. perhaps the font size is too big, but this info is critical. let's leave it for now and see what it feels like when we actually have balances and rewards for a while.
