### ISSUE TITLE
Handle screensaver case on ledger connection

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#2015]
UI Version: 0.X.X

Description:

When ledger is displaying the screensaver it polls the device successfully (i.e calls `get_version` successfully) but it fails to call other "protected" cryptographic functions such as getting the public key or signing.

This causes to throw an error for public key `Unknown error code` but not for getting the version

Ref: https://github.com/ZondaX/ledger-cosmos-js/issues/12

**Comment by jbibla** [comment]
`Unknown error code` - could use a better error message
