### ISSUE TITLE
Connection indicator at wrong position on mobile

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2036]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5869273/53153626-0758e900-35b9-11e9-8979-050e35ceaf4b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbibla** [comment]
resolved.

![screen shot 2019-03-05 at 4 46 23 pm](https://user-images.githubusercontent.com/6021933/53839715-3d597e00-3f66-11e9-8ac2-6c1408c77b77.png)
