### ISSUE TITLE
Big numbers means big responsibilities

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#2044]
**Describe the bug**
Big numbers are not displayed nicely on the header with a 15" screen

**To Reproduce**
1. Login when you are rich AF
2. Look at your money and dislike the way they are printed, they make you look poorer

**Expected behavior**
See 19M or some other cool expandable shorthand that on hover or on click show the whole number

**Screenshots**
<img width="1023" alt="screenshot 2019-02-21 at 11 32 43" src="https://user-images.githubusercontent.com/1656471/53162536-84da2480-35cc-11e9-939d-a48d080dd4b7.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 72

We have to decide if the fix I suggest make sense for everyone and/or what else we can do to show massive numbers, the chain will grow so also block numbers will hit big numbers

**Comment by jbibla** [comment]
the SDK is going to send us Atoms, not uAtoms in the future... so this will be resolved when that is completed.

**Comment by fedekunze** [comment]
Lol this description is golden

**Comment by jbibla** [comment]
still @sabau is correct - we may have some millionaire-atom-hodlers who this will be ugly for.

**Comment by faboweb** [comment]
Other UIs just shorten the numbers at some point: `1000000` becomes `1m`

**Comment by jbibla** [comment]
ah true! 

1k, 1M, 1B

**Comment by jbibla** [comment]
still, we agreed to do the math until the REST API returns Atoms instead of uAtoms

**Comment by faboweb** [comment]
Let'S make big numbers font size smaller

**Comment by jbibla** [comment]
- [ ] add a class if long numbers
- [ ] do calculation for uAtoms

**Comment by jbibla** [comment]
i'd like to leave the font size as is for now - if this is an issue in the future we can add more dynamic font sizes. is that ok?
