### ISSUE TITLE
Still showing shares instead of tokens

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#2048]
**Describe the bug**
_A clear and concise description of what the bug is._

Page validator (and maybe LiValidator) is showing shares

**To Reproduce**
_Steps to reproduce the behavior:_

1. Submit delegation with X stake
2. Go to Validator page

**REST Request**: 
{"type":"auth/StdTx","value":{"msg":[{"type":"cosmos-sdk/MsgDelegate","value":{"delegator_addr":"cosmos160a2xkrnhk9tqfzklgrwv8nvlplxaa3eegmuz6","validator_addr":"cosmosvaloper160a2xkrnhk9tqfzklgrwv8nvlplxaa3euu0fwf","value":**{"denom":"stake","amount":"200001"}**}}],"fee":{"amount":null,"gas":"500000"},"signatures":null,"memo":""}

**Expected behavior**
_A clear and concise description of what you expected to happen._

Show tokens instead of shares

**Screenshots**
_If applicable, add screenshots to help explain your problem._

`My Delegation` is showing shares:

<img width="773" alt="screen shot 2019-02-21 at 6 27 03 pm" src="https://user-images.githubusercontent.com/31522760/53188743-58db9500-3606-11e9-904c-144a9226509e.png">

**Comment by faboweb** [comment]
I don't think this is true. We use the computed `yourVotes` which calculates shares to tokens. Maybe you thought this because of the `uatoms`?

**Comment by fedekunze** [comment]
`100200001 uatoms` are not `200001 atoms`

**Comment by faboweb** [comment]
`100200001` includes the string `200001`. this may have been an optimistic update error at the same. I can't reproduce the issue on `fabo/2044-big-numbers`

**Comment by faboweb** [comment]
@fedekunze changes are on develop now, this should be fixed. can you approve?

**Comment by fedekunze** [comment]
fixed on develop
