### ISSUE TITLE
Cache for static files

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#2061]
**Is your feature request related to a problem? Please describe.**

When we deploy to S3 the browser of users may have a version of index.html that does not reflect reality, we cannot expect them to hit refresh, it should work out of the box

**Describe the solution you'd like**

`Cache-Control: must-revalidate`
**Describe alternatives you've considered**

Disabling all the cache will kill performances, may work for develop, but never for production
**Additional context**

@greg-szabo

**Comment by faboweb** [comment]
@sabau remember to close issues when done. if you do so, they also automatically move into the done column.
