### ISSUE TITLE
Tally vote number report 100 000 000 for each vote

### ISSUE THREAD

**Issue by sabau** [cosmos/voyager#2063]
**Describe the bug**

In Governance the number of votes is multiplied by 100.000.000
**To Reproduce**

- Create a proposal
- Deposit enough
- Vote for it
- The number of votes will be 100.000.000

**Expected behavior**

- The number of votes will be 1
**Screenshots**

<img width="984" alt="screenshot 2019-02-22 at 14 55 37" src="https://user-images.githubusercontent.com/1656471/53246804-f0e28880-36b1-11e9-9369-cbc0b15d8486.png">

**Comment by fedekunze** [comment]
That’s the total power of the delegator. It’s displaying uatoms instead of atoms

**Comment by faboweb** [comment]
Do together with #2044
