### ISSUE TITLE
U2F Timeout in Chrome 72+

### ISSUE THREAD

**Issue by jleni** [cosmos/voyager#2077]
**Describe the bug**
Ledger has announced an incompatibility issue that appear in Chrome 72+. Using transport-u2f results in U2F TIMEOUT.

Their recommendations at this moment are:
- When U2F is used, migrate to other browsers not affected by the bug.
- Switch to webusb. They will provide more information about this in the next few days.

It is likely that it will be necessary to switch to webusb. 

We need to:
- Analyse the implications of switching
- Probably modify the ledger js library to use webusb instead. Most likely, the API will remain stable so Voyager should not be affected.

**Comment by jleni** [comment]
Ledger will apply a fix in their SDK that should resolve the issue without changes in Voyager.

Apps memory requirements have changed so I have submitted a PR at their request that includes this change.
Also we are submitting v1.1.0 that includes bech32 address explorer.
https://github.com/LedgerHQ/ledger-app-cosmos/pull/3

**Comment by jleni** [comment]
I have removed the webusb mention as it seems the fix will not require this.

**Comment by faboweb** [comment]
Is this actually a problem? Didn't hear complaints so far.

**Comment by jleni** [comment]
Referencing related issues here to facilitate tracking:
https://github.com/LedgerHQ/ledgerjs/issues/306
https://bugs.chromium.org/p/chromium/issues/detail?id=935131

It seems that Chrome has fixed the problem, but Ledger still keeps the issue open.

**Comment by faboweb** [comment]
Closing as this apparently is no bug.
