### ISSUE TITLE
Essay, for fun and accountability

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2090]
Reflection on why the sprint goal wasn't reached and how to reach it the next time.

**Comment by fedekunze** [comment]
do you think this contributes to the company's culture ?

**Comment by faboweb** [comment]
> do you think this contributes to the company's culture ?

yes ;P

**Comment by fedekunze** [comment]
strongly disagree

**Comment by sabau** [comment]
I won't really write excuses 🤣 but I think a post mortem is healthy. So here's mine:
I invested half a day into tendermint/gaia tagged image + tests on it, then I went into SRE discussions about networking and possible tools, the two combined consumed a couple of days out of 4 available. Finally I forgot the sprint was one day shorter 🎉
