### ISSUE TITLE
Dates on transactions are broken

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2104]
![image](https://user-images.githubusercontent.com/5869273/53429112-47223500-39ec-11e9-95a0-b54d190e1e2f.png)

**Comment by jbibla** [comment]
😭

**Comment by sabau** [comment]
I was going to add the same issue XD that's funny we fixed them not really long time ago

**Comment by fedekunze** [comment]
tendermint RPC's block endpoint changed 😃

**Comment by faboweb** [comment]
> tendermint RPC's block endpoint changed 😃

#whatelseisnew 🙈

**Comment by jbibla** [comment]
e2e will save us

**Comment by jbibla** [comment]
this was resolved
