### ISSUE TITLE
Hide My delegations and rewards on LiValidator on Explorer mode

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#2115]
**Is your feature request related to a problem? Please describe.**

They will always be `n/a`

**Comment by jbibla** [comment]
do you think it's better to hide them then to have `n/a` or `--` maybe with a tooltip that says you need to sign in or something?

**Comment by fedekunze** [comment]
there's already the tab that redirects to sign in. I'd just remove them, the same as we do with the balance header

**Comment by faboweb** [comment]
The idea is to not redirect to sign in but to show a message: "please sign in". One UX principal is to not hide content from the user, this would speak pro show the fields and mark them as `n/a`.

**Comment by fedekunze** [comment]
fixed on develop as they show `--`
