### ISSUE TITLE
Add more context to faucet button

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2134]
Currently the faucet button doesn't say much and doesn't give us feedback.

Expected:
The faucet button should have some more information about what is happening behind the scene, that it is rate-limited and that the tokens on the testnet are not worth anything.

**Comment by faboweb** [comment]
Also there are errors when using the faucet.
![image](https://user-images.githubusercontent.com/5869273/54120503-25677b80-43f8-11e9-806c-d8c9d4c17024.png)

**Comment by jbibla** [comment]
my proposal for self contained faucet UX:

1 - button that says "Get Test Tokens" (and is _maybe_ only visible when signed in _AND_ on a testnet). 
if always visible, clicking the button needs to prompt the user to create an account / sign in.
2 - on click, loader should be displayed inside the button
3 - if successful, show checkmark and return back to default button state. if failed, show error message somewhere ... not sure exactly about this.

alternatively, this could be an action-modal. probably should have been in the first place.

**Comment by faboweb** [comment]
We only get tokens once per account. Therefor let's display the "get token button" inside a "data-message-card" on the page wallet (only if signed in). when the user clicked it show loader as @jbibla proposed. then if successful it will vanish as the user has tokens already.

**Comment by jbibla** [comment]
> We only get tokens once per account.

ok cool. if that's the case, does the user need to click a button at all? can we just make this request one time for every new account on testnets?

**Comment by faboweb** [comment]
The new idea was:

When a user logs in, the user has no funds yet and a faucet is present a call to the faucet is automatically dispatched.
