### ISSUE TITLE
Ledger connection requires button

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#2154]
**Describe the bug**

While #1823 is on hold we should add a button to the ledger sign in. I've heard from users that the icon doesn't look clickable at all and thus they are waiting for some action to happen once they connect the ledger.

**Comment by jbibla** [comment]
can it check automatically instead of requiring a button at all?

**Comment by fedekunze** [comment]
> can it check automatically instead of requiring a button at all?

I thought we were doing that on #1823. Do you want to add that to the scope of this PR instead of the button ?

**Comment by faboweb** [comment]
Let's do the button first.
