### ISSUE TITLE
Fix position of activity indicator

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2161]
**Describe the bug**

On the network page and the validator page the colored dot that indicates the activity is not aligned well.

**To Reproduce**

Go to networks page

**Expected behavior**

Dot has more padding to the left

**Screenshots**

![image](https://user-images.githubusercontent.com/5869273/53794081-82ae8900-3f2f-11e9-9a74-b9e434851c62.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 72

**Comment by jbibla** [comment]
i believe this is fixed in #2125

**Comment by faboweb** [comment]
Nope:
![image](https://user-images.githubusercontent.com/5869273/53804489-f65c9000-3f47-11e9-85a5-3f2836ce199e.png)

**Comment by jbibla** [comment]
😭
