### ISSUE TITLE
Delegation warnings are broken

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2162]
**Describe the bug**

When I click on "Delegate" and I have no stakes a warning should appear but it doesn't.

**To Reproduce**

Go to validator
Click on Delegate

**Expected behavior**

Warning appears
or remove them #2043

**Screenshots**

![image](https://user-images.githubusercontent.com/5869273/53794524-74ad3800-3f30-11e9-9109-78d60b1c8f2a.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 72

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by fedekunze** [comment]
let's remove them on #2043

**Comment by fedekunze** [comment]
moved to #2043
