### ISSUE TITLE
Improve explorer mode

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2170]
**Describe the bug**

the wallet page is still blank and the tx page shows no transactions instead of the sign in card if the user not signed in
Do we even need to prompt right away for sign in?

**To Reproduce**

Sign in
Go to Wallet

**Expected behavior**

Show sign in card

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
wasn't your sign in card PR supposed to resolve this?

**Comment by faboweb** [comment]
I just added it as a fallback. Plus it apparently is missing on 2 pages. Might be my fault.
