### ISSUE TITLE
Throttle outgoing requests

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#2175]
**Is your feature request related to a problem? Please describe.**

Voyager makes requests on every block (transactions, rewards). Sometimes this can result in too many outgoing requests. 

If Voyager is disconnected, we also make requests every second to try to reconnect.

**Describe the solution you'd like**

We need a strategy for throttling outgoing requests to avoid using unnecessary resources for our users and to avoid spamming the Stargate APIs.

**Additional context**

**Comment by fedekunze** [comment]
I think we could start by querying the txs optimistically with a 6s timeout after we send a tx

**Comment by fedekunze** [comment]
instead of querying every block

**Comment by fedekunze** [comment]
ok we can subscribe to new txs [events](https://github.com/tendermint/tendermint/blob/develop/types/events.go) via Tendermint. I don't know yet if we can provide any other type of tag or address tho

**Comment by jbibla** [comment]
i'm not sure i understand your proposal @fedekunze. are you suggesting we subscribe to tx events in tendermint and query the REST API if there are new transactions?
