### ISSUE TITLE
Network blocks table shows header before any blocks are loaded

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#2183]
**Describe the bug**

The headers for the blocks table will be displayed for a couple seconds before the blocks are displayed. 

**To Reproduce**
- Hit refresh on the blocks page
- See the table headers floating without blocks

**Expected behavior**

Show a loading graphic while the blocks are loading

**Comment by fedekunze** [comment]
I don't think this is an issue. It's actually better to show the header than nothing. The only thing that I'd fix it the transaction counter, which is blank before blocks are displayed

**Comment by jbibla** [comment]
i have a simple solution.
