### ISSUE TITLE
Improve transactions design

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#219]
From @faboweb 

- [x] better border between transactions
- [x] stronger brightness for positive value
- [x] icon in first row always
- [ ] search for transaction index
- [ ] details view

BTW, what is search for transaction index? I was thinking search could be for transaction address.

dependencies: https://github.com/cosmos/cosmos-sdk/issues/318

**Comment by faboweb** [comment]
> what is search for transaction index? I was thinking search could be for transaction address.
I would just do a full-text-search as we have all the transactions locally.

**Comment by jolesbi** [comment]
blocked on https://github.com/cosmos/cosmos-sdk/issues/318

**Comment by faboweb** [comment]
Related to #366
