### ISSUE TITLE
Faucet doesn't work locally

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#2199]
**Describe the bug**

Clicking the faucet creates errors in the console.

**To Reproduce**
- sign in
- click faucet button
- see browser console

**Expected behavior**

- faucet works locally / is hidden while on localhost

**Screenshots**

<img width="388" alt="screen shot 2019-03-06 at 8 00 57 pm" src="https://user-images.githubusercontent.com/6021933/53924587-9995ce00-404a-11e9-84f6-ff39787a0832.png">

CC @sabau

**Comment by faboweb** [comment]
This is expected behavior. The faucet doesn't work locally but the button should show so we design around it.

**Comment by jbibla** [comment]
disabled then, maybe?

**Comment by faboweb** [comment]
hahahah ok, disabling is fine for me

**Comment by fedekunze** [comment]
disable + tooltip

**Comment by jbibla** [comment]
there is no button anymore.
