### ISSUE TITLE
Showing 3 zeros too much

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2204]
**Describe the bug**

On PageWallet we show 10 zeros. But we only have a precision of 7 zeros.

**To Reproduce**

**Expected behavior**

Only show allowed precision to not cause confusion.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by fedekunze** [comment]
closed by #2205
