### ISSUE TITLE
Error with very low amount txs

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#2216]
**Describe the bug**

Error when defining very low amounts on different types of transactions

**To Reproduce**

`Delegating failed: Request failed with status code 400`

1. redelegation amount:  `0.000000000000000000005`
```
Message: "shares must be > 0"
```
**Note**: actually this error is printed as CLI error with `/n`s:

`{"error":"ERROR:\nCodespace: staking\nCode: 102\nMessage: \"shares must be \u003e 0\"\n"}`

2. redelegation amount: `0.000000005`
```
message:"too few tokens to redelegate, truncates to zero tokens"
```

3. delegation: `0.0000000000000000005`

```
{"error":"failed to decode JSON payload: math/big: cannot unmarshal \"0.0000000\" into a *big.Int"}
```

**Expected behavior**

- `Delegating failed: Request failed with status code 400` should display the error message from the response instead of the error code.

- amount field should allow a minimum of `1e-7` for transactions

**Screenshots**

<img width="586" alt="screen shot 2019-03-08 at 12 02 21 pm" src="https://user-images.githubusercontent.com/31522760/54025183-0d92bc00-419a-11e9-83a0-0d187933b530.png">

**Comment by faboweb** [comment]
should be fixed with #2258
