### ISSUE TITLE
Persist session

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2224]
**Is your feature request related to a problem? Please describe.**

When I refresh I don't want to sign in again.

**Describe the solution you'd like**

My session is persisted in a cookie or the URL.

Persisting it in the URL makes this a very stateless change.

**Describe alternatives you've considered**

**Additional context**

**Comment by fedekunze** [comment]
Yes please !

**Comment by jbibla** [comment]
how would you persist this in the URL? by using the users address for every path?

**Comment by faboweb** [comment]
> how would you persist this in the URL? by using the users address for every path?

possible. the query stays active as the `vue-router` immediately adds the hash-bang with the internal route.
