### ISSUE TITLE
Opened Voyager and immediate panic

### ISSUE THREAD

**Issue by azulmarino** [cosmos/voyager#2229]
**Describe the bug**

Opened Voyager and got

The gaiacli rest-server (LCD) experienced an error: panic: resource temporarily unavailable goroutine 1 [running]: github.com/cosmos/cosmos-sdk/client/lcd.createHandler(0xc42011f1f0, 0x5, 0x7ffeefbffc89) /go/src/github.com/cosmos/cosmos-sdk/client/lcd/root.go:78 +0x634 github.com/cosmos/cosmos-sdk/client/lcd.ServeCommand.func1(0xc4207e9d40, 0xc42045ef00, 0x0, 0x8, 0x0, 0x0
**To Reproduce**

Open voyager
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave 10.14.2 (beta)
 - Browser: Safari
 - Version: 12.0.2

**Additional context**

**Comment by azulmarino** [comment]
log shows

localhost:9071" "--home" "/Users/dean/.cosmos-voyager/gaia-8001/lcd" "--node" "103.72.145.36:26657" "--chain-id" "gaia-8001""

I am running full node Gaia 13001

**Comment by fedekunze** [comment]
[https://beta.cosmoswallet.io](https://beta.cosmoswallet.io) has the latest features. We haven't updated it for Gaia-13001 yet. We're upgrading to 0.33 today (#2225)

**Comment by fedekunze** [comment]
> Opened Voyager and got

where you using the desktop version by chance ?

**Comment by azulmarino** [comment]
OK, at work now ... just having my tea break .I'll test tonight.
Is it safe to use my ledger app with my real Cosmos account ?
Using desktop.
Got the link from Christine in TG.

**Comment by fedekunze** [comment]
> Is it safe to use my ledger app with my real Cosmos account ?

You can use it to send query your transactions and submit some on the `local-testnet`. Although the audit reports haven't yet been released, it is safe to use your ledger. Make sure you have the latest version of the cosmos ledger app ( `v1.1.1`).

Also remember to **NEVER** paste your original mnemonic anywhere (not even on the dev mode which supports seed import).

If you find any bugs or UX issues please report them. We'd happy to hear your thoughts on the app !
