### ISSUE TITLE
Calculate fees for every transaction

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2230]
**Is your feature request related to a problem? Please describe.**

As a developer before implementing #2008
I want to know the fees needed for a transaction
So that I can implement the view layer.

**Describe the solution you'd like**

On every transaction calculate the fees (without displaying them  yet).

**Describe alternatives you've considered**

**Additional context**

AC:
- calculate the fees for a transaction before a transaction
  - simulate the gas with a request to stargate
  - calculate fees in atoms
- print the calculated fees to the console

**Comment by jbibla** [comment]
nice approach
