### ISSUE TITLE
Withdraw rewards transactions show empty "From" field

### ISSUE THREAD

**Issue by rsum1** [cosmos/voyager#2246]
**Is your feature request related to a problem? Please describe.**
In the "Transaction" tab, withdraw rewards transactions only show the word "From"

**Describe the solution you'd like**
I think this should either show as no text at all, or something like "Cosmos Hub" or "Fee Pool"

**Additional context**
I am using the website with a Ledger.

**Comment by jbibla** [comment]
thank you @rsum1!
