### ISSUE TITLE
contacts page / address book feature

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#225]
We should let users define key-value pairs for their commonly used send-to and receive-from addresses. Let's say they get wages every month in Atoms. They should be able to attach a label to their work address, e.g.

```
contacts: [
  {
    label: "work"
    address: "D29SDF234DSDSG33..."
  },
 ...
]
```

And later we can create profile pages for their contacts, letting the user see:

* how many coins they received over x years/months from that address (queried through the netmon or the local db)
* how many transactions occurred with that contact
* sweet-looking charts showing the above data

**Comment by jolesbi** [comment]
great idea. will likely have to wait until after launch.

**Comment by jbibla** [comment]
this is a great idea but we are not going to implement it any time soon. can be reopened if we hear it from our users.
