### ISSUE TITLE
Page preferences can be accessed from explorer mode

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#2259]
**Describe the bug**

Page preferences can be accessed from explorer mode

**To Reproduce**

1. Go to `https://localhost:9080/#/preferences` on explorer mode

**Expected behavior**

Should have a card for sign in required

**Screenshots**

<img width="1636" alt="Screen Shot 2019-03-13 at 5 44 22 PM" src="https://user-images.githubusercontent.com/31522760/54297761-c0f31a80-45b7-11e9-9484-670cb0a9804f.png">

**Comment by jbibla** [comment]
let's remove this page.

https://github.com/cosmos/voyager/pull/2255#discussion_r265245953
