### ISSUE TITLE
Use LCD websockets

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#226]
I as a user
Want to receive updates via websockets through the LCD
So that I see new information immediately.

Refreshing
- [ ] Balances
- [ ] Transactions
- [ ] Status Information

By @mappum:
> Would be cool to have a LCD websocket proxy that verifies proofs for every tx emitted from the upstream Tendermint full node. But until then, the UI could get the txs from Tendermint WS, and just use a LCD REST endpoint to verify the tx is in a block.

Extracted from #35 

dependencies: https://github.com/cosmos/gaia/issues/116

**Comment by jolesbi** [comment]
- [ ] balances
- [ ] transaction history

**Comment by jolesbi** [comment]
closed #41 — this ticket is now responsible for status information.

**Comment by mappum** [comment]
Having issues with the tendermint RPC subscription system (which the LCD websocket will be built on top of), so I opened an issue: https://github.com/tendermint/tendermint/issues/1099

**Comment by jolesbi** [comment]
blocked by https://github.com/cosmos/gaia/issues/116

**Comment by NodeGuy** [comment]
@faboweb If we want to use WebSockets then does it make sense to be refactoring the REST API?  Why not switch to WebSockets and deprecate the REST API?

**Comment by faboweb** [comment]
Should we do such a big refactor now? Let's prio this against our other milestones.

**Comment by jbibla** [comment]
this is a stale ticket
