### ISSUE TITLE
Show atom instead uatom on mainnet

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2272]
**Describe the bug**

We show `utam` but show atoms.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by jbibla** [comment]
where do we show uatom?

**Comment by faboweb** [comment]
everywhere we would show `stake` on the testnet
