### ISSUE TITLE
Commission Percentage is incorrect

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#2278]
<img width="138" alt="Screen Shot 2019-03-14 at 11 39 19 PM" src="https://user-images.githubusercontent.com/6021933/54406929-6c809580-46b2-11e9-8dc2-a6ba1844c201.png">

**Comment by fedekunze** [comment]
I think validator power (% of the network shares) is also wrong

**Comment by jbibla** [comment]
oy. let's make them right!
