### ISSUE TITLE
withdraw tx with ledger fails because of missing account number

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#2297]
**Describe the bug**

When a user tries to withdraw their rewards using the action modal, the tx appears to fail and states "missing account number"

**To Reproduce**

- click withdraw link in balance header
- attempt to claim existing rewards by submitting rewards action modal
- see error message

**Expected behavior**

- successful transaction should occur without errors

**Comment by fedekunze** [comment]
Opened #2299 #2298, maybe they can help us identifying these bugs due to unsupported versions

**Comment by jbibla** [comment]
mainnet. i don't think it's a version issue, though knowing that information will make debugging issues easier.

**Comment by faboweb** [comment]
I can't confirm this. Can you add reproduction steps?

**Comment by jbibla** [comment]
i will try to reproduce.
