### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#23]
As a user
I want to be able to add multiple accounts to the wallet
so that I can be more anonymous.

AC:
- [x] User is able to create another account
- [ ] User is able to select an account for global use
  - [ ] User is able to select an account for viewing balances
  - [ ] User is able to select an account for viewing transactions
  - [ ] User is able to pick an account for public communication (forum)
  - [ ] User is able to pick an account for nomination/delegation

Note:
- Are users able to remove an account?
- Should the selected account be prominently viewable at all times?

**Comment by faboweb** [comment]
Peng:
Perhaps this is a terminology issue we need to fix. The current UI is not going to have multiple accounts. Just one account with multiple coins.

**Comment by faboweb** [comment]
Peng:
In the case we want to support multiple accounts, we would need to integrate the `basecli keys new mykey` command. @mappum would know how to implement this.

**Comment by mappum** [comment]
When we suggested this feature, we *did* mean multiple accounts, not just
multiple coins on one account. The main reason was to make it possible to
import accounts which already have money on them (e.g. ones generated with
`basecli`).

Although, a single account definitely makes many parts of the app simpler,
so maybe a better solution would be for the import feature to simply move
funds into the app's single account. Or even just not supporting imports
and expecting the user to send their funds to their app's address outside
of the app.

**Comment by jolesbi** [comment]
since it is possible to have as many accounts as you'd like — i think it would be unfortunate to be stuck with 1 in the GUI — sounds like we should flesh out the pros and cons together 🌞 🇲🇽 🌴

**Comment by jolesbi** [comment]
from the meeting at Thompson Rooftop

- user must be able to choose which account to login with
- true multiple account support in the future

**Comment by jolesbi** [comment]
I think that this is going to be addressed by forcing the user to use the welcome screen before they access the app.

**Comment by faboweb** [comment]
I think the welcome screen only pops up initially right? After that, the user is "signed in".
This one addresses the creation of multiple addresses and being able to check out all of them.

**Comment by jolesbi** [comment]
yeah. so the welcome screen lets someone sign in with one address. if they want to sign out and sign back in with another address than that's ok. 

is this ticket about a feature where you can be "signed in" with more than one address at a time? does it have something to do with multiple asset types (ATOMS, ETH, BTC, etc...)?

**Comment by mappum** [comment]
>is this ticket about a feature where you can be "signed in" with more than one address at a time? does it have something to do with multiple asset types (ATOMS, ETH, BTC, etc...)?

Doesn't have to be multiple at a time, but at least the ability to switch. It's not about multiple asset types since one account can have multiple denominations. More about cases such as importing an old key from another device, or keeping a cold storage account on your Ledger, etc.

**Comment by jolesbi** [comment]
right! cool! so doesn't that mean we can rely on the welcome screen for handling everything to do with multiple accounts? or this feature is about switching between existing accounts very easily from within the app? is that the idea?

**Comment by mappum** [comment]
Relying on the welcome screen is easy enough for now. This requirement got brought up because the previous solution was to copy private key files around to switch keys, so anything is better than that.

**Comment by faboweb** [comment]
This is done via "sign out" -> "sign in" right?

**Comment by jolesbi** [comment]
yep. this is done!! 🎉 🌮
