### ISSUE TITLE
on refresh, balance header shows incorrect numbers

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#2303]
**Describe the bug**

- total atom balance calculation is off
- no delegations card appears even though there are delegations

**To Reproduce**
- log in with ledger
- refresh the page
- see total atom balance displayed with same number as "available"
- "no delegations" card appears even though there are delegations

**Expected behavior**

- i expect to see the correct atom total
- expect to see my delegations

**Additional context**
- re-rendering the page resets the data to be correct

**Comment by faboweb** [comment]
Seems fixed on develop

**Comment by jbibla** [comment]
not exactly. still showing 0.0000 for a second or two and then available balances for both total and available and then it updates to the correct balance...

**Comment by faboweb** [comment]
So should we only show the balance once wallet and delegation have been loaded?

**Comment by jbibla** [comment]
yeah, should be `--` before 0.
