### ISSUE TITLE
Redelegation amount is broken

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#2305]
**Describe the bug**

The amount on the redelegation tx in the transaction list is showing NaN.

**To Reproduce**

- redelegate
- go to page transactions

**Expected behavior**

it should show the correct redelgation amount

**Screenshots**

![image](https://user-images.githubusercontent.com/5869273/54481915-784b9380-483b-11e9-9443-44bcbbd24de8.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Safari
 - Version: 12.0.3

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by fedekunze** [comment]
I can't reproduce

**Comment by faboweb** [comment]
On develop:

![image](https://user-images.githubusercontent.com/5869273/54524201-9f0be600-4971-11e9-89a6-2e4bce92628b.png)
