### ISSUE TITLE
stop using trunk accounts to generate addresses

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#292]
this is added complexity that would be good to avoid if possible

```
{
    "name": "trunk",
    "address": "15632710B968836ADEA5816AB8900483ED35264D",
    "pubkey": {
      "type": "ed25519",
      "data": "AAA0C7660481E068DC616878B3480EA9B64B57693B213C7B0D31F478EDCA496A"
    }
  }
```

dependencies: https://github.com/cosmos/cosmos-sdk/issues/301

**Comment by faboweb** [comment]
We need this as long as there is no endpoint to just generate a seed phrase.

**Comment by jolesbi** [comment]
right. i thought this was something we were expecting from the LCD or the SDK...

**Comment by jolesbi** [comment]
https://github.com/cosmos/cosmos-sdk/issues/301

**Comment by faboweb** [comment]
This is already done
