### ISSUE TITLE
If gaia init fails app doesn't recover

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#334]
On starting the gaia we have to init. currently init breaks in some cases with a hash mismatch. In this case we procede to starting gaia but get an error that we need to init gaia first. On consecutive start of the app we never init gaia again.

**Comment by faboweb** [comment]
Just experienced it again:
![image](https://user-images.githubusercontent.com/5869273/36095560-f13ffb5a-0ff2-11e8-8bd3-57f63d89a9b5.png)

**Comment by jolesbi** [comment]
how do we get around this in the mean time?

**Comment by faboweb** [comment]
The user can remove the config folder. This "resets" the application.
My idea to simply solve this is to react to the specific error and init Gaia again.

**Comment by jolesbi** [comment]
closed by #438
