### ISSUE TITLE
the component file structure doesn't make sense anymore

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#351]
the file structure doesn't match the app anymore. 

- [ ] reorganize files and folders to match app

one option...
```
/common
/balances
/transactions
/delegates
/proposals
/validators
/blocks
```

vs.
```
/common
/govern
/monitor
/staking
/wallet
```

**Comment by faboweb** [comment]
The organization seems to be domain/module specific instead of navigation specific. But I have no strong opinion. Only thing: Don't remove the govern folder. :)

**Comment by faboweb** [comment]
Is this still an issue? How do you feel about this @nylira ?

**Comment by nylira** [comment]
Let's leave this as-is for now. It's not important, and we have to switch it again later.
