### ISSUE TITLE
Show bonding events in the Transactions page

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#355]
## User Story
Let's say Jocelyn B. open the Cosmos UI after a week of not using it. She remembers that she should have 10,000 ATOM (from participating in the fundraiser). But her Balances page only shows 5,000 ATOM. She checks the Transactions page and it says that she's only sent 1,500 ATOM from her wallet. So where did the other 3,500 ATOMs go? She freaks out and wonders if someone stole her balance.

Well, she staked it. But she completely forgot about doing that, because she has a busy life. It doesn't help that the UI doesn't have an easily accessible place to see where those ATOMs went.

## Proposal
We don't have an area in the UI where we show the history of user-initiated bonding events. I propose that we show bonding events as txs in the Transactions page.

**Comment by jolesbi** [comment]
poor Jocelyn! 

i absolutely agree. would love to see bonds considered tx's. i'm surprised they are not!

is this possible already or will it require changes to tendermint / sdk? @mappum ?

**Comment by jolesbi** [comment]
@mappum @faboweb ideally i think all transactions should appear in the tx history. is this possible?

**Comment by faboweb** [comment]
This is possible. We would need to switch on transaction type and need another design for delegation transactions.
But I want to question if this is the best way to display these information. The two transaction types have different contexts and it might information overload the user. If we decide to go this way, I propose we add at least filtering options to the transactions page.

**Comment by jolesbi** [comment]
we should consider including tx histroy on the send page and on the staking page (filtered by tx type). this is fairly common in wallets like coinbase where each denomination's "wallet" displays the total, some actions (buy, sell, send), and the corresponding tx history.

good points fabo. i think the tx histroy page (which should display all tx's with filters) can be done in a way where transaction types are obvious enough that it is not overloaded (see screenshot below as an example of multiple tx types in the same history).

![img_977af0c94936-1](https://user-images.githubusercontent.com/6021933/41857536-c1798f7c-7865-11e8-8ebf-86006c244d8c.jpeg)

**Comment by faboweb** [comment]
One additional challenge is, that delegation txs have some kind of time variable. I.e. unbonding only happens after x days and only after manually finishing the process (see #808)

**Comment by jolesbi** [comment]
> that delegation txs have some kind of time variable

my understanding based on #808 is that two tx's are required for unbonding. so we could / should show both. tx history should already include time and date. i think this is cool!

**Comment by faboweb** [comment]
emails would rely on a centralized system, wouldn't it?

**Comment by faboweb** [comment]
The endpoints are available on a newer SDK version. Note: I created suggestions to improve here: https://github.com/cosmos/cosmos-sdk/issues/1637

**Comment by fedekunze** [comment]
See #1010, we could use the current `Tags` being used at each module to check the tx type

**Comment by faboweb** [comment]
To clarify: This contains of implementing the designs from #913 plus querying the new /stake/delegators/{addr}/txs endpoint to get all txs, which are then shown in the tx-history.

**Comment by jbibla** [comment]
shouldn't block on tx designs - just use what we have already

but here is a first pass https://sketch.cloud/s/xKnxA/all/voyager-ui/transaction-history
