### ISSUE TITLE
Use real transaction UIDs

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#366]
Currently transactions do not have unique identifiers. Searching for transactions is difficult and we're having to rely on a id generator to list txs with unique keys. Implementing this issue is blocked on https://github.com/cosmos/cosmos-sdk/issues/318

- [x] allow searching for transactions with real tx hash
- [x] list transactions using real tx hash
- [x] filter out duplicate self transactions using real tx hash
~~- [ ] link to transaction details from `LiTransactions`~~

details (i.e.):
block,
addresses,
type

dependencies: https://github.com/cosmos/cosmos-sdk/issues/318

**Comment by faboweb** [comment]
This is now unblocked as the LCD returns the tx hash for each queried tx https://github.com/cosmos/cosmos-sdk/pull/1317

**Comment by nylira** [comment]
How do you query for a tx if you don't have the tx hash?

**Comment by faboweb** [comment]
You query by tag and get a list of fitting txs including their hash.

**Comment by nylira** [comment]
I liked @jolesbi's suggestion of having multiple wallets -- one for each coin. The top 20% lets you send and receive the coin, the bottom 80% is your transaction history for that coin. I think he's working on that wireframe.

**Comment by faboweb** [comment]
I thought this issue is about transaction uids?

**Comment by jolesbi** [comment]
> I think he's working on that wireframe.

it's true! i shared it with ya'll

> I thought this issue is about transaction uids?

yes, the points above would apply to any and all tx histories.

**Comment by faboweb** [comment]
Seeing the sketch I think it is not a good idea. I may want an overview over my coin sending behavior not just for one coin.

**Comment by jolesbi** [comment]
> I may want an overview over my coin sending behavior not just for one coin.

i would like to keep the full tx history page!

https://github.com/cosmos/voyager/issues/913
https://github.com/cosmos/voyager/issues/891

**Comment by faboweb** [comment]
As most of this discussion does not have to do with issue I will strip the scope of this issue and remove `link to transaction details from LiTransactions`
