### ISSUE TITLE
gamification of governance

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#377]
from @chjango: 

"What if we gamified governance in the UI to reinforce certain positive behaviors and foster a more engaged community? One example is this: low voter participation in governance has plagued many a DAO and no network has been able to solve this proactively within their protocol. The solution is so elegant and simple if we just gamified the UI and allowed people, for instance, to level up the more they voted, or the higher a person's proposal ranked, or if they got extra kudos for getting their proposal passed, etc..."

**Comment by fedekunze** [comment]
What is this for ? adding emojis and stuff ? @jbibla @Chjango

**Comment by jbibla** [comment]
this is more of a high level discussion - but this is out of scope for a few months at least. we can revisit after we have a centralized db and are working on governance2.
