### ISSUE TITLE
Create threat model document.

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#386]
Threat model diagram style guide: https://www.owasp.org/index.php/CRV2_AppThreatModeling#Data_Flow_Diagrams

**Comment by jolesbi** [comment]
- are there analytics options we can use?

**Comment by okwme** [comment]
* passcode persistent in storage
    * looking here for ideas but think it's the same thing https://github.com/MetaMask/KeyringController

**Comment by NodeGuy** [comment]
I'm waiting for Jessy to host a threat modeling meeting (https://allinbits.slack.com/archives/C8EN0L068/p1531289293000154).

**Comment by NodeGuy** [comment]
I'm also reading a book about threat modelling.

**Comment by NodeGuy** [comment]
Done: https://docs.google.com/document/d/1WOzU-518hsnScDvgbH6h8y2mb09LrzexTvUn7wISDZE/edit#

See also a new security issue generated as a result: https://github.com/cosmos/voyager/issues/1359

**Comment by fedekunze** [comment]
Marked as done
