### ISSUE TITLE
include two more button types

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#446]
i think it would be good to include a secondary button for our primary and danger buttons. i imagine this basically being the same border style but without such a strong background.

in this example below, the reset is too strong. i'd prefer if this button were a secondary button or a danger-secondary. @nylira what do you think?

<img width="822" alt="screen shot 2018-02-05 at 1 13 37 pm" src="https://user-images.githubusercontent.com/6021933/35821431-f7f883d0-0a76-11e8-9627-e7d7379cb355.png">

**Comment by nylira** [comment]
The alternative is that we replace the danger and warning buttons with a design that colors in the borders and text, but keeps the background dark. I prefer this for simplicity.

**Comment by jolesbi** [comment]
sounds great!!

**Comment by nylira** [comment]
This has been resolved by @NodeGuy's update all dependencies PRv#660 . The new `@nylira/vue-button` component changes danger and warning buttons to only have a border color.
