### ISSUE TITLE
PageBlock isn't displaying Tx data (when there is supposed to be data)

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#454]
https://medium.com/@speculatecoin/with-blocks-that-have-transactions-the-section-at-bottom-on-blocks-page-shows-no-transaction-data-aa163de6afcb

**Comment by jolesbi** [comment]
@mappum looks like we're using Tendermint RPC for this which is why the bytes are being returned. 

Block Height: 4976
`result.data.txs`
```
FgMBBmdhaWEtMgAAAAAAAAAAaQAAAAEBAQABBHNpZ3MBFE/o/+Eu26NL5OWHshJRd6wkWUuvIAEBAAEEc2lncwEUT+j/4S7bo0vk5YeyElF3rCRZS68BAQEHZmVybWlvbgAAAAAAAAPoAQEAAQRzaWdzARS0S3TaJt7YQM+nJg+1MooGWbCxMQEBAQdmZXJtaW9uAAAAAAAAA+gBLK39zzNOGXuERRoHD389Hd6hD3NRbxlhXF5RPjoPNTXv5kUkO74FXar4duTrYcXp+o1JfrnD+uzdQPPEwN3HAQHnPx4z7tR5Ldt/kKD5E9ZBGm9C4cAmgkdoSACD/NKFBw==
```

i can't tell if the LCD has an endpoint for tx data. do you know?

**Comment by mappum** [comment]
Just checked, looks like the LCD doesn't have a general purpose TX endpoint: https://github.com/cosmos/gaia/blob/v0.5.0/cmd/gaia/rest.go#L52-L76

Not sure what the timeline is for the new LCD in the new SDK, but we'll have to make sure we request an endpoint for the tx data. Until then, we could either backport an endpoint to the old LCD code which we are using, or not show the txs.

**Comment by jolesbi** [comment]
i created a ticket in the SDK repo. i think we have to move this out of the project until sdk is ready for it.

**Comment by nylira** [comment]
This has been implemented by @okwme in the cosmos/explorer repo. If we go ahead with #722 it'll make showing TXs in blocks in Voyager easier.
