### ISSUE TITLE
Feedback on current UI

### ISSUE THREAD

**Issue by gamarin2** [cosmos/voyager#461]
Hey! @jolesbi asked me to take a look at the UI and so I did! First I want to say that the UI looks amazing! Obviously I won't be detailing everything that is great, but I still wanted to say it before beginning the list of what could be improved.

Without further due, here is my feedback.

## Installation

I have installed the UI on develop branch following the instructions of the README. It went smoothly, I only have two minor points to raise:

- I would add `git clone https://github.com/cosmos/cosmos-ui` before `yarn`
- Not your fault, but following the instructions to install gaia on the README gives the following error `error Couldn't find a package.json file in "/Users/gamarin/go/src/github.com/cosmos/gaia"`. Not the first time I encounter it. Not really an error either, as ignoring it and continuing with the instructions works, but it could be confusing. 

## Account creation

Not much to say, it's great! I would add:
- Another message when creating account like "I understand that loosing both my password and my seed will result in the indefinite loss of my account" or something along those lines. 
- Enforce password confirmation when creating account https://github.com/cosmos/cosmos-ui/issues/468
- Maybe add a fourth login option to solve https://github.com/cosmos/cosmos-sdk/issues/381 (see my comment on the issue)

## Bottom of the UI

- Profile page is a bit difficult to find. Especially it was not intuitive for me to find the `Sign Out` button. Maybe put it on the top bar next to question mark icon?
- Bottom right IP should display a tip explaining what is is when we pass the mouse over it

## `Balances` section

- Would rename `Wallet` 
- Add info that only liquid assets are displayed
- Not intuitive to find how to send. Could be confusing for the user to just see "Address". What I would do is change the organisation of the top of the section. Instead of just having `Your address` with the address below, I would separate this whole field in two big buttons `Receive` and `Send`. 
- Would only show “Network denomination” of **Atoms + coins held by user**. (If user holds nothing, just show Atom with 0 balance). And under the list of coin with non-zero balances I would add a “Show empty balances” button, which would display the list of zero-balances network denom (list is hidden by default)

So the `Wallet` section would look like that:
- [RECEIVE] || [SEND]
- Balances                            [Refresh Icon]
    - Atoms: 0
    - Photons: 1
- [Show empty balance assets]

[] indicate button/icon

## ` Delegates` section

- Would rename `Stake` 
- Would reshape the section as follows (if this is not clear, please tell me and I'll try to clarify):
    - Your total staking power: X Atoms  [BOND] [UNBOND ALL]
    - Accumulated revenue: X Photons [CLAIM]
    - Your validators: (followed by a list of element <ValName | % of total network Stake | Total stake | Self-bonded stake | Your stake | [UNBOND]>)
- The [BOND] button would move the user to the `Validators` section
- When a user clicks the [UNBOND] button next to a validator he has bonded Atoms to, it would open a popup showing all the revenue its Atoms generated on this validator (X Atoms, Y Photons, Z ethers, etc.). Next to each asset the user would be able to  enter the amount of it wants to unbond. Then, a `TxUnbond` would be send for this validator and the amount of each asset to unbond. There should also be a button to unbond everything from this validator.
- User can click `UNBOND ALL` to unbond everything from all validators. Add extra warning there. In the background, multiple `TxUnbond` will likely have to be sent.

## `Validators` section

To me, this section serves two purposes:
- Bond to validators
- Monitor how many validators and validator candidates there are

So the display order is important. I would display as follows:
- First, display validators user is currently bonded to
- Then, display other validators in random order
- Then, display validator candidates in random order. Only validator candidates that declared candidacy less than X weeks ago are displayed (to avoid spam). If a candidate does not enter validator set before X weeks have passed, it has to send another `TxDeclareCandidacy` to show up in the wallet.

Information to display for each validator: 
<ValName | % of total network Stake | Total stake | Self-bonded stake | Your stake | [BOND]> (just like in `Stake` section, except there you can only bond).

## `Blocks` section

- Rename `Explorer` section?

## Top bar icons

Top bar is a bit confusing. Icons change with sections. Intuitively top bar should remain the same for each section. It took me quite some time to realize that the icons were changing depending on the section. What I would do is:
- Keep a static top bar on each section. There, I would put: Atom balance | [question mark] | Profile
- Incorporate the other icons (search/refresh) on the section itself. I think we can find a logical place for these icons on each section. For example, for the `Balances` section I would put the search bar/icon next to “Network denomination”. Search bar/icon should always be next to what is being searched, so that it is clear for the user what the search bar/icon is for. As for refresh icon, I think a more logical place would be at the far right in the box under “Denomination Balance” (this box displays “NA No data available yet” for me). I would also make it much bigger. Another example: in the Delegates section (that I would rename “Stake”), I would put the refresh button at the far right next to “Your Votes”.

That's it for now. If some comments are difficult to understand, please tell me so that I can clarify. Again, all these are only suggestions, and totally open for discussion. The UI is already amazing :)

**Comment by jolesbi** [comment]
amazing feedback @gamarin2 ! really appreciate the detail! we will definitely discuss with the UI team and implement. many great ideas! i agree with many of your points.

can you please draw or use software to show visually the layout you would like to see on the wallet section and the delegates? it's hard for me to understand your vision from words alone but a sketch or drawing would be very helpful. please include it here.

**Comment by gamarin2** [comment]
Here it is @jolesbi 

## Wallet section

![walletsection](https://user-images.githubusercontent.com/18440102/36026055-b8240316-0d95-11e8-9ac5-1c5e4fd75dc8.png)

## Staking section

![stakingsection](https://user-images.githubusercontent.com/18440102/36026063-c078481a-0d95-11e8-9070-581ff3a85f43.png)

**Comment by jolesbi** [comment]
Thanks very much @gamarin2 ! 

are the circles next to "Atoms" and "Photons" checkboxes?
