### ISSUE TITLE
proposal: rename cosmos-ui to voyager

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#472]
Let's rename this repository to https://github.com/cosmos/voyager

And all of the associated files in the same way:

```
package.json
README.md
etc
```

- [x] rename all the things

I'm pushing ahead on this issue instead of the sprint because we need to get the /voyager page up and running on the website.

**Comment by jolesbi** [comment]
i got confirmation from bucky, jim, and christine. they all thought it was great.
