### ISSUE TITLE
Signed setup files

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#476]
### Version
0.4.1

### Description
Greg stated again, that he would like to see setup files to distribute. He says, that signed setup files are state of the art and should have enough security to distribute.

Pulling in @greg-szabo

**Comment by nylira** [comment]
How Tor did it:
https://blog.torproject.org/deterministic-builds-part-two-technical-details

**Comment by okwme** [comment]
### Windows
 * Two Types
   *  Standard
   * EV (Extended Validation) takes longer, costs more, required for hardware products
 * Distributed on USB ([globalsign.com link](https://support.globalsign.com/customer/portal/articles/2705869-minimum-requirements-for-code-signing))
 * Location Required ([globalsign.com link](https://support.globalsign.com/customer/portal/articles/2705869-minimum-requirements-for-code-signing))
 * Timestamp from [here](http://rfc3161timestamp.globalsign.com/standard) required ([globalsign.com link](https://support.globalsign.com/customer/portal/articles/2705869-minimum-requirements-for-code-signing))
 * Can be bought from anyone listed here ([microsoft.com link](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#span-idstep2buyanewcodesigningcertificatespanspan-idstep2buyanewcodesigningcertificatespanspan-idstep2buyanewcodesigningcertificatespanstep-2-buy-a-new-code-signing-certificate))

### Mac
 * Need [Apple Developer Certificate](https://developer.apple.com/account/mac/certificate/)
 * Electron Signing ([electron-userland/electron-osx-sign link](https://github.com/electron-userland/electron-osx-sign))
 
### Electron
 * Electron Docs ([electron.build link](https://www.electron.build/code-signing))
 * Windows Installer ([electron/windows-installer link](https://github.com/electron/windows-installer))
* Mac Electron Installer ([mongodb-js/electron-installer-dmg link](https://github.com/mongodb-js/electron-installer-dmg))
   * Tutorial ([christianengvall.se link](https://www.christianengvall.se/dmg-installer-electron-app/))
   * Unable to sign ([issue link](https://github.com/mongodb-js/electron-installer-dmg/issues/26))
 * Uses squirrel for auto-updates and signing certs ([github.com/Squirre mac](https://github.com/Squirrel/Squirrel.Mac), [github.com/Squirre windows](https://github.com/Squirrel/Squirrel.Windows))
   * Windows needs to be run from a windows machine or VM
 * Auto-deploy tutorials
   * [pracucci.com link](https://pracucci.com/atom-electron-signing-mac-app.html)    
   * [medium.com/heresy-dev link](https://medium.com/heresy-dev/auto-updating-apps-for-windows-and-osx-using-electron-the-complete-guide-4aa7a50b904c)
 * Packing Tutorial ([medium.com/how-to-electron link](https://medium.com/how-to-electron/a-complete-guide-to-packaging-your-electron-app-1bdc717d739f))
   * Electron Builder ([electron-userland/electron-builder link](https://github.com/electron-userland/electron-builder)
   * Electron Packer ([electron-userland/electron-packager link](https://github.com/electron-userland/electron-packager))

### Other Links
 * Deterministic build that Tor uses ([devrandom/gitian-builder link](https://github.com/devrandom/gitian-builder))

**Comment by faboweb** [comment]
Nice writeup. Thank you.

**Comment by okwme** [comment]
Hurdles: 
 - We need to sign the mac app on an OSX machine.
 - We need to sign the windows app on wine or a windows machine. 
 - Mac would have the developer account that needs to be made by a cosmos/tendermint admin and then the private key would need to be managed somehow.
 - Basically the same would need to happen for windows, but they would be managing the private key on a USB stick.

**Comment by NodeGuy** [comment]
It looks like there are two separate problems to solve here:

1.  making a deterministic installer
2.  signing the installer

There's a lot of information in this issue about signing so I've created https://github.com/cosmos/voyager/issues/969 for the deterministic installer.

**Comment by faboweb** [comment]
Wait for decision on outsourcing

**Comment by faboweb** [comment]
We do not longer aim to ship an installable application.
