### ISSUE TITLE
Can't seem to unbond atoms

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#477]
### Version
develop

### Description
I have an account that has delegated fermions to three different validators. I'm attempting to unbond my atoms but I get this error:

```
Error sending transaction: bad nonce sequence, got 8, expected 9
```

![screen shot 2018-02-14 at 1 56 12 pm](https://user-images.githubusercontent.com/172531/36189810-8e869480-118f-11e8-8ee0-cbe977ffb533.png)

### Log
[main.log](https://github.com/cosmos/voyager/files/1722825/main.log)

**Comment by nylira** [comment]
Update: I tried unbonding from all three validators at once and it works. However, the process is incredibly slow. On the order of 30 seconds of waiting. And the UI does not tell me that something is happening in the background, I just have to have faith.

**Comment by NodeGuy** [comment]
Why is this blocked?

**Comment by NodeGuy** [comment]
https://www.youtube.com/watch?v=6Cs3Pvmmv0E

**Comment by NodeGuy** [comment]
I'm not seeing that error but I am experiencing a different one while trying to unbond.  This task will be  easier to diagnose once Pact is in place so I'll work on it after that.

**Comment by faboweb** [comment]
If the error is not there anymore, let's close this issue and open a new one.
