### ISSUE TITLE
Unify definition of binary path

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#480]
### Version
0.4.1

### Description
The definition of the path to the binary is different for building (using the "--binary" flag) and for setting a binary to be used by the main process (via BINARY_PATH environment variable). Maybe we should unify those.

**Comment by faboweb** [comment]
Which way do we solve this?
Advantage environment variable: Easy to access, easy to set via CI

Pulling in @NodeGuy for feedback

**Comment by NodeGuy** [comment]
Building is now hardwired—there's no longer a `--building` option.

**Comment by faboweb** [comment]
So we stick with environment variables only?
What should the naming be? I propose:
gaiacli: CLI_BINARY_PATH
gaiad: NODE_BINARY_PATH

**Comment by NodeGuy** [comment]
I propose we close this in favor of https://github.com/cosmos/voyager/issues/784.

**Comment by faboweb** [comment]
OK
