### ISSUE TITLE
Tx Tags are now encoded in Base64

### ISSUE THREAD

**Issue by ebuchman** [cosmos/voyager#485]
Updated gaia to latest Tendermint here: https://github.com/cosmos/gaia/pull/129

We're talking gaia 0.6 and tendermint 0.16 - for the gaia-3 testnet.

One thing that changed is the way we encode DeliverTx Tags - they used to be explicitly `string` or `int`, but now we use a generic [`KVPair`](https://github.com/tendermint/tmlibs/blob/develop/common/types.proto#L15) that uses `[]byte`, so everything is encoded as `base64` by JSON. Here's what the CLI output now looks like:

```
$ gaia client tx send --to 32102F807F4A9732F048E525DE82BE1FAA9C4CE3 --amount 10fermion --name mykey
Please enter passphrase for mykey: 
{
  "check_tx": {
    "gasWanted": "30",
    "fee": {
      "key": "Z2Fz"
    }
  },
  "deliver_tx": {
    "tags": [
      {
        "key": "aGVpZ2h0",
        "value": "MjY3"
      },
      {
        "key": "Y29pbi5zZW5kZXI=",
        "value": "MhAvgH9KlzLwSOUl3oK+H6qcTOc="
      },
      {
        "key": "Y29pbi5yZWNlaXZlcg==",
        "value": "MhAvgH9KlzLwSOUl3oK+H6qcTOM="
      }
    ]
  },
  "hash": "2F7703934DC7DA9FEDBE2F3544702002C35E4D5A",
  "height": 267
}
```

It's easy to decode these in python:

```
>>> "aGVpZ2h0".decode('base64')
'height'
>>> "MjY3".decode('base64')
'267'
>>> "Y29pbi5zZW5kZXI=".decode('base64')
'coin.sender'
>>> "MhAvgH9KlzLwSOUl3oK+H6qcTOc=".decode('base64').encode('hex')
'32102f807f4a9732f048e525de82be1faa9c4ce7'
```

And so on. Note the `height` is actually the string representation of the height - ie `"267"`. The addresses for coin.sender and coin.receiver are just the raw address bytes (length 20, normally encoded as hex)

**Comment by faboweb** [comment]
Thank you for the clarification!
We will patch this right now. But I think the parsing of the values to clear text should happen in the LCD. This is just one step less to think about for developers, working on top of the LCD. And everybody would need to decode client-side. Is this feasible?

**Comment by ebuchman** [comment]
Oh duh that's right - this should totally be an LCD thing.

**Comment by ebuchman** [comment]
https://github.com/cosmos/cosmos-sdk/issues/486

**Comment by faboweb** [comment]
Let's close this and handle the issue, when we migrate to gaia-3.
