### ISSUE TITLE
ux / usability notes (tyler)

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#494]
v0.4.0
- not obvious that the wallet is for sending and receiving if the user's balance is 0
- BUG: unable to update address balance
- first bar on bonding page is too strong - the red indicates an error / something bad happening but in reality, it is the intention of the user to bond some fermions. i would consider making this first bar more neutral. 
- we can hide unbonding bar if nothing is in the unbonding period
- sockets will be really helpful for ux 👍

**Comment by nylira** [comment]
> not obvious that the wallet is for sending and receiving if the user's balance is 0

This can be solved by implementing the step-by-step tutorial for first time users.

> BUG: unable to update address balance

Does nothing show up after clicking on the refresh button?

> first bar on bonding page is too strong - the red indicates an error / something bad happening but in reality, it is the intention of the user to bond some fermions. i would consider making this first bar more neutral.

Yeah, we can make this gray or something more muted.

> we can hide unbonding bar if nothing is in the unbonding period

Sure!

> sockets will be really helpful for ux 👍

Agreed, for more responsiveness.

**Comment by jolesbi** [comment]
> Does nothing show up after clicking on the refresh button?

yeah. couldn't get it to work. could have been a testnet / gaia issue. something to keep an eye on.
