### ISSUE TITLE
Enable users to connect to a certain node in the UI

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#504]
> Thank you for filing an issue!

### Version

0.4.3

### Description

Users may want to connect to a certain node (local node or private node). This is currently possible by using the COSMOS_NODE environment variable. But it would be easier and more accessible for users to archive this from within the UI.

**Comment by faboweb** [comment]
How about making the connected node more prominent (maybe in the menu or combined with the connection indicator) and let the user change the node by clicking that so the interaction fits the context better?

**Comment by nylira** [comment]
@faboweb Agree with that. I added a lot of design notes here for this feature https://github.com/cosmos/voyager/issues/732

**Comment by faboweb** [comment]
Closing in favor of #1312
