### ISSUE TITLE
Integrated fermion faucet

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#506]
> Thank you for filing an issue!

### Version

0.4.3

### Description

We saw that it is hard for users to start using the UI as it is hard to get tokens when starting using the app. We discussed the last time, that we want a way for users to get tokens (fermions) simple and fast.
A proposal was, to have an option in the application to get fermions on a button click.

**Comment by nylira** [comment]
I don't know if this has to be integrated, but we really need a working faucet sooner than later.

**Comment by nylira** [comment]
I vote for closing this issue. We have a great faucet at https://gaia.cosmosfaucet.network. It would be too much work to integrate it into Voyager.

**Comment by faboweb** [comment]
Users still need to go there and copy paste their address on that page. I think a integrated solution would lead to a better UX. But I am not feeling strongly about this.

**Comment by fedekunze** [comment]
Close this ?

**Comment by jbibla** [comment]
yes, we are not going to integrate a fermion faucet any time soon.
