### ISSUE TITLE
[Wireframes] Governance wireframes

### ISSUE THREAD

**Issue by gamarin2** [cosmos/voyager#509]
Here are the wireframes for the Governance section.

## Active proposal list

![activeproposallist](https://user-images.githubusercontent.com/18440102/36798050-d9990faa-1ca9-11e8-9c27-b204ee81a610.png)

- Proposed method of ordering: First, urgent proposals. Then, SoftwareProposals. Last, General proposals. Inside each category, order by remaining days. The less remaining days, the higher.
- The two progress bars are:
    - Yes/No ratio
    - All votes. The entire bar represents the total voting power. So it would give something like <Yes--No--NoWithVeto--Abstain--RemainingVotingPower>

## Pending proposal list

![pendingproposallist](https://user-images.githubusercontent.com/18440102/36798052-da70701c-1ca9-11e8-8457-8cbca00781e0.png)

- Pending proposals are submitted proposals that have not reached MinDeposit
- Here progress bar indicates the current deposit. The entire bar represents MinDeposit.

## Closed proposal list

![closedproposallist](https://user-images.githubusercontent.com/18440102/36798055-db54dc02-1ca9-11e8-9ecc-00ca60e3e42e.png)

- Proposals that have been either accepted or rejected. 

## New proposal

![newproposal](https://user-images.githubusercontent.com/18440102/36798056-db8c7d74-1ca9-11e8-8ec0-0696acf1ec6f.png)

- Deposit cannot be 0

## Active proposal 

![activeproposal](https://user-images.githubusercontent.com/18440102/36798057-dbab65f4-1ca9-11e8-8dff-24fef3cf3009.png)

- No comment

## Pending proposal

![pendingproposal](https://user-images.githubusercontent.com/18440102/36798059-dbcac552-1ca9-11e8-86ce-4272739779a9.png)

- No comment

## Closed proposal

![closedproposal](https://user-images.githubusercontent.com/18440102/36798060-dbe494aa-1ca9-11e8-81e5-cf93b42a7f2b.png)

- No comment

## Vote

![vote](https://user-images.githubusercontent.com/18440102/36798061-dc03de1e-1ca9-11e8-94a7-f13765a47fb6.png)

- User can either vote with all its voting power or vote differently for each validator it is bonded to. In any case, 1 transaction per validator as to be sent in the background.

## Deposit 

![deposit](https://user-images.githubusercontent.com/18440102/36798064-dc213bee-1ca9-11e8-9a9e-6251b7841b77.png)

- No comments

If you have any questions, don't hesitate! :)

**Comment by nylira** [comment]
Great wireframes. The functionality is clear and focused. This is basically how I imagined proposals in my head. @gamarin2 what did you have in mind with the NoWithVeto button and the yes/no bar? Should we have a third color to represent the third vote choice?

Here are a few things I thought about that aren't addressed in the wireframes:
* We'll want to allow searching for proposals by ID. Users may post about specific proposals on our subreddit or forum, and we'll want to give them an easy way to find the proposal in the app.
* Do pending proposals ever disappear after a while if the minDeposit is never reached? If they don't disappear, we're going to have to deal with a lot of spam proposals in the UI.
* What sort of extra fee do users have to input to create an urgent proposal? It must be a significant amount or all proposals will be urgent.
* What prevents users from creating Software Upgrade proposals for everything, in order to bump their proposal ahead of General Proposals?
* Are we going to have a report spam/abuse button for each proposal? If so, will there be a threshold of votes required before the proposal is flagged for deletion? Or does voting No NoWithVeto satisfy that function?

**Comment by gamarin2** [comment]
Thanks @nylira, great feedback!

For the NoWithVeto button, we have two choices. Basically what the NoWithVeto button does is cast a No Vote but also adds a Veto Vote. So it counts towards the No bar but if more than 33% of people vote NoWithVeto the proposal will be Vetoed. We have two ways of representing this:
- Yes/No bar + Veto bar (i.e. 3 bars in total)
- Yes/No/NoWithVeto bar. I.e. third color in the Yes/No bar (maybe the No bar is light red and dark red to represent No and NoWithVeto respectively)

I think I would favour option 2 to avoid bars overload.

Now for the rest of your points:

> We'll want to allow searching for proposals by ID. Users may post about specific proposals on our subreddit or forum, and we'll want to give them an easy way to find the proposal in the app.

100% agree

> Do pending proposals ever disappear after a while if the minDeposit is never reached? If they don't disappear, we're going to have to deal with a lot of spam proposals in the UI.

Yes, if they stay for longer than `MaxDepositPeriod` they get removed.

> What sort of extra fee do users have to input to create an urgent proposal? It must be a significant amount or all proposals will be urgent.

No Extra Fee. The way I would prevent people from abusing Urgent flag is to add a 5th vote option on urgent proposal (`Not Urgent`). In the background it would cast a `NoWithVeto` vote. If more than 33% of voters vote `Not Urgent`, proposal will be rejected and submitter will loose its deposit.

> What prevents users from creating Software Upgrade proposals for everything, in order to bump their proposal ahead of General Proposals?

I expect people to vote `No` or `NoWithVeto` if the proposal was submitted as Software Upgrade and was General. Then submitter would loose its deposit. Maybe we could add a hint somewhere to indicate that people should vote `No` or `NoWithVeto` if submitter used wrong type?

> Are we going to have a report spam/abuse button for each proposal? If so, will there be a threshold of votes required before the proposal is flagged for deletion? Or does voting No NoWithVeto satisfy that function?

Re: Previous point. It could be interesting, but people could just vote `No` or `NoWithVeto`. Maybe just add hint that if proposal is spam/not urgent/wrong type then people should vote `No` or `NoWithVeto`. Then submitter will loose deposit.

**Comment by nylira** [comment]
@faboweb I think I said that were weren't allowing proposal creation in the UI in the meeting yesterday. I forgot to check these wireframes -- it appears that we are allowing proposals to be created in the UI. Whoops!

**Comment by faboweb** [comment]
Thank you for the update!

**Comment by fedekunze** [comment]
Closing as @jbibla already did the final wireframes for the `governance2` milestone. For further feature proposals please add comments there
