### ISSUE TITLE
Justify requirement for unstable Node.js version.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#511]
### Version

0.4.3

### Description

`package.json` requires Node.js version >=9.4.0, which is not the current version "recommended for most users" (8.9.4 LTS).  If this is important then it would be good to explain why in the README, otherwise let's allow use of the stable version of Node.js.

**Comment by faboweb** [comment]
I updated this on false assumptions. Could you maybe check if the UI runs with 8.9.4 and create a PR do downgrade?
Also consider `.circleci/config.yml`.

**Comment by NodeGuy** [comment]
Yes, I'll do this once I get Voyager working on my machine.

**Comment by faboweb** [comment]
@NodeGuy still a thing?

**Comment by NodeGuy** [comment]
No longer a thing because v10.13.0 is now recommended for most users.
