### ISSUE TITLE
Consider starting with local network by default.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#512]
### Version

0.4.3

### Description

I see Voyager offering value in at least two ways:

* as a tool for sending, receiving, and bonding Atoms
* a means for visualizing the value proposition of Cosmos

The second way is important because while there is a lot of excitement about our technology, it can be tricky for people to get their heads around what a blockchain is and how blockchains can connect to each other.  It's easy for people to understand shovels and dump trucks because we played with models of them in sandboxes as children but blockchains in comparison are very abstract.

Voyager can be a sandbox that gives people an understanding of Cosmos in a fraction of the time it would take for them to read and grok the white paper.  If we see it as a tool to support learning then there is an important continuum to consider:

simple & predictable <-------> complex & powerful

To maximize the efficiency of learning we want to start people out on the simple & predictable side of the continuum so that a) it's easy for them to learn and b) we have more control over their learning environment.  Then we want to move them along the continuum to the other side because the learning of a tool is most useful when that tool can handle complex situations with a lot of power.

When dealing with complex networks in software, the best way to make them simple & predictable is via simulation.  This suggests another continuum:

1. local network simulation (total control & predictability, no dependency on outside networks)
1. a test net (simpler than a real network and so easier to understand; dependent on an outside network but nothing important is at stake, i.e., when making mistakes through play no money can be lost)
1. a real net (the training wheels are off and the full power of the tool is exposed)

Total control & predictability is not just beneficial for learning, it's also easier to for testing and delivering working software quickly.  This is important for us because our primary goal right now is capturing mind share and promoting adoption.  Please see my article [The Importance of Working Software](https://www.nodeguy.com/the-importance-of-working-software/) for more of my thoughts on this subject.

Let's ship Voyager to start with a local simulated net by default and then offer an option to switch to test and real networks later.  Our metric for success can be:

_Start a timer the moment a new user launches the Voyager application.  How many minutes go by before she understands the value proposition of Cosmos?_

At this phase of our development, anything that increases this time should be disabled/simplified/configured-automatically/simulated.

dependencies: #27 #541

**Comment by jolesbi** [comment]
wow. amazing idea @NodeGuy. i am strongly in favour of this gradual learning approach and appreciate the way you've laid out your thoughts on the subject. 

1. does that mean that we would need to ship gaia with voyager?
2. this ties nicely into https://github.com/cosmos/voyager/issues/27 (which we decided would wait until after launch, but i am happy to re-open this conversation)
3. ideally, this could be integrated nicely with the welcome / on-boarding flow

✌️

**Comment by faboweb** [comment]
I also have to strongly approve the laid out thoughts. :-)

My thoughts:
I assume the user expects the app to work out of the box. I haven't encountered a wallet (and I currently can't think of any other product) that works in a sandbox on launch and the user switches it to production after. This is not a problem because we said that our domain is brand new so we can/should try novel approaches. I would highlight very prominently that the user is working in a sandbox to not confuse the user.
I like the idea by @jolesbi to do this as part of the onboarding. Users could at the end of the onboarding decide to connect to a local testnet. Then users would have actively chosen to do this and are aware of it.
I also like the idea for the timer a lot. Our decisions should be based on data all the time! :) But I think it is important to find measurable goals. "understanding the value proposition of Cosmos" sounds to me very vague and not measurable. @NodeGuy did you have concrete measurements for this in mind?

> does that mean that we would need to ship gaia with voyager?
We are shipping Gaia together with Voyager in the production build. ;)

**Comment by NodeGuy** [comment]
> I also like the idea for the timer a lot. Our decisions should be based on data all the time! :) But I think it is important to find measurable goals. "understanding the value proposition of Cosmos" sounds to me very vague and not measurable. @NodeGuy did you have concrete measurements for this in mind?

Sorry, I wasn't clear.  I mean for that metric to be a thought experiment only to offer inspiration for design choices, not to be a concrete measurement.

**Comment by nylira** [comment]
Fabian taught this to me. We can enable the mock server by changing this line: https://github.com/cosmos/voyager/blob/ebc546c7082bca34de9c0782e0e74bb9bff40587/app/src/renderer/main.js#L45

From

```
 node = Node(lcdPort)
```

To
``` 
node = Node(lcdPort, true)
```

**Comment by nylira** [comment]
This is no longer blocked. What do you guys think? Should we do this now that we have a more stable testnet to connect to? I think we should prioritize being connected to a testnet if it's working, and only fallback onto the mock server.

**Comment by jolesbi** [comment]
if mocked server is on, i'd vote for hiding the sign out button so the user can't find themselves in a situation where they are logged out without knowing the password to the dummy account.

what about initial login?

**Comment by faboweb** [comment]
The signin issue was fixed by Peng.

**Comment by NodeGuy** [comment]
> This is no longer blocked. What do you guys think? Should we do this now that we have a more stable testnet to connect to? I think we should prioritize being connected to a testnet if it's working, and only fallback onto the mock server.

Now that I see our primary customers as contributors to the fund raise I see them as being more experienced and needing less hand holding with respect to onboarding.  I agree that we should offer the testnet by default if it's up.
