### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#515]
> Thank you for filing an issue!

### Version

0.4.3

### Description

Some of the data shown is not self explanatory. We want to add tooltips on hover/on tap for those. Identified items are:
- [ ] IP -> connected node IP

**Comment by nylira** [comment]
So these tooltips, I wonder if we're trying to solve the symptom instead of the problem. Maybe we can explain confusing parts of the site without tooltips, because they require discoverability?

**Comment by nylira** [comment]
Did some research and this lib looks good: https://hekigan.github.io/vue-directive-tooltip/

**Comment by jolesbi** [comment]
we already have some tooltips! 

<img width="281" alt="screen shot 2018-04-03 at 7 45 29 pm" src="https://user-images.githubusercontent.com/6021933/38281250-b2df104c-3777-11e8-8b76-bb16fb5992d5.png">

**Comment by nylira** [comment]
Yeah, I just saw that earlier too. 👍 We can reuse that style, but it still be helpful to use a library to resolve possible z-indexx issues and automatic tooltip placement so that it they aren't clipped off the screen.
