### ISSUE TITLE
Show note about only showing liquid assets

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#517]
> Thank you for filing an issue!

### Version

0.4.3

### Description

Voyager will only show liquid assets (not staked). We want to show a note so the user is aware of this.

Alternatively we can also show staked assets!

**Comment by nylira** [comment]
I think it's best to show staked assets too. Not a detailed table of how many Atoms are staked to each Validator, but just a "# of atoms staked" and then a link to view the user's current stake.

**Comment by faboweb** [comment]
Good idea
