### ISSUE TITLE
Rename "Validators" to "Staking"

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#519]
> Thank you for filing an issue!

### Version

0.4.3

### Description

We decided to rename the "Validators" page to "Staking" as "Staking" is a powerful known word in the context of "proof of stake".

**Comment by jolesbi** [comment]
from #464 - there is some discussion around using the work "Stake" vs. "Votes". Let's discus here.

```
makes sense to me
...
- % of Vote
- Total Votes
- Your Votes
```
```
makes less sense to me
...
- % of Vote
- Total Votes
- Your Stake
```

the word choice at the moment is Votes - so i think all the columns should say Votes. there is a separate discussion to be had about using "Staking" and "Stake" but i'd like to propose we merge this PR and open a new ticket for language (or use an existing one) if you feel so compelled.

though this is maybe a bad time to bring this up again, the purple bar doesn't make any sense to me and i wish it would be on the "% of Vote" column as a visual representation of the percentage.

<img width="766" alt="screen shot 2018-03-12 at 12 16 16 pm" src="https://user-images.githubusercontent.com/6021933/37280839-45191038-25ef-11e8-8a88-4b2455dde07f.png">
