### ISSUE TITLE
SPIKE Claim staking reward

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#520]
> Thank you for filing an issue!

### Version

0.4.3

### Description

As a user I want at some point be able to claim my reward for having staked my atoms.

**Comment by NodeGuy** [comment]
What is blocking this?

**Comment by NodeGuy** [comment]
@jbibla Please link your design here.

**Comment by NodeGuy** [comment]
Please remove issues from the backlog when moving them into Scrumptious.

**Comment by faboweb** [comment]
@jbibla probably wants to show the claim option in the rewards section of the design he posted. not to mixup with the "claim" button on the unbonding tx.

**Comment by jbibla** [comment]
> the "claim" button on the unbonding tx.

in the future, to be known as the "unbonding" button 😉

**Comment by faboweb** [comment]
Scope:
- Know how to "claim" rewards
- Know how to display rewards

Linking an active discussion of this: https://github.com/cosmos/voyager/issues/1285

**Comment by faboweb** [comment]
There is a tx for withdrawing all rewards [TxWithdrawDelegationRewardsAll](https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/distribution/transactions.md#txwithdrawdelegationrewardsall)
It is also possible to withdraw just from one validator which we can implement as a 2nd step.

We probably need to create an endpoint to query for rewards, as there is none right now or calculate it clientside. For calculating it clientside we still need additional information like `ValidatorDistInfo` and `DelegatorDistInfo` as seen in the wihdraw calculation done [here](https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/distribution/transactions.md#delegation-reward-withdrawal). I suppose just querying the calculated data is better as it leaves the logic on the SDK side.

As for updating the rewards, they are triggered on following events (taken from https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/distribution/state.md):
 1. delegation amount to a validator is updated, 
 2. a validator successfully proposes a block and receives a reward,
 3. any delegator withdraws from a validator, or 
 4. the validator withdraws it's commission.

**Comment by fedekunze** [comment]
Blocked by https://github.com/cosmos/cosmos-sdk/pull/2236, not yet implemented on the SDK

**Comment by fedekunze** [comment]
the implementation will take a while so I wouldn't consider adding it to this week sprint
