### ISSUE TITLE
Make search consistent

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#521]
> Thank you for filing an issue!

### Version

0.4.3

### Description

For consistency every top level page should have a search functionality.

**Comment by okwme** [comment]
![screenshot 2018-05-28 13 55 14](https://user-images.githubusercontent.com/964052/40613436-ca233d46-627e-11e8-930b-3ebc26feb142.png)
![screenshot 2018-05-28 13 54 58](https://user-images.githubusercontent.com/964052/40613437-ca4dcf98-627e-11e8-99ec-58e574c86747.png)

should they all have the "go" button like the block explorer?

should they stay open when a user navigates away and comes back, or should it reset like the block explorer?

wallet search filters "Available Balances". Should it be disabled when there are no balances available? should search in general be disabled when there's nothing to search?
