### ISSUE TITLE
Onboarding wizard

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#527]
> Thank you for filing an issue!

### Version

0.4.3

### Description

The domain of crypto is very new and strange to users. To archive a first class UX we want to have an onboarding wizard explaining most of the steps and functionalities to the user

**Comment by faboweb** [comment]
Draft first

**Comment by nylira** [comment]
I will work on this item this week, although I may not be able to finish it. I'll prioritize the other PRs first. I'll keep you guys updated.
