### ISSUE TITLE
Free atoms

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#531]
> Thank you for filing an issue!

### Version

0.4.3

### Description

Give away a fraction of atoms to users so that they can directly play around with actual assets.
Align this with Jea/Bucky.

Pulling in @jaekwon @ebuchman 

First comment by Jea:
- If we can prevent abuse then it sounds like a good idea. Maybe we can link it to Facebook.

**Comment by nylira** [comment]
First we'll have to support fractions of atoms and other tokens!

**Comment by faboweb** [comment]
Good catch!

**Comment by faboweb** [comment]
Adds a lot of complexity. We will have an onboarding on a local node with atoms there.
