### ISSUE TITLE
visualize issue dependencies

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#547]
I created this diagram to help me visualize the issue dependencies.  It's a snapshot taken on 2018-03-14 and I'm leaving it here for future reference.

![Alt text](https://gist.githubusercontent.com/NodeGuy/f5f657f949d1889cec2022c1b79d3850/raw/18363a76738f62a773246d690bffa2f9d0fa2724/dependencies.svg?sanitize=true)

**Comment by faboweb** [comment]
Good stuff :) Can we put this somewhere inside the repo? Or do you prefer having an open issue stating the current status?

**Comment by NodeGuy** [comment]
Thanks, I'd like to keep it here until it's more stable.
