### ISSUE TITLE
write up JS hiring task

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#550]
for JS candidates, we agreed on a task that combines both Lotion and Vue. HR would like us to write this up so they can share easily with candidates. i think the ideal outcome is a document that can be emailed.

✌️

**Comment by nylira** [comment]
Let's do it in tendermint/internal, if we care about making it a test. If the hiring task is publicized here people would have time to research the task and practice it multiple times before the real event.

**Comment by faboweb** [comment]
Closed by: https://github.com/tendermint/hiring/pull/228
