### ISSUE TITLE
Opt-in to remote error collection

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#552]
> Thank you for filing an issue!

### Version

0.4.3

### Description

We currently track errors remote via Sentry. As users might be upset that we collect data without them knowing, it may be good to make them opt-in to collecting data.

**Comment by jolesbi** [comment]
since we have security conscious / aware users, we should give them the option to opt in as opposed to not offering the option.

**Comment by nylira** [comment]
This should be in the user settings if the user wants to change it later. We'll also want to integrate it into the sign in / create account flow, around the create password section.

**Comment by faboweb** [comment]
Thanks for sharing your thoughts. I would implement it, like you proposed and store the option in localstorage.
