### ISSUE TITLE
Make it easy to run Voyager against a develop version of the Hub.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#557]
Today when @adrianbrink is working on a develop version of the Hub it's clear how to run the CLI against it but not Voyager.

Create a smooth path to running Voyager against local Hub code, e.g., by writing documentation, and check the results with @adrianbrink.

**Comment by faboweb** [comment]
I am not sure I understand correctly. I rephrase: I as a developer want to use Voyager on the Network "Cosmos Hub".

**Comment by jolesbi** [comment]
sorry @NodeGuy, i don't understand.

**Comment by NodeGuy** [comment]
Rephrase:

"I am Adrian.  I am working on Hub and want to test my new code with Voyager.  I don't know how."

**Comment by faboweb** [comment]
So I clarified with Adrian:
He want's to connect to a specific node. We have the `COSMOS_NODE` environment variable for that. It is in the documentation, but maybe we need to make it more prominent.

**Comment by NodeGuy** [comment]
Thank you, it sounds like it's solved to me.
