### ISSUE TITLE
Fix the MaxListenersExceededWarning spam

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#561]
### Version
`develop`

### Description
We're getting spammed with the following line in CircleCI builds. It comprises nearly 50% of the build log which makes it harder to find out what is wrong.

```
Remove (node:215) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit
```

Let's increase the max listeners.

### Screenshot

![circleci](https://user-images.githubusercontent.com/172531/37609294-08c8fd38-2b9d-11e8-9400-e75c3c274b60.png)

**Comment by faboweb** [comment]
You are so right! We need to kill those damn messages :)

**Comment by mappum** [comment]
I would say that we should actually diagnose and ensure there isn't a memory leak, but it looks like it never goes above 11 so it's probably OK to just increase the limit 👍
