### ISSUE TITLE
yarn test:e2e fails if BINARY_PATH isn't set

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#574]
### Version
0.4.3

### Description
```
$ yarn test:e2e
...
TAP version 13
# sign in
using binary undefined
ui home: /var/folders/wj/0h36fvtj03q0y9lf0n9c0nxc0000gp/T/1fyqfh932ug
node home: /var/folders/wj/0h36fvtj03q0y9lf0n9c0nxc0000gp/T/6pw1z457nm/baseserver
unhandledRejection TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:493:38)
    at Promise (/Users/david/Documents/Tendermint/voyager/test/e2e/launch.js:119:17)
    at new Promise (<anonymous>)
    at startLocalNode (/Users/david/Documents/Tendermint/voyager/test/e2e/launch.js:118:9)
    at Promise (/Users/david/Documents/Tendermint/voyager/test/e2e/launch.js:37:13)
    at new Promise (<anonymous>)
    at launch (/Users/david/Documents/Tendermint/voyager/test/e2e/launch.js:28:15)
    at /Users/david/Documents/Tendermint/voyager/test/e2e/signin.js:10:21
    at Test.<anonymous> (/Users/david/Documents/Tendermint/voyager/node_modules/tape-promise/index.es5.js:24:17)
...
```

The README doesn't mention the need to set BINARY_PATH but it's used here:

https://github.com/cosmos/voyager/blob/2d30d385cacc0cf1830cd7738ab0c5d2074d0056/test/e2e/launch.js#L12

Could we use the version of Gaia found in the `PATH` instead of requiring the user to set an environment variable?  Normally I expect `yarn test` to Just Work out of the box without requiring extra configuration of my shell.

**Comment by jolesbi** [comment]
++

**Comment by faboweb** [comment]
We can default to the PATH gaia. But we need to provide the possibility to define the path name as the e2e tests run mainly on the CI.

**Comment by NodeGuy** [comment]
How about we put Gaia in the path on the CI?

**Comment by NodeGuy** [comment]
Works for me.

**Comment by NodeGuy** [comment]
Oh, it looks like there's already code to use Gaia in the `GOPATH`:

https://github.com/cosmos/voyager/blob/edffe993505b37837defc73453d36161b3abc9a5/app/src/main/index.js#L156-L159

It's not activating because `NODE_ENV` isn't set for the E2E test.

**Comment by NodeGuy** [comment]
Looks like we have a regression:  Now we need two environment variables to be set in order for `yarn test:e2e` work:

> you can try to run `BINARY_PATH=$(which gaiacli) NODE_BINARY_PATH=$(which gaiad) yarn test:e2e`

@mappum Can we go back to the glorious days of `yarn test:e2e` working?
