### ISSUE TITLE
Show error "Genesis has changed" to the user.

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#611]
> Thank you for filing an issue!

### Version

---

### Description

Currently Voyager just shows a generic error in this case.

**Comment by faboweb** [comment]
Also version mismatch errors

**Comment by jolesbi** [comment]
why would the genesis change? what is the use case?

**Comment by faboweb** [comment]
On testnets i.e.. In production chains this should not happen I guess

**Comment by faboweb** [comment]
Flow: init Voyager -> close voyager -> Genesis on GitHub changes -> reopen Voyager -> Genesis that is stored locally mismatches the one on GitHub

@mappum why could this happen? And could we just accept the new genesis?

**Comment by okwme** [comment]
happened to me
