### ISSUE TITLE
Make Prettier CI check generate more meaningful error message if files not compliant.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#622]
See https://github.com/hexacta/prettier-check

**Comment by nylira** [comment]
+1, this would be a great quality of life improvement for passing our linter.

`yarn lint` needs to give us better error messages. Right now we only know the file where a formatting error exists.

**Comment by nylira** [comment]
@NodeGuy I've changed my mind. Especially with @faboweb's precommit hook to run Prettier, this shouldn't be much of a problem. We can close this.
