### ISSUE TITLE
Have a toggle to show all available denominations on the network

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#636]
### Description

Implemented in #633 we hide all tokens a user has a balance of 0 in. The reason is to reduce visual clutter.

But maybe the user wants to see, which tokens are available on the network (to be evaluated). For this case, it would be nice (and this was decided in the original design) to have a toggle that shows all denominations.

Ref https://github.com/cosmos/voyager/issues/461#issuecomment-364410672

**Comment by fedekunze** [comment]
moving this to #1586
