### ISSUE TITLE
Back Button Bug Hunt

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#655]
### Version
0.5.0

### Description
It's confusing to have a back button on the Wallet page when you first sign in. There's nowhere to go back to. I know we had this discussion before, but I argue that we should remove the back button from all the pages. (If not all, then all of the top level pages).

**Comment by jolesbi** [comment]
ahh! it just goes back in history - so what happens? does it bug out? does nothing?

**Comment by nylira** [comment]
It doesn't do anything. We should just have it greyed out with no hover or click actions.

**Comment by jolesbi** [comment]
the back button discussion has re-emerged. i believe we are seeking a solution to the following problems.

1. when the user initially signs in or when the user is at the beginning of their browsing history (when there is no where to go back to) the button should be disabled. 

2. when on the `PageBlock` page, there is a forward and back button for navigating through blocks. the back button is basically redundant here - as it behaves the same way as the `PageBlock` back button.

3. some people expect the back button to be on the left as it would be in a browser... but there is an argument that the back button shouldn't mimic the browser button because the URL is not present.

4. proposals will be a few levels deep. ideally, users will be able to use a back button to go up one level at a time - but many of our other pages do not have this kind of depth.

**Comment by jolesbi** [comment]
@nylira please take a look at #1 - i was not able to find a *simple* solution.

**Comment by faboweb** [comment]
Would a consistent "one level up" button (it would not be a back button) that hides when at top level solve these problems?

**Comment by nylira** [comment]
Responding to @jolesbi 

1. If we cannot disable the back button on sign in -- it's okay, we can give up on this issue.
2. The back and forward buttons on the page block page let you traverse through the history of gaia blocks. They are entirely separate from the Back button discussion. I propose a block timeline where we have a bar and a scrubber that lets you move between historical blocks with a more fluid UX than only the granular back/forward.
3. If we move the Back button to the left side of the page, it will solve the confusion of `2.` ^ I like having the idea of a standard browser back button in Voyager, even if there is no URL. Think of your smartphone usage. Do you look at the URL field before you decide to press or swipe back? Most mobile browsers truncate the URL field.
4. Other pages do not have that sort of depth now, but they will later. Examples:

* Staking Page -> Validator Profile "Jon Valy" -> Validator's Proposals
* Blocks Page -> Block #1337 -> Block Transactions (133 total) -> Transaction 133
* Proposals Page -> Proposal "Give Me 10MM Atoms" -> Vote Breakdown

I vote for keeping the back button, moving it to the left. And for deep navigation, let's add a breadcrumb like this:

<img width="618" alt="screen shot 2018-06-06 at 2 57 41 pm" src="https://user-images.githubusercontent.com/172531/41021721-010fc316-699a-11e8-8160-a766fa70707e.png">

**Comment by jolesbi** [comment]
> Would a consistent "one level up" button (it would not be a back button) that hides when at top level solve these problems?

i think so! 

@nylira are you ok with fabo's idea? i am on board with what you are proposing - but it is more involved.

**Comment by nylira** [comment]
Yeah, I think it's a move in a good direction.

**Comment by jolesbi** [comment]
investigate bugs - watch out for ux rabbit holes 🐰

**Comment by okwme** [comment]
The only back button error I could find was when hot reload was used in development. This would enable triggering the sign in page to appear. This does not appear possible in normal use of the app. Furthermore the history is not available, even with `mode: 'history'`. What is possible (if desired for the disabled back button) is that we could keep track of the history manually with one of the router callbacks like:
```
beforeRouteEnter (to, from, next) {
    next(vm => {
      // log some data in local storage or somewhere
    })
  }
```

**Comment by okwme** [comment]
Not a Back Button Bug But sth else:
1. sign in to account w steak
2. nav to anywhere only accessible by stake holders (for ex Delegation)
3. sign out
4. sign in to account w no steak
5. land at delegation screen you got no business at

will make a new issue

**Comment by okwme** [comment]
https://github.com/cosmos/voyager/pull/938
https://github.com/cosmos/voyager/pull/935
