### ISSUE TITLE
Multiple back buttons

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#665]
### Multiple back buttons

Click 'Staking'
Click 'mr_mounty'
Two back buttons present

OR

Click 'Proposals'
Click first proposal
Two back buttons present

**Comment by nylira** [comment]
Closed by #674

**Comment by nylira** [comment]
@okwme next time write "closes #665" to automatically close an issue in your PR.

**Comment by okwme** [comment]
@nylira 👍
