### ISSUE TITLE
competition comparison spreadsheet

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#68]
- build comparison sheet for other UI's / wallets so we know where we stand in the market

**Comment by jolesbi** [comment]
https://docs.google.com/spreadsheets/d/1yjtQ5_SyOI6VJ6PZYiFrWhzikpyjFWK__drjVUVS2DE/edit#gid=0

**Comment by jolesbi** [comment]
@faboweb though i think this would be great to have, i'm not sure i can justify spending time on it pre-launch. our pre-launch feature set is already fairly well defined and there is a lot of work to do in preparation for launch.

what do you think?

**Comment by faboweb** [comment]
Good question. Maybe we miss sth. important we don't see yet. Investing a little could be beneficial.

**Comment by jbibla** [comment]
the doc lives in google drive - not sure if we need this open issue anymore

**Comment by faboweb** [comment]
The sheet holds no real data. And I think we need this.

**Comment by fedekunze** [comment]
Closing as we’ll use the benchmarking on Notion
