### ISSUE TITLE
Support recovering accounts again with the new SDK.

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#682]
### Version

0.6.0 (once #591 merges)

### Description

The old method of recovering accounts does not work any more:

> Peng Zhong
> Can we recover accounts with the gaia-5000 gaiacli? `gaiacli keys add pengz --recover "my twelve words go here"` gives me the error `ERROR: You must provide a name for the key`

We have to follow a new method:

> Ethan Buchman
> your 12 words dont go there
> just `gaiacli keys add pengz --recover` and then follow the prompts

These are the relevant lines: https://github.com/cosmos/voyager/blob/d45f0a69063c747056a6d5bc456407be32595446/test/e2e/launch.js#L188-L207

- [ ] support recovering accounts

**Comment by faboweb** [comment]
fixed in #684
