### ISSUE TITLE
light theme broken

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#685]
> Thank you for filing an issue!

### Version

Commit: d7096b3609e22eeb3db77ada76e92727af942ea1

### Description

The text in the buttons is not readable:

![image](https://user-images.githubusercontent.com/5869273/39915276-c874381c-5507-11e8-9d17-3e4924087c88.png)

**Comment by okwme** [comment]
i checked out the specific git, cleared the node_modules and installed them again  
```
git checkout d7096b3
rm -r node_modules
yarn
COSMOS_NODE=localhost yarn testnet
``` 
this all gave me a version of voyager where the text is visible:  
![screenshot 2018-05-14 15 12 39](https://user-images.githubusercontent.com/964052/39999450-6e77d100-5789-11e8-93fa-e00ed2385682.png)

is it possible you have some mismatch in a styling module?

**Comment by faboweb** [comment]
Thank you for checking this. I will try to clear node_modules.

**Comment by nylira** [comment]
I know the issue, will fix it.

**Comment by nylira** [comment]
The issue was that I updated the `@nylira/vue-buttons` to support full color primary buttons, but Voyager still included the hack to turn the background of primary buttons to white. Thus white text on white bg, and nothing was visible.
