### ISSUE TITLE
Voyager doesn't recover from an error while sending coins

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#694]
> Thank you for filing an issue!

### Version

Commit 220397c93f1555e89971181e4c1a2cc929954de3

### Description

When a sending transaction fails, all following transactions do not produce REST requests.

@mappum maybe?

**Comment by NodeGuy** [comment]
What's the best way to reproduce this?

**Comment by okwme** [comment]
`lock` is still returning the same rejected promise in `/vuex/modules/send.js` in the `sendTx` action.

to reproduce go to wallet -> send and turn off your internet before trying to send some coin. then turn internet back on and try to send again @NodeGuy

**Comment by NodeGuy** [comment]
Nice find, @okwme!
