### ISSUE TITLE
SPIKE: Combine cosmos/voyager, cosmos/explorer, websites, and `ni-*` components in monorepo

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#696]
### Version

0.5.0

### Description

Combining these interrelated projects would help solve integration issues like #685, #689, cosmos/explorer#1, cosmos/explorer#2, tendermint/tendermint.com#151. There have been many other integration and component update issues over the past couple years that would be solved by this.

It will also be the biggest single step towards universal, theme-able, and reusable vue components for all Cosmos projects.

We can reuse this Voyager repository or we can make a new one, I think there are arguments both ways. Reusing the Voyager repo lets us retain our valuable SEO and hard links. We can rename this repository if we want to, and GitHub will forward all requests to the new repository name. The alternative is a brand new repository--we will definitely need a name for this. I'm open to suggestions.

### Steps to Monorepo

Here are all the steps needed to accomplish this. We can attempt this one step at a time, it doesn't all have to be in one sprint. Combinging cosmos/voyager and cosmos/explorer is a significant one, because cosmos/explorer (in general) is using an old version of cosmos/voyager components.

- [x] combine cosmos/voyager and cosmos/explorer: e.g. `mono/voyager` `mono/explorer` `mono/components/`
- [ ] add `@nylira/vue-*` components  to monorepo under `./components`
- [x] add cosmos.network to monorepo
- [x] add tendermint.com to monorepo
- [x] add allinbits.com to monorepo

**Comment by okwme** [comment]
https://github.com/cosmos/voyager
https://github.com/cosmos/cosmos.network
https://github.com/cosmos/explorer
https://github.com/tendermint/tendermint-vue
https://github.com/tendermint/tendermint.com

**Comment by NodeGuy** [comment]
We don't need Lerna because we're not publishing NPM modules, right?

Proposal for new repository name: `cosmos-ui`

**Comment by nylira** [comment]
No, don't need Lerna right now.

Haha, Voyager used to be called `cosmos-ui` not so long ago. The suggestion is a good one though.

**Comment by faboweb** [comment]
One more idea I wanted to share on the monorepo front:
How about we return to the option, where we export the components from Voyager (keeping Voyager as our prime focus project as is), we import Voyager into the websites, reusing the components and trigger rebuild/redeploy of the websites, when anything in “./components” changes.
+ If one of the reasons to do this is to integrate the development cycle of the websites more into the UI team, then we use https://www.zenhub.com/ to use all issues/projects in our planing process.

What do you think @nylira ?

**Comment by nylira** [comment]
The issue with that is that we have website components that need to be shared that are not used in Voyager. This still means a monorepo for the websites is a great idea. Explorer is a part web app and part website, so where does that fit in? Merge with Voyager? And then how about shared Voyager, Explorer, and website components?

Importing Voyager components into our websites still causes integration issues. Let’s say we want to a feature to NiListItem or NiField specifically for a website first, later to be used in Voyager. There’s no easy edit -> reload -> edit development cycle because the component is in Voyager, not the website.

**Comment by faboweb** [comment]
You can always use Voyager as a node_module in the website (or even just link it `yarn link`). Hot reloading should kick in when you change the code in the node_module (Voyager).
Some common components are already extracted as node_modules (like `@nylira/vue-field`). How about having a repo 'cosmos-ui-components' where all those common components live?

**Comment by faboweb** [comment]
Question: How often do our components change?

**Comment by nylira** [comment]
`@nylira/vue-field` and the others components took a huge amount of integration work and still has maintenance costs today. The dream has always been to extract the rest of our Cosmos UI components to npm, but I’d had to give up on that idea because it’s too much work to maintain so many separate repos. That’s how we ended up with different versions of NiPageHeader, NiSection, forms and modals -- all of which are reused in different levels across our Explorer, Voyager, and cosmos.network, projects. All those components are not up to date, and all the components have small improvements in them that are not being shared.

`yarn link` does work for editing a node module and viewing its changes in another repo. But it's still not the ideal workflow. 

Let's say we improve the `@nylira/vue-button`, `yarn link`ing it to the `cosmos.network` repo. We improved its usability. It looks great. We make a PR in the `cosmos.network` repo to bump the version. It's merged. We're not done--we still have go into all of our other repos that use `@nylira/vue-button` and also bump the version in their package.json. We have to make the 5-7 PRs to get this accomplished. Whoever reviews these PRs needs to know about what changed in the new version of `@nylira/vue-button` because there no diffs other than the version bump.

In the monorepo case, once we improve `@nylira/vue-button` (now just called `./components/button`) and get that PR merged, the button has been instantly improved in every single project that uses it. The person who reviews this PR knows exactly what happened to the button. 

*How often do our components change?* They should change whenever we need them to. The @nylira components would change a lot faster to suit our needs if they were not in a separate repository. We have been ignoring them as a team because they seem to work okay, but they don't have any unit tests (due to lack of time and oversight), yet they power critical parts of our app.

The Voyager product is still the primary focus of the UI team. If no one works on the websites except for Jordan and I, it's okay. But doing this change will help the two of us tremendously in maintaining these currently separated but very similar projects.

**Comment by faboweb** [comment]
A change would still need to be manually checked in all the products to see if there are side effects as there are no tests outside of voyager.

I want to make the work on the website easier as well! I am just looking for a third solution. How about having the websites in one repo as they are mostly the same code, common components in one repo, Voyager in one repo? Would this make things easier?

**Comment by NodeGuy** [comment]
> A change would still need to be manually checked in all the products to see if there are side effects as there are no tests outside of voyager.

The correct solution to this is to write tests.

@faboweb Why are you looking for a third solution?  What's your objection to a monorepo?

**Comment by faboweb** [comment]
* a lot of code in one place
* a lot of products in one place
* a lot of issues in one place

In coding developers aimed to make things more atomic to reduce side effects (like with the whole micro-services approach of the last years) and with this monorepo we do exactly the opposite and I am afraid we will have a lot of side effects.

**Comment by NodeGuy** [comment]
That's an important concern.  The question is whether the benefits of integration will exceed the costs of demodularization.  The current integration costs seem clear and significant to @nylira, which is why I imagine he's so excited about this solution.  The costs of a monolithic repo are not yet known.

This is why I propose that we combine only two repositories at first and see how it goes before any further consolidation.

**Comment by nylira** [comment]
I want a solution we can all agree on. If it helps to address your concerns @faboweb, we can try @NodeGuy's proposal of merging Voyager and Explorer as a first step. After we spend a couple weeks working with both projects in the same repo, we can do a re-evaluation of this approach.

**Comment by NodeGuy** [comment]
I don't like the idea of merging Explorer because we agreed in the meeting that we aren't going to take it on as a team.  We agreed that we would consider merging the website repos because we're already committed to working on them.

**Comment by nylira** [comment]
Explorer and Cosmos share the most components, which is why I mentioned it. Merging with cosmos.network works well also. It's a highly trafficked site that is critical to onboarding users to Voyager -- it could use more oversight.

**Comment by nylira** [comment]
I think we have consensus to go with a shared component library. A monorepo discussion we can have after launch.
