### ISSUE TITLE
Cannot recover account

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#724]
### Version

0.6.0 running `yarn testnet` on `develop`

### Description

I can't seem to import an account. I get this error:

![screen shot 2018-05-22 at 2 19 51 pm](https://user-images.githubusercontent.com/172531/40345351-73a346a8-5dcb-11e8-8c06-2bb9c1d01996.png)

### Log

[main.log](https://github.com/cosmos/voyager/files/2025206/main.log)

**Comment by faboweb** [comment]
Works fine for me. Did you copy your old keybase?

**Comment by faboweb** [comment]
I am asking because the log says there is an error in the binary "Unexpected type byte 94"

**Comment by nylira** [comment]
@faboweb I'm not sure what you mean by copy old keybase. I'm using an old 12 word seed that I have saved from January.

I still cannot recover that account. 

I'm going to try and create a new account and recover that.

**Comment by faboweb** [comment]
The 12 word seed structure changed. So old seeds may crash the new keybase algorithms. Was that the case? If yes tell me, and I create an issue about a better error handling in gaia.

**Comment by nylira** [comment]
Yes, this is case. Also, the new seeds are 16 words, we should update that.

**Comment by faboweb** [comment]
Done: https://github.com/cosmos/cosmos-sdk/issues/1051

**Comment by faboweb** [comment]
Closing as Billy created a wonderful work around.
