### ISSUE TITLE
Join the testnet meeting and clarify who needs to build the faucet

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#730]

**Comment by NodeGuy** [comment]
This is done.  I got a commitment from the testnet team that they will maintain a faucet if we maintain the code for it.

@adrianbrink wrote [code for a faucet](https://github.com/cosmos/faucet) and invited us to take ownership of it.  He said the code needs to be updated to use the latest version of Gaia.

**Comment by NodeGuy** [comment]
@nylira Would you please review this and move it to "Done" if you're satisfied?
