### ISSUE TITLE
Simplify the issue template and PR template.

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#736]
The templates have too much information and it's a hassle to delete all the lines before I can start getting into the details of the issue or the PR. It's a poor user experience.

I propose that we maintain a [CONTRIBUTING.md](https://blog.github.com/2012-09-17-contributing-guidelines/) and store all of this extra information there.

And I propose we simplify the templates to something like this:

## Issue Template
```
UI Version: 0.X.X
Description:
<!-- Steps to reproduce, logs, and screenshots are helpful for us to resolve the bug --> 
```

## Pull Request Template
```
Closes #ISSUE
Description:
<!-- Briefly describe what you're adding or fixing with this PR --> 
```

The simplified PR template also better enforces auto-closing of the relevant issue.

**Comment by faboweb** [comment]
Let's do it
