### ISSUE TITLE
Specifying a sdk-commit in the build script doesn't work

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#740]
Commit: 22e9bf5f6fd78866038be774b01d4a6590d79e38

![image](https://user-images.githubusercontent.com/5869273/40420820-e4abf4ee-5e89-11e8-8184-e2bc729acfc1.png)

**Comment by NodeGuy** [comment]
I'm hoping that #742 fixes this.

**Comment by faboweb** [comment]
This still fails (for different reasons):
![image](https://user-images.githubusercontent.com/5869273/40472636-4dacad0c-5f3a-11e8-9303-dcf0a0a29c93.png)

**Comment by nylira** [comment]
Building works for me with a specific SDK commit. I'm using the short form for the commit ID. Can you try this command?

```
yarn build --commit=e1658685 --network=app/networks/gaia-5001 --sdk-commit=187be1a5
```

**Comment by faboweb** [comment]
Sorry wrong screenshot. :/ Updated it. But for reasons it works now.

**Comment by nylira** [comment]
Should we close this then?

**Comment by faboweb** [comment]
Ok.
