### ISSUE TITLE
The build script doesn't output the same hashes for everybody

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#741]
If @okwme runs the build script with commits specified, he gets different hashes.

**Comment by NodeGuy** [comment]
I'm hoping that #742 fixes this.

**Comment by faboweb** [comment]
Could you maybe give an insight into what caused this?

**Comment by faboweb** [comment]
Which hashes do you guys (@okwme i.e.) get for `yarn build --commit=e1658685 --network=app/networks/gaia-5001 --sdk-commit=187be1a5`?

I have:
Cosmos Voyager-darwin-x64_0.6.2.tar.gz SHA256: 4de52ab5d8e025046b69961a8f75d45c7f2a20b919de089a2b3458fc57884db6
Cosmos Voyager-linux-x64_0.6.2.tar.gz SHA256: cce127af72400357a6ac69ec95058d6b38598d10b62258f7b49cb7ddde8177fa
Cosmos Voyager-win32-x64_0.6.2.zip SHA256: f51f24c1e5ef3f8ed77e5076ce13fa6969091865f36c216c2e529dd63d378f88

**Comment by nylira** [comment]
I can match your hashes with that command @faboweb 

Cosmos Voyager-darwin-x64_0.6.2.tar.gz SHA256: 4de52ab5d8e025046b69961a8f75d45c7f2a20b919de089a2b3458fc57884db6

Cosmos Voyager-linux-x64_0.6.2.tar.gz SHA256: cce127af72400357a6ac69ec95058d6b38598d10b62258f7b49cb7ddde8177fa

Cosmos Voyager-win32-x64_0.6.2.zip SHA256: f51f24c1e5ef3f8ed77e5076ce13fa6969091865f36c216c2e529dd63d378f88

**Comment by faboweb** [comment]
Nice!
