### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\HighTech\.cosmos-voyager\gaia-5001\genesis.json'

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#747]
https://sentry.io/tendermint/cosmos-voyager/issues/563062716/
https://sentry.io/tendermint/cosmos-voyager/issues/562837314

```
Error: ENOENT: no such file or directory, open 'C:\Users\HighTech\.cosmos-voyager\gaia-5001\genesis.json'
  at None (/C:/Users/HighTech/Desktop/resources/app/dist/index.html)
```

**Comment by faboweb** [comment]
Both users use Windows. Let's test on Windows.

**Comment by faboweb** [comment]
I think this will be fixed by the #735

**Comment by NodeGuy** [comment]
I can't build Gaia on Windows:

```
C:\Users\david\go\src\github.com\cosmos\cosmos-sdk>make get_vendor_deps
process_begin: CreateProcess(NULL, rm -rf vendor/, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [get_vendor_deps] Error 2
```

Looks like they broke Windows compatibility with the Makefile again.  I reported it here: https://github.com/cosmos/cosmos-sdk/issues/536

**Comment by faboweb** [comment]
Good find. Could we build insight Docker in the meantime?

David Braun <notifications@github.com> schrieb am Fr., 1. Juni 2018, 23:08:

**Comment by NodeGuy** [comment]
On Windows when I switch to the testnet I get `Error subscribing to new blocks/Internal error` but I don't get the above error.  It looks like this is fixed.
