### ISSUE TITLE
Move all 3 build hashes to end of build step for easier comparison.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#750]
Currently the build hashes are mixed in with a lot of other logging; let's put them all together at the end.

**Comment by jolesbi** [comment]
read my mind!

**Comment by jolesbi** [comment]
duplicated by https://github.com/cosmos/voyager/issues/744

**Comment by nylira** [comment]
#744 has a more detailed spec, definitely good to do though!
