### ISSUE TITLE
Prettier script doesn't work on Windows

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#753]
UI Version: Commit 8c004d6bc9835d6e5ee7929d73946181fea7b689

Description:

![image](https://user-images.githubusercontent.com/5869273/40607240-3427dab0-6268-11e8-845b-7d9db5410751.png)

This happened before and was the cause for changing the '`' syntax in the package.json script.

**Comment by NodeGuy** [comment]
OK.  We can look at it but again I raise the question:  It makes sense to me to be committed to making Voyager work on Windows for the first release but do we want to spend the extra attention necessary making it work for developers on Windows as well before first release?

**Comment by faboweb** [comment]
I sometimes don't have a Mac at hand. This should not stop me from developing, does it?

**Comment by nylira** [comment]
Just adding the solution here: https://github.com/prettier/prettier/issues/4086#issuecomment-370228517
