### ISSUE TITLE
Add link to log in the menu

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#768]
UI Version: 0.6.2

Description:

It could be nice to directly have a link that opens the main.log in the menu of Voyager.

**Comment by jolesbi** [comment]
maybe just in `devMode`?

**Comment by faboweb** [comment]
At least in `devMode`. It could help in cases where Voyager doesn't show an error but doesn't work properly. I am not sure, users know where to find the main.log.

**Comment by nylira** [comment]
In every mode would be nice. What would be even more accessible is a page in Voyager that has the live streaming logs in a scrollable window.

**Comment by faboweb** [comment]
I like the idea of the internal log viewer. But I guess we could should start with the easy solution and upgrade later to the internal view. What do you think?

**Comment by nylira** [comment]
Yep, let's stick with a simple link to start with.
