### ISSUE TITLE
Automatic fallback to mocked connection

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#776]
UI Version: 0.6.2

Description:

If a testnet is down, Voyager could automatically fallback to a mocked connection. Or it at least could offer to switch to a mocked connection.

**Comment by jolesbi** [comment]
i think offering to switch would be nice - maybe we can add it as an option on the full screen error page as well. especially when coupled with a more clear "THIS IS MOCKED" message (https://github.com/cosmos/voyager/issues/775)

**Comment by nylira** [comment]
Yes, I think we want to offer the switch but don't do it automatically. It would be confusing to see the entire UI change because of a temporary loss of connection. I've added it to the Planning project.

**Comment by faboweb** [comment]
I support the manual switch for stated reasons.

**Comment by faboweb** [comment]
Let's use full screen error

**Comment by faboweb** [comment]
This is done right?
