### ISSUE TITLE
Let's hardwire default paths to Gaia.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#784]
#748 builds Gaia binaries into `builds/gaia`.  If `BINARY_PATH` and `NODE_BINARY_PATH` aren't set then let's have Voyager look for them there, or even better let's hardwire the paths and get rid of `BINARY_PATH` and `NODE_BINARY_PATH`.

**Comment by faboweb** [comment]
Do we want devs to be able to overwrite the paths for some reasons?

David Braun <notifications@github.com> schrieb am Fr., 1. Juni 2018, 21:34:

**Comment by NodeGuy** [comment]
I can't think of a reason.  If a dev wants to use a different version of Gaia then he could specify a different version to be built.

**Comment by nylira** [comment]
The fewer configuration flags the better, I support this idea.

**Comment by jolesbi** [comment]
i'd like us to revisit this!

**Comment by faboweb** [comment]
What do you mean? What do you propose?

**Comment by jolesbi** [comment]
to run voyager i have to use this command:
```
BINARY_PATH=builds/Gaia/darwin_amd64/gaiacli NODE_BINARY_PATH=builds/Gaia/darwin_amd64/gaiad yarn testnet
```

but i'd like to be able to use this command:
```
yarn testnet
```

i think we're defaulting to local gaia instead of the gaia we're building with `yarn build:gaia`.

**Comment by okwme** [comment]
I thought this was w regard to letting the default gaia path point to the app-specific build, but still allowing setting the path explicitly for the scenario @faboweb outlined

**Comment by faboweb** [comment]
Then I got this wrong. Let's do it like that. :) Thank you for clarifying.

billy rennekamp <notifications@github.com> schrieb am Do., 12. Juli 2018,
13:36:
