### ISSUE TITLE
Remove webpack.main.config.js.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#785]
The spike (#680) demonstrated that we don't need it.

**Comment by NodeGuy** [comment]
I'm aborting this because I discovered that we're using Webpack for HMR with Vue.  This is more complicated than it should be but the best simpler alternative appears to be [electron-compile](https://github.com/electron-userland/electron-compile) and [it doesn't yet support HMR with Vue](https://github.com/electron-userland/electron-compile/issues/281).

**Comment by faboweb** [comment]
What is HMR may I ask?
