### ISSUE TITLE
new toggle component on preferences page doesn't toggle 

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#789]
console.logs `Analytics disabled in browser` on every click. no visual change or other errors. but seems not to be working.

**Comment by okwme** [comment]
this is new intended behavior after https://github.com/cosmos/voyager/pull/782

**Comment by jolesbi** [comment]
oh interesting. maybe a darker grey?

**Comment by faboweb** [comment]
We could add a message, that this doesn't enable because it is in dev mode.
