### ISSUE TITLE
Figure out where '/config.js' came from.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#792]
I deleted `/config.js` in https://github.com/cosmos/voyager/pull/604/commits/8225f3734a1c1d5adec85681867195f06b8c1183 but somehow it's back.  I failed to find out where it was reintroduced manually and searching via `git bisect`.

If we can't figure out where it came from then let's delete it.

**Comment by faboweb** [comment]
I think this got removed and put into other config files when we rebuild the build step. I also think we can remove it.
