### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#806]
UI Version: 0.6.2

Description:

@rigelrozanski mentioned, that it would be nice to allow emoji in monikers.

But it is important to not allow full unicode as this might be used to scam.

**Comment by jolesbi** [comment]
do they not work right now?

**Comment by rigelrozanski** [comment]
VERY important for the success of the network

**Comment by rigelrozanski** [comment]
Relavent - these are the markdown codes... maybe could reuse? https://gist.github.com/rxaviers/7360908#file-gistfile1-md

**Comment by faboweb** [comment]
Is ":" allowed in monikers?

Rigel <notifications@github.com> schrieb am Sa., 9. Juni 2018, 20:03:

**Comment by rigelrozanski** [comment]
I mean it's not a violation right now

**Comment by faboweb** [comment]
Not working on this right now.
