### ISSUE TITLE
Show bonding / redelegation transactions

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#808]
UI Version: 0.6.2

Description:

The bonding / unbdonding and redelegation transactions need to be visualized. Those transactions have a period when they are running but are not in full effect. For unbonding the user needs to send another transaction that finishes the unbonding. The same goes for redelegation. The SDK team agreed, that not sending these transactions will not have a negative effect for the user. But it will not free up funds. And it is desired that redelegations are closed to clean up. So we should incentivize the user to close these redelegations.
Maybe the ending txs could be send automatically by Voyager (optin/optout by the user).

pulling in @jolesbi @nylira

**Comment by jolesbi** [comment]
can we break down the flow for each use case?

bonding
---
1. user bonds some atoms
2. period of no effect?
3. another bonding tx?
4. bond finished?

unbonding
---
1. user unbonds some atoms
2. 1 month unbonding period
3. another unbond tx?
4. unbonding finished?

redelegation
---
1. user redelegates atoms
2. period of no effect?
3. another redelegation tx
4. redelegation finished?

**Comment by faboweb** [comment]
I think bonding works immediately.
The rest sounds right.

**Comment by faboweb** [comment]
Consider #355

**Comment by cwgoes** [comment]
I agree; the second transaction UX is terrible. `voyagerd` might work, but if this really would require something of that magnitude (unless you were planning to do it anyways), maybe we should revisit this on the SDK end.

**Comment by faboweb** [comment]
I agree with Chris. If this has such a big scope, let's look for another solution first.

**Comment by cwgoes** [comment]
> @cwgoes any updates?

On our radar but not going to happen this week, made an issue in the SDK repo - https://github.com/cosmos/cosmos-sdk/issues/1525.

**Comment by faboweb** [comment]
Linking #148

**Comment by faboweb** [comment]
- refactor LCD endpoints
- adding transaction to history page
- filter by transaction type in history

**Comment by faboweb** [comment]
Split 🍌

**Comment by cwgoes** [comment]
Note: https://github.com/cosmos/cosmos-sdk/issues/1525#issuecomment-413955612
