### ISSUE TITLE
Run 'yarn' in 'pull' and 'checkout' Git hooks.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#814]
If were to do this then any changes in the dependencies would be handled automatically when pulling new changes or switching branches.

**Comment by faboweb** [comment]
Good idea.

David Braun <notifications@github.com> schrieb am Mo., 11. Juni 2018, 14:04:

**Comment by faboweb** [comment]
A concern is that: Maybe `yarn link` breaks after `yarn`
