### ISSUE TITLE
Change default branch to 'master'.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#815]
Most users of Voyager are going to want to use the `master` branch but are shown `develop` when visiting the GitHub repository.

**Comment by faboweb** [comment]
Then you have to select develop on each PR. Are you sure this is necessary?

David Braun <notifications@github.com> schrieb am Mo., 11. Juni 2018, 14:06:

**Comment by NodeGuy** [comment]
Oh, that sounds like a pain.  Never mind then.
