### ISSUE TITLE
Begin extracting reused components into Cosmos UI repository.

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#820]
- [x] start repository with basic README, LICENSE, testing infrastructure
- [x] add the @nylira components that are using
- [x] extract the Voyager components we are reusing on the websites and explorer
- [x] add CircleCI integration
- [x] deploy version 0.1.0

**Comment by nylira** [comment]
I started the repository here. https://github.com/tendermint/ui

And I just got access from Jae to our https://www.npmjs.com/~tendermint organization, so let's deploy this module as `@tendermint/ui`!

**Comment by okwme** [comment]
skipping this one: https://github.com/nylira/vue-user-pages

**Comment by okwme** [comment]
running list of Ni Prefix Common components that should maybe be skipped:
 * NiBtnCopy
   * reason: imports electron and NiBtn

**Comment by faboweb** [comment]
we could make copyToClipboard a copy function passed in as a property
