### ISSUE TITLE
[yarn testnet] doesn't work with local node

### ISSUE THREAD

**Issue by zramsay** [cosmos/voyager#825]
UI Version: 542783c703a4004a4f802ff7df71fc9465332b3b

Description:

- latest gaia
- run `gaiad start`
- producing blocks
- run `COSMOS_NODE=localhost yarn testnet` per README instructions,
- get:

![screenshot from 2018-06-13 15-12-34](https://user-images.githubusercontent.com/8304391/41372845-78b9c088-6f1c-11e8-806f-e1e0ccc3c7b0.png)

**Comment by zramsay** [comment]
like, run `yarn` by itself or run `yarn install`? I did run `yarn install` prior to this command (followed the readme instructions). Running `npm install` then this command made it work, but that's not in the readme

**Comment by zramsay** [comment]
![screenshot from 2018-06-13 15-43-03](https://user-images.githubusercontent.com/8304391/41374200-8347aea8-6f20-11e8-87ac-ea38abec3638.png)

so it sort of works, although when i go to localhost:9080, nothing

**Comment by nylira** [comment]
Is this still an issue?

**Comment by zramsay** [comment]
probably. i don't see any evidence that it was fixed

**Comment by faboweb** [comment]
There is documentation how to run this with a local node and it works well.
