### ISSUE TITLE
Add loader for blocks

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#827]
UI Version: 0.6.2

Description:

If we are waiting for blocks, the block indicator shows '#0'. This is a little confusing I think.

![image](https://user-images.githubusercontent.com/5869273/41373276-bb8ff2be-6f04-11e8-9b1e-bae047bd96d3.png)

**Comment by okwme** [comment]
closing for https://github.com/cosmos/voyager/issues/850
