### ISSUE TITLE
Always build gaia

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#841]
UI Version: 0.7.0

Description:

When running `yarn build:gaia` and there is already a gaia version existing then no new version is build. This can produce situations, where you silently forget to upgrade the gaia version used to build Voyager.

**Comment by jolesbi** [comment]
i think this is causing me trouble today - will `build:gaia` override the existing binaries?

**Comment by zramsay** [comment]
it should override existing binaries, just like `go build` would

**Comment by NodeGuy** [comment]
Waiting for https://github.com/cosmos/cosmos-sdk/issues/1581 to be fixed.

**Comment by NodeGuy** [comment]
I can't reproduce this:

```shell
$ ls -l builds/Gaia/darwin_amd64/
total 102912
-rwxr-xr-x  1 david  staff  25169344 Jul  6 13:47 gaiacli
-rwxr-xr-x  1 david  staff  27030704 Jul  6 13:47 gaiad
$ builds/Gaia/darwin_amd64/gaiacli version
0.19.0-c6711810
$ yarn build:gaia
...
$ ls -l builds/Gaia/darwin_amd64/
total 115200
-rwxr-xr-x  1 david  staff  27661232 Jul 16 15:54 gaiacli
-rwxr-xr-x  1 david  staff  29923056 Jul 16 15:54 gaiad
$ builds/Gaia/darwin_amd64/gaiacli version
0.21.1-28a1b5eb
```

Did you update the version of Gaia to be built in `tasks/build/Gaia/COMMIT.sh` before running `yarn build:gaia`?

**Comment by jolesbi** [comment]
thank you for confirming that gaia builds override existing binaries! 

i think when i said this was causing me trouble - the _real_ issue was that my local voyager wasn't pointing to the version i was building a la https://github.com/cosmos/voyager/issues/784
