### ISSUE TITLE
Staking UI problems

### ISSUE THREAD

**Issue by nylira** [cosmos/voyager#842]
UI Version: 0.7.0

Description:

## Show all bonded validators

On my validator's account, which has 101 unbonded steak and 1000 bonded steak, the `Unbonded STEAK` bar is not full. This is expected, because the genesis.json file bonded 1000 steak for me automatically. However, we should be showing the validator I'm bonded to on the Bond STEAK page. 

Right now it's just confusing why I only have 9% of the `Unbonded STEAK` bar available.

<img width="1136" alt="screen shot 2018-06-14 at 2 33 14 pm" src="https://user-images.githubusercontent.com/172531/41395449-53e20a76-6fe0-11e8-8786-388ef29d72de.png">

## Wrong/missing green numbers on `Bond STEAK` page

In this case I'm trying to bond 5 steak each to `cwgoes` and `zach`. The green diff numbers shows me that I'm giving Chris 11 atoms (??) and zero to Zach. Something is wrong here.

<img width="759" alt="screen shot 2018-06-14 at 2 37 00 pm" src="https://user-images.githubusercontent.com/172531/41395495-7e3552ba-6fe0-11e8-8432-9c74fb202c47.png">

## Cannot bond to `cwgoes` and `zach`

When I try to apply the bond, I get this error:

<img width="1136" alt="screen shot 2018-06-14 at 2 39 13 pm" src="https://user-images.githubusercontent.com/172531/41395564-c8e12b5e-6fe0-11e8-955d-fbc18abe2581.png">

**Comment by nylira** [comment]
## Staking more STEAK than I have

The UI is allowing me to attempt to stake more than the available 9% of my STEAK. There should be an error message when the user attempts this.

## Visual problem with the green bonding bar

There is a gray circle on top of the green bonding bars. This circle has no function when increasing the user's bond with a particular validator. There's something wrong with div visibility or z-index here.

<img width="1136" alt="screen shot 2018-06-14 at 2 41 15 pm" src="https://user-images.githubusercontent.com/172531/41395643-08c1ac26-6fe1-11e8-8261-a8cb2c8d0735.png">

**Comment by mappum** [comment]
Hey @nylira, thanks for the comprehensive report.

Looks like #3 (and maybe #2) are due to the fact that one of the validators got revoked (a new feature we haven't thought about handling yet). It will probably make sense to just hide revoked validators, although I'm not sure how the UX should look if we are bonded to a validator later gets revoked.

**Comment by nylira** [comment]
One more issue. Validators get regularly revoked from the validator set for being offline for 50 out of the last 100 blocks.

- [ ] we need to show revoked validators in the staking page
- [ ] we need to allow users to unbond atoms from revoked validators
- [ ] we need to prevent users from being able to bond to revoked validators (or at least show a very big warning that they should not do this)
