### ISSUE TITLE
Staking works only a single time after starting voyager

### ISSUE THREAD

**Issue by patrickwieth** [cosmos/voyager#845]
UI Version: 0.7.0

Description:

Only on Arch Linux (Antergos) does staking work at all. It worked a single time. After that it doesn't work anymore. Then I restarted voyager and tried it again. If I select a different validator than zaki (the one I initially staked to), lino for example, it does not work, even though it prompts me a success popup. If I unselect lino and only have zaki and unbonded as options, it works to bond to zaki. Unbonding does not work at all.

![unbenannt](https://user-images.githubusercontent.com/10943178/41402230-0c85dd4c-6fc2-11e8-97fc-1d273ab733cb.png)

On Windows the initial delegation does not work at all.

**Comment by faboweb** [comment]
Thank you for submitting this error. We will investigate this.

**Comment by nylira** [comment]
Let's add this issue to #842 @mappum

**Comment by faboweb** [comment]
Closing in favor of the actively developed #842
