### ISSUE TITLE
Wallet Balance doesn't update

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#847]
UI Version: 0.7.0

Description: After getting voyager up for the first time on a fresh install and importing my keys i was told i held no tokens. I went to a faucet and requested some but still no tokens. Went to the block explorer and looked for a recent block with any transactions and found mine (i think it was mine). Went back to wallet and still no balance and then remembered there's a refresh button. maybe wallet balance should be automatically refreshed on the mounted event?

**Comment by okwme** [comment]
use RPC to watch for new TXs then trigger LCDs

**Comment by okwme** [comment]
`wrapper.vm.$nextTick` and `wrapper.update()` helped when moving components over when there were timing errors in tests

**Comment by nylira** [comment]
Added one more task to this issue

- [ ] remove update button

**Comment by faboweb** [comment]
Very similar to #679
