### ISSUE TITLE
Refactor main process

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#856]
Scope:
- [ ] Design of the refactor
- [ ] Implemantation

**Comment by NodeGuy** [comment]
Split out [refactor of Addressbook](https://github.com/cosmos/voyager/issues/1195).

**Comment by NodeGuy** [comment]
Proposed design:

* remove all global variables

**Comment by faboweb** [comment]
> move all code related to Gaia Lite into main/gaiaLite.js

created this already in the SDK 0.26 PR

**Comment by faboweb** [comment]
There is none no more
