### ISSUE TITLE
Notify users when they are trying to send coins to empty address

### ISSUE THREAD

**Issue by mossid** [cosmos/voyager#861]
If a user tries to send coins to an empty address(that does not have funds/has account nonce 0), there is a possibility that the user is sending to a wrong address. We can pop up a notification window that saying the destination account is empty before finalizing the transaction.

**Comment by faboweb** [comment]
Shouldn't bech32 prevent sending to a wrong address?

Joon <notifications@github.com> schrieb am Fr., 15. Juni 2018, 16:04:
