### ISSUE TITLE
Refactor build process to include networks dir and config toml

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#863]
UI Version: 0.X.X

Description:

**Comment by NodeGuy** [comment]
Blocked by https://github.com/cosmos/cosmos-sdk/issues/1581.

**Comment by NodeGuy** [comment]
@faboweb Would you please help with the unit tests?  I'm wasting a lot of time trying to figure out what's wrong: https://circleci.com/gh/cosmos/voyager/4521
