### ISSUE TITLE
preference page components

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#864]
<img width="275" alt="screen shot 2018-06-20 at 11 26 29 am" src="https://user-images.githubusercontent.com/6021933/41668199-cd3bd4ba-747c-11e8-9c07-ef34e80ffeb3.png">

1. excellent page!
2. i don't think the "off" state needs to be red or "danger" - something like `app-fg` would be suitable
3. the circle on the toggle (the part that you click) should have a border like our buttons
4. the dropdowns should match the button styling or vice-versa (the borders are different)
5. i think my preference would be for the in-button-icons to be on the right of the text

**Comment by okwme** [comment]
check #888
