### ISSUE TITLE
block explorer is janky

### ISSUE THREAD

**Issue by jolesbi** [cosmos/voyager#868]
as the blocks coming rolling in you'll notice that the second block disappears momentarily. the new block at the top of the list does not enter or appear gracefully.

here is an action shot:
<img width="752" alt="screen shot 2018-06-21 at 11 52 01 pm" src="https://user-images.githubusercontent.com/6021933/41757144-278f2430-75ae-11e8-975c-d595005c1c9c.png">

**Comment by nylira** [comment]
Closing this in favor of discussing in #869. I don't think a rolling list of blocks makes sense--it doesn't offer value to the user.

**Comment by faboweb** [comment]
I do not 100% agree with closing issues based on an open spike. I would prefer if we put such issues in "Discuss".
