### ISSUE TITLE
theme broken

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#874]
UI Version: develop

Description: dark theme on light theme

![screenshot 2018-06-25 12 31 38](https://user-images.githubusercontent.com/964052/41845472-e928133c-7873-11e8-916f-25c9e7a6721a.png)
![screenshot 2018-06-25 12 31 32](https://user-images.githubusercontent.com/964052/41845475-eafc6c94-7873-11e8-9820-6a542a4eeed8.png)

**Comment by jolesbi** [comment]
most likely this is a result of my contrast PR. i will fix ASAP.
