### ISSUE TITLE
Bonding Text is confusing

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#877]
UI Version: 0.7.0

Description: When staking to a delegator you have the checkbox that says: "Yes, update my bonds. I understand unbonding will take 30 days". This reads like it's an option instead of a disclaimer. 

Maybe good to add something like: "Please confirm you understand that after staking tokens to a validator it will take at least 30 days to remove your tokens again." 

Maybe it's good to stop using both "stake" and "bond" as they're basically the same thing, right?

![screenshot 2018-06-25 15 31 53](https://user-images.githubusercontent.com/964052/41853017-02450230-788d-11e8-8f39-d4ad7d160bf4.png)

**Comment by jolesbi** [comment]
great point @okwme !

> Maybe it's good to stop using both "stake" and "bond" as they're basically the same thing, right?

yes, please let's use stake / staking.

**Comment by nylira** [comment]
I think Rigel wants to use Delegating and Undelegating everywhere, instead of "stake" or "bond". Pingingg @rigelrozanski

**Comment by rigelrozanski** [comment]
Having meditated on this, I think the clearest language can be broken down as following:
 - To describe a delegators *action* we use `delegating`/`undelegating`/`redelegating`
 - To describe the created *object* we use `delegation`/`unbonding-delegation`/`redelegation`
 - (rare) to describe the *state of tokens* we use `bonded`/`unbonding`/`unbonded`

**Comment by rigelrozanski** [comment]
Thus I would say:
```
Please confirm you understand that after delegating to a validator, undelegating takes 3 weeks. Note however that you may redelegate to other validators instantaneously. See XXX for a more detailed explanation
```
I'd include a link to further descriptions

**Comment by okwme** [comment]
moved to #781
