### ISSUE TITLE
Is pink meant to be part of the light theme?

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#878]
UI Version: 0.7.0

Description: The pink highlighting looks out of place on the light theme. It mainly appears on form inputs although also a little bit in the sidebar. Maybe it should be `--accent` instead of `--mc`? did this recently change and that's why it sticks out to me so much?

![screenshot 2018-06-25 15 42 28](https://user-images.githubusercontent.com/964052/41853626-7c3d0190-788e-11e8-803a-c170764a1b39.png)
![screenshot 2018-06-25 15 42 54](https://user-images.githubusercontent.com/964052/41853637-81d97d4a-788e-11e8-9557-add60138daa8.png)
![screenshot 2018-06-25 15 42 18](https://user-images.githubusercontent.com/964052/41853630-7e75744c-788e-11e8-81bb-8f5e45136c74.png)
![screenshot 2018-06-25 15 43 07](https://user-images.githubusercontent.com/964052/41853639-83605f62-788e-11e8-84aa-831ac0ae0a15.png)

**Comment by jolesbi** [comment]
in the dark-theme, the pink color indicates the selected / focussed state. we can use a different color for the light theme though i don't think this is an issue as it stands.

**Comment by nylira** [comment]
Pink and purple are pretty similar. I will work with Jordan on the colors. Let's close this PR for now.
