### ISSUE TITLE
Validator status still faked by utility script

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#880]
UI Version: 0.7.0

Description: The first 100 validators are given the attribute `isValidator` set to `true` by `scripts/indicateValidator.js` during the `addDelegate` mutation in `modules/delegates.js`

**Comment by faboweb** [comment]
LCD endpoint to get validatorset: `/validatorsets/latest`. For now we probably need to poll this. @mappum does Tendermint deliver validators via RPC?

**Comment by mappum** [comment]
>does Tendermint deliver validators via RPC?

Do you mean in an event? Not that I'm aware of, but we are already getting every header so we could check that to see if the validator hash changes to know to trigger fetching the new validator set.

**Comment by faboweb** [comment]
Sounds good. :)

Matt Bell <notifications@github.com> schrieb am Mo., 2. Juli 2018 um
18:00 Uhr:
