### ISSUE TITLE
Show versions

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#886]
UI Version: 0.7.0

Description:

Following up on https://github.com/cosmos/voyager/issues/767 we may want a modal that shows the versions currently used in Voyager or incorporate these informations on the preferences page.

**Comment by nylira** [comment]
We have a **lot** of dependencies. Instead of a modal, let's make a very simple full page that lists all of our `package.json` dependencies.

**Comment by okwme** [comment]
any inputs on these variations?
![screenshot 2018-07-02 19 21 26](https://user-images.githubusercontent.com/964052/42177481-2c6aef84-7e2d-11e8-801d-821a0b7f4887.png)
![screenshot 2018-07-02 19 21 15](https://user-images.githubusercontent.com/964052/42177484-2e62a61a-7e2d-11e8-80e3-8f9e361c0746.png)
![screenshot 2018-07-02 19 20 46](https://user-images.githubusercontent.com/964052/42177490-325ffdda-7e2d-11e8-950f-339cfe539c72.png)
![screenshot 2018-07-02 19 20 49](https://user-images.githubusercontent.com/964052/42177487-3095ead2-7e2d-11e8-81fc-d86c2b743bc1.png)

**Comment by faboweb** [comment]
Nice :)
I think the network already shows in the network indicator and is therefor doubled. What do you think?

**Comment by faboweb** [comment]
What about the Tendermint version?

**Comment by faboweb** [comment]
For the design I like the 2nd one the most as it looks the cleanest.

**Comment by nylira** [comment]
I think the popup is cleanest. But I wonder why the version shows 0.4.3. Good work.

**Comment by okwme** [comment]
Version were hard copy dummy
got real info in the popup, how's this:
![screenshot 2018-07-03 15 40 33](https://user-images.githubusercontent.com/964052/42223239-8cdc1c76-7ed7-11e8-8b7a-a56c0757ab88.png)
![screenshot 2018-07-03 15 40 36](https://user-images.githubusercontent.com/964052/42223241-8f76c076-7ed7-11e8-933f-7ffdd4814cfa.png)

**Comment by jolesbi** [comment]
looks good!

maybe the left side should ay "Version information" and the button on the right could say "show versions" - as the buttons tend to contain a verb and the left side (description) is usually more descriptive 😄

**Comment by faboweb** [comment]
What about the Tendermint version?

**Comment by okwme** [comment]
@Fabo and I discussed Tendermint version and decided that because the tm version can be derived from Cosmos SDK version, and because there's no command available in gaiacli or gaiad right now to get the tendermint version that we skip it until it is requested.

![screenshot 2018-07-04 10 55 11](https://user-images.githubusercontent.com/964052/42267304-f5332e4e-7f78-11e8-8212-01793c074449.png)
![screenshot 2018-07-04 10 55 14](https://user-images.githubusercontent.com/964052/42267309-f6cfbb0a-7f78-11e8-97dd-edeb6debbf44.png)
