### ISSUE TITLE
Receive button invisible on small screens

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#897]
UI Version: 0.7.0 / be57bdeff30681ec65d97e633f829ba343a136bf

Description:

![image](https://user-images.githubusercontent.com/5869273/42155883-e0512ec6-7de9-11e8-995b-b86c124887c3.png)

This was already fixed, but probably was lost in the transition to tendermint/UI

**Comment by jbibla** [comment]
confirmed - this is no longer an issue.

<img width="358" alt="screen shot 2018-08-14 at 5 48 00 pm" src="https://user-images.githubusercontent.com/6021933/44120389-358e6954-9fea-11e8-9119-ecacf170a7c4.png">
