### ISSUE TITLE
Menu selection design inconsistent

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#906]
UI Version: 0.7.0

Description:

Menu:
![image](https://user-images.githubusercontent.com/5869273/42175713-b2480382-7e26-11e8-99b2-d2d7a10502ae.png)

List Item:
![image](https://user-images.githubusercontent.com/5869273/42175731-c3838856-7e26-11e8-95c8-182df998d455.png)

I also think there are too many colors in the menu selection state.

**Comment by nylira** [comment]
I'm working with Jordan on a new set of Cosmos colors in this website PR: https://github.com/cosmos/cosmos.network/pull/198#issuecomment-402085265. Once we agree on that one, we can implement it in Voyager. One the primary aims of that PR is to reduce our theme colors to 11-13.

**Comment by jbibla** [comment]
this has been resolved. i think our hover states are satisfactory.

<img width="262" alt="screen shot 2018-08-14 at 5 50 40 pm" src="https://user-images.githubusercontent.com/6021933/44120526-9e67fc56-9fea-11e8-89ec-321325060a87.png">
<img width="1049" alt="screen shot 2018-08-14 at 5 50 29 pm" src="https://user-images.githubusercontent.com/6021933/44120538-a8cd5d1c-9fea-11e8-9da4-e922c0adb625.png">
