### ISSUE TITLE
Transactions design files

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#913]
We would like to have a design files showing the design of each transaction types.

**Comment by nylira** [comment]
By design file you mean specification file right? Not visual design.

**Comment by faboweb** [comment]
Actually Billy meant visual design.

**Comment by okwme** [comment]
the concepts are kinda married tho:  
what are all the different tx types -> what should each of them look like?

**Comment by jolesbi** [comment]
related to #891

**Comment by nylira** [comment]
Transaction types:

1. To
2. From
3. Self
4. Bond
5. Unbond
6. Vote

**Comment by okwme** [comment]
7. Swap Bond

**Comment by faboweb** [comment]
8. End unbonding
9. End redelegation
10. Proposal creation

billy rennekamp <notifications@github.com> schrieb am Di., 10. Juli 2018,
18:44:

**Comment by faboweb** [comment]
Redelegation. And yes we need to implement that as well.

**Comment by NodeGuy** [comment]
Hey JB, I see you haven't moved this to `Scope Clarified` yet.  Is there something unclear about it?

**Comment by faboweb** [comment]
This is how it currently looks: 
![image](https://user-images.githubusercontent.com/5869273/43737513-cfa77122-99c1-11e8-85fc-dc75f21f7f2e.png)

**Comment by faboweb** [comment]
Pulling in @nylira

**Comment by faboweb** [comment]
Looking good. :)

**Comment by faboweb** [comment]
This is done
