### ISSUE TITLE
Rename yarn testnet to yarn start

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#920]
UI Version: 0.7.0

Description:

The default npm and yarn start cmd is `yarn start` / `npm start`. I think we should move to this default. Specifying a testnet still works like this: `yarn start gaia-6002`.

**Comment by nylira** [comment]
The convention for Vue is `yarn serve`, because we're running a development server to bundle serve the frontend. Could we use that instead of `yarn start`?

**Comment by faboweb** [comment]
We do yarn start
