### ISSUE TITLE
--bright yes or no

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#923]
UI Version: 0.7.0

Description: the css variable `--bright` is used in a few places in the tm components. At some point it was removed from the `variables.styl`. When added back (as the original white) it seems to mess up the look of a few things, as well as improve the look of a few things. Maybe we could decide whether or not it belongs and if so where.

![screenshot 2018-07-04 15 17 28](https://user-images.githubusercontent.com/964052/42279217-637071fe-7f9d-11e8-9cfe-c77d1c513da2.png)
![screenshot 2018-07-04 15 17 32](https://user-images.githubusercontent.com/964052/42279221-651d9392-7f9d-11e8-962e-f59ed7639c37.png)
![screenshot 2018-07-04 15 28 28](https://user-images.githubusercontent.com/964052/42279697-f2f5783c-7f9e-11e8-8650-d4acd56c56ff.png)
![screenshot 2018-07-04 15 28 35](https://user-images.githubusercontent.com/964052/42279699-f472c278-7f9e-11e8-90ab-fe88cbadd938.png)

**Comment by jolesbi** [comment]
thank you for pointing this out!

peng and have been discussing use of color here https://github.com/cosmos/cosmos.network/pull/198

we should have this sorted out shortly!

**Comment by faboweb** [comment]
Is this still an issue?

**Comment by okwme** [comment]
think this was related to this issue:
https://github.com/cosmos/voyager/issues/906
looks like it's all resolved tho
