### ISSUE TITLE
Delegated Bonding Slider Grey Circle

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#924]
UI Version: 0.7.0

Description: When delegating stake you use the slider that has a grey part on the left. Is this grey part supposed to represent already bonded stake? if so maybe it should be removed when at 0 as it blocks the visual impact of making a first small delegation as mentioned in #781 

![screenshot 2018-07-04 15 33 50](https://user-images.githubusercontent.com/964052/42279959-aa32e070-7f9f-11e8-8cf0-aed2df50a08a.png)
![screenshot 2018-07-04 15 33 14](https://user-images.githubusercontent.com/964052/42279963-ab9b8138-7f9f-11e8-8a57-e874b255971a.png)

also: is it broken? can't confirm if the grey part increases and creates a new lower bound while the network is currently stopped

**Comment by faboweb** [comment]
We assume this is closed
