### ISSUE TITLE
Weird characters on macOS

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#926]
UI Version: 0.7.1

Description:

See the weird characters (`Â` and `â€“`) in the screenshot:

![screen shot 2018-07-04 at 4 24 19 pm](https://user-images.githubusercontent.com/2148537/42293249-e0e7809c-7fa6-11e8-88e9-a2d8210fa53f.png)

**Comment by faboweb** [comment]
Character being badly shown seem to be escaped ones like `&nbsp;`, `&ndash;` and additionally `…`.

**Comment by faboweb** [comment]
Maybe has to do with the pug-template parsing?

**Comment by NodeGuy** [comment]
Can't replicate.
