### ISSUE TITLE
block explorer too fast to select desired block

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#945]
UI Version: 0.7.0

Description: On the block explorer if you are trying to select a specific block new ones are coming in and pushing them all down so fast that it's difficult to click it. Maybe we could autoscroll with the new blocks or could put them inside of an overflow auto div so that once scrolled the view stays?

**Comment by faboweb** [comment]
Sounds like an easy fix. Also consider #868.

But we may want to use the cross product explorer anyway I thought. Should we keep fixing the explorer in that case?

**Comment by okwme** [comment]
it would be a fix for both of them

**Comment by jolesbi** [comment]
too fast, too furious

**Comment by faboweb** [comment]
Maybe: Only autoscroll if you are on top of the list
