### ISSUE TITLE
If all nodes are down on start, Voyager hangs in loading screen

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#947]
UI Version: 0.7.1

Description:
If all nodes are down on start, Voyager hangs in loading screen

**Comment by NodeGuy** [comment]
Right now I can't even get to the loading screen.

What behavior do we want here instead?

**Comment by faboweb** [comment]
Going straight to the "retry connection modal" I propose.

In a perfect world: going to login first :)
