### ISSUE TITLE
reload on mock server error

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#948]
UI Version: 0.7.0

Description: Reloading on testnet server works now thanks to https://github.com/cosmos/voyager/pull/940 but it still doesn't work on the mock server

**Comment by ricburton** [comment]
![screen shot 2018-07-18 at 09 33 05](https://user-images.githubusercontent.com/438160/42884953-afc1b952-8a6d-11e8-856a-cd8419bbc0f6.png)
![screen shot 2018-07-18 at 09 33 09](https://user-images.githubusercontent.com/438160/42884959-b23f2a7a-8a6d-11e8-98a5-79307167dd17.png)
<img width="458" alt="screen shot 2018-07-18 at 09 30 45" src="https://user-images.githubusercontent.com/438160/42884962-b421b704-8a6d-11e8-95b3-999e46b574d3.png">

This was my experience trying to go on a bold voyage. ⚓️

**Comment by faboweb** [comment]
@ricburton do these error relate to reloading on the mocked network?

**Comment by ricburton** [comment]
Not sure how to do that. This is what happens: https://cl.ly/3k220x1O3d0x

Richard

**Comment by faboweb** [comment]
On which Voyager version are you?

**Comment by NodeGuy** [comment]
I can't test the mock server because Voyager crashes on startup.

**Comment by jolesbi** [comment]
@NodeGuy there was once a way - may have been removed. @faboweb will know.

@ricburton that was most likely an issue with the previous testnet - unrelated to the mock server. we'll have a new version of voyager out for the (hopefully more stable 🤞) gaia-7002 very soon.

**Comment by faboweb** [comment]
Using the env flag "COSMOS_MOCKED=true" should start Voyager in mocked mode.

**Comment by faboweb** [comment]
I can confirm that this is an issue:
![2018-07-27 10 32 22](https://user-images.githubusercontent.com/5869273/43310676-8ab9a774-9188-11e8-890a-8cb6c683e71b.gif)

**Comment by NodeGuy** [comment]
What is it that you're doing?  Just switching back and forth between the Live Testnet and the Mock Testnet?  I can do that without error.

**Comment by faboweb** [comment]
Switching to a mock network and then refreshing the view.

David Braun <notifications@github.com> schrieb am Fr., 27. Juli 2018, 18:41:

**Comment by NodeGuy** [comment]
I can't reproduce it:

![reload on mock server](https://user-images.githubusercontent.com/2148537/43338286-f395a980-91a3-11e8-9237-cb1866a897bc.gif)

**Comment by faboweb** [comment]
Refreshing the view with CMD+F5 ;)

**Comment by NodeGuy** [comment]
When I type CMD+R nothing happens.  I don't see it in any of the menus.

Are you starting with `yarn start`?

**Comment by faboweb** [comment]
CMD+R is refreshing chrome. You have to type it while focussing the dev-tools.

**Comment by NodeGuy** [comment]
Thank you, now I can recreate the problem.

The bug is caused by the mock setting not being persisted.  Why are we not persisting all of the Vuex state in `localStorage`?

**Comment by faboweb** [comment]
Hmm, If we persistent the mocked config, Voyager would also be mocked mode on the next start. Do we want that?

**Comment by NodeGuy** [comment]
Yes, why wouldn't we?  To me that would be consistent with the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by faboweb** [comment]
The sign-in flow sucks in this case, as the user reopens Voyager and then needs to signin and then switch to the live network to then sign in again.

**Comment by faboweb** [comment]
I would expect Voyager "to just work" again when reopening it again.

**Comment by faboweb** [comment]
Idea how to implement:
- tell the main thread that we are running in mocked mode
- on booting, the main thread tells the view thread we are running in mocked mode

But: For simplicity I agree that we just store it as well as balances.et Al. We can then later check if this is confusing for users.

**Comment by NodeGuy** [comment]
I'm confused.  If the sign-in flow sucks with my suggestion then why not implement your ideas?

I don't think my idea is any simpler.
