### ISSUE TITLE
importing new seed doesn't use bech32

### ISSUE THREAD

**Issue by okwme** [cosmos/voyager#954]
UI Version: 0.7.0

Description: non breaking errors when importing an account from seed. 

Steps to reproduce:

 1.  Import account using seed after starting a new local node (as per fabo's readme instructions)
 2. Check network tab and see:
    * Error 400 on `http://localhost:9070/accounts/6C77215680044609216333D009E24890E6F6BC50`
    * Error 400 on `http://localhost:9070/txs?tag=sender_bech32=%276C77215680044609216333D009E24890E6F6BC50%27`
    * Error 400 on `http://localhost:9070/txs?tag=recipient_bech32=%276C77215680044609216333D009E24890E6F6BC50%27`
 3. Check console tab and see:
```
xhr.js?ec6c:178

GET http://localhost:9070/txs?tag=recipient_bech32=%276C77215680044609216333D009E24890E6F6BC50%27 400 (Bad Request)
GET http://localhost:9070/accounts/6C77215680044609216333D009E24890E6F6BC50 400 (Bad Request)
GET http://localhost:9070/txs?tag=sender_bech32=%276C77215680044609216333D009E24890E6F6BC50%27 400 (Bad Request)


lcdClient.js?312d:43

Uncaught (in promise) Error: decoding bech32 failed: failed converting data to bytes: invalid character not part of charset: 98
Uncaught (in promise) Error: decoding bech32 failed: failed converting data to bytes: invalid character not part of charset: 98
```

**Comment by faboweb** [comment]
This is a know bug resolved in the SDK 0.20.0.
