### ISSUE TITLE
Change how the Date object is fixed in tests

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#961]
UI Version: 0.7.1

Description:

Ref: https://github.com/cosmos/voyager/pull/952/files/a6736f42db3b2c8258b8e06b5d1d05c141e9c3ca#diff-48654224d7b96335593ca66a7728c572R1
@NodeGuy

**Comment by sabau** [comment]
Can we use the normal date and override only when needed with i.e.

```
jest.spyOn(Date, `now`).mockImplementation(() => 43000)
```

**Comment by faboweb** [comment]
Uhh that's a very good idea :)
