### ISSUE TITLE
Remove cookieconsent

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#972]
UI Version: 0.7.1

Description:

This errors frequently (on CI) and is a potential security hole.

Error:

`file://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css - Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by okwme** [comment]
blocked by https://github.com/tendermint/ui/pull/61
cookie consent comes from tendermint/ui so i didn't remove it but i references the local file instead of trying to use the CDN, hopefully that resolves our issue here

**Comment by okwme** [comment]
fixed by https://github.com/cosmos/voyager/pull/1162
