### ISSUE TITLE
Password input fails in the beginning

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#982]
UI Version: 0.7.1

Description:

When I first enter my password it fails. Maybe the binary has not started yet?

**Comment by NodeGuy** [comment]
Hi Matt, I see you haven't moved this to `Scope Clarified` yet.  Is there anything confusing about it?

**Comment by mappum** [comment]
I'm unable to reproduce the issue.

@faboweb is this still happening for you?

**Comment by faboweb** [comment]
Yes
