### ISSUE TITLE
Identify and avoid connecting to non-indexing nodes

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#988]
UI Version: 0.7.1

Description:

Usually nodes are not indexing transactions. This results in falsely txs not showing.

Tendermint shows us if a node is indexing via the status endpoint and the property `node_info.other.tx_index`

**Comment by jolesbi** [comment]
is it unreasonable to propose that voyager won't connect to a non-indexing node without the user saying this is ok?

1. voyager tries to connect to an indexing node
2. if no indexing nodes found, full screen modal telling user that voyager can't find any indexing nodes, asking if voyager should try connecting to non indexing nodes
3. features effected by non-indexing nodes (like tx history) should have special error message stating that the node voyager is connected to is "non-indexing" with a button to try to find (or run locally?) an indexing node.

what do you think?

**Comment by faboweb** [comment]
Totally what I was thinking. Two 👍 from me.

**Comment by faboweb** [comment]
- let's try to push for indexing being mandatory

**Comment by jbibla** [comment]
also show correct message

**Comment by NodeGuy** [comment]
Another idea:  How about Voyager doesn't connect to non-indexing nodes, period.  We can handle more cases after launch.

**Comment by faboweb** [comment]
I guess most staking information. Am I wrong @fedekunze ?
I like the idea to skip non-indexing nodes. We just need to make sure, we have at least one per testnet. This should be possible, as we can make the testnet team do it. :)

**Comment by fedekunze** [comment]
+ @faboweb @NodeGuy I like the idea of skipping non-indexing nodes, since we won't be able to query txs by tag. That affects mostly all actions (_i.e_ governance, staking, transfers, etc) and important queries we need in order for Voyager to work smoothly

**Comment by fedekunze** [comment]
@faboweb @NodeGuy should we also open an issue for more docs of what `Node indexing` is and what are the pros/cons of it ?

**Comment by faboweb** [comment]
yes @fedekunze please open one

**Comment by fedekunze** [comment]
See cosmos/cosmos-sdk#2132

**Comment by NodeGuy** [comment]
OK, I'll make Voyager skip non-indexing nodes.

**Comment by faboweb** [comment]
The mentioned status `node_info.other.tx_index` doesn't show actual indexing.

Example:
103.72.145.36:26657 shows  `tx-index=on` but doesn't show txs.
195.201.141.141:26657 shows  `tx-index=on` and shows txs.

Pulling in SDK team @cwgoes

**Comment by NodeGuy** [comment]
Please submit a bug report in the SDK repo.

**Comment by fedekunze** [comment]
See cosmos/cosmos-sdk#2183

**Comment by faboweb** [comment]
Isn't indexing handled by Tendermint?

**Comment by NodeGuy** [comment]
Sounds like the bug should be filed in the Tendermint repo.

**Comment by faboweb** [comment]
Created an issue on the Tendermint repo: https://github.com/tendermint/tendermint/issues/2304

**Comment by fedekunze** [comment]
We shouldn't be blocked on Voyager side. Even in the case there's an issue on the SDK or Tendermint, we still need to identify non indexing nodes. Therefore I'm removing the `blocked` label

**Comment by faboweb** [comment]
The problem is: We can't identify those nodes yet. There is no proposal for how to solve this yet.

**Comment by NodeGuy** [comment]
Is this now irrelevant because of https://github.com/cosmos/voyager/issues/1291?

**Comment by faboweb** [comment]
> Is this now irrelevant because of #1291?

We can ice this PR. We can get back to it after launch.

**Comment by cwgoes** [comment]
I think we should keep trying to fix this - Voyager isn't the only client that might need to query indexing status, and we want the user to have the ability to select a different full node.

I'll try to take a look today or tomorrow.

**Comment by NodeGuy** [comment]
Iced.
