### ISSUE TITLE
address themes complexity (remove light theme)

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#993]
i'd like to propose that we remove the light theme AND OR generate the `themes.json` files dynamically (on serve and on build). 

1. there is no need to maintain two themes. it adds complexity and maintenance that we don't need.
2. having to maintain a component library across two themes is harder than with one theme (which is hard enough)
3. having to change colors in two places in voyager isn't very DRY

**Comment by faboweb** [comment]
dev toggle this feature
