### ISSUE TITLE
No data available yet.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#996]
UI Version: 0.7.1

Description:

Wallet shows "No data available yet."

![screen shot 2018-07-20 at 7 15 45 pm](https://user-images.githubusercontent.com/2148537/43029001-54414526-8c51-11e8-9e49-4852fa6d57a6.png)

**Comment by NodeGuy** [comment]
Hmm.  If the the transaction subscription is broken then I guess this is the best we can hope for.

**Comment by faboweb** [comment]
How has the transaction subscription influence on the shown balance?

**Comment by NodeGuy** [comment]
I don't know—I was making an assumption.

If they're unrelated then the message `No data available yet.` is a UX problem because as a user I appear to be connected to a working network but don't know how many tokens I have nor what to do to fix the problem.  Simply waiting for time to pass didn't work.

Ideally the message would prompt the user towards a fix.

**Comment by faboweb** [comment]
How about first investigating if we are correct about the state showing "account has no coins yet" and then rewrite this issue?

**Comment by jolesbi** [comment]
agreed - the message should indicate that you don't have any balances (if you don't).
