### ISSUE TITLE
error subscribing to transactions

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#997]
UI Version: 0.7.1

Description:

Upon app loading:

<img width="1261" alt="screen shot 2018-07-20 at 7 17 15 pm" src="https://user-images.githubusercontent.com/2148537/43029062-96dccf5e-8c51-11e8-905d-8243e180cee7.png">

**Comment by faboweb** [comment]
We have to leave one open ;)

**Comment by NodeGuy** [comment]
Haha, oops.  Usually in the case of a dupe the original issue is left open.
